#!/bin/sh
#
# Starts rfd.
#

LOGLEVEL_RFD=5
CFG_TEMPLATE_DIR=/etc/config_templates

init() {
	export TZ=`cat /etc/config/TZ`

	if [ ! -d /etc/config/rfd ] ; then
  		mkdir /etc/config/rfd
	fi
	if [ ! -e /etc/config/rfd.conf ] ; then
		cp $CFG_TEMPLATE_DIR/rfd.conf /etc/config
	fi

        # Bug fix
        grep "/etc/config/rfd/keys" /etc/config/rfd.conf
        if [ $? == 0 ] ; then
                echo "Copy rfd files"
		cp $CFG_TEMPLATE_DIR/rfd.conf /etc/config
        fi

	if [ ! -e /etc/config/syslog ] ; then
		cp $CFG_TEMPLATE_DIR/syslog /etc/config
	fi
	if [ -e /etc/config/syslog ] ; then
  		. /etc/config/syslog
	fi

}

start() {
	echo -n "Starting rfd: "
	init
        echo "Waiting for multimacd to get ready"
        eq3configcmd wait-for-file -f /dev/mmd_bidcos -p 1 -t 5
	start-stop-daemon -S -q -p /var/run/rfd.pid --exec /bin/rfd -- -d -f /etc/config/rfd.conf -l $LOGLEVEL_RFD
	echo "OK"
}
stop() {
	echo -n "Stopping rfd: "
	start-stop-daemon -K -q -p /var/run/rfd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

