################################################################################
#
# wiringpi for ODROID (https://github.com/hardkernel/wiringPi)
#
################################################################################

WIRINGPI_ODROID_VERSION = 2f8842f1ff6a264a594a4fb8fd6d00bb9f6752bc
WIRINGPI_ODROID_SITE = git://github.com/hardkernel/wiringPi.git

WIRINGPI_ODROID_LICENSE = LGPL-3.0+
WIRINGPI_ODROID_LICENSE_FILES = COPYING.LESSER
WIRINGPI_ODROID_INSTALL_STAGING = YES

ifeq ($(BR2_STATIC_LIBS),y)
WIRINGPI_ODROID_LIB_BUILD_TARGETS = static
WIRINGPI_ODROID_LIB_INSTALL_TARGETS = install-static
WIRINGPI_ODROID_BIN_BUILD_TARGETS = gpio-static
else ifeq ($(BR2_SHARED_LIBS),y)
WIRINGPI_ODROID_LIB_BUILD_TARGETS = all
WIRINGPI_ODROID_LIB_INSTALL_TARGETS = install
WIRINGPI_ODROID_BIN_BUILD_TARGETS = all
else
WIRINGPI_ODROID_LIB_BUILD_TARGETS = all static
WIRINGPI_ODROID_LIB_INSTALL_TARGETS = install install-static
WIRINGPI_ODROID_BIN_BUILD_TARGETS = all
endif

define WIRINGPI_ODROID_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)/wiringPi DEFS='-D_GNU_SOURCE -DODROID_BOARD' $(WIRINGPI_ODROID_LIB_BUILD_TARGETS)
	$(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)/devLib DEFS='-D_GNU_SOURCE -DODROID_BOARD' $(WIRINGPI_ODROID_LIB_BUILD_TARGETS)
	$(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)/gpio DEFS='-D_GNU_SOURCE -DODROID_BOARD' $(WIRINGPI_ODROID_BIN_BUILD_TARGETS)
endef

define WIRINGPI_ODROID_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)/wiringPi $(WIRINGPI_ODROID_LIB_INSTALL_TARGETS) DESTDIR=$(STAGING_DIR) PREFIX=/usr LDCONFIG=true
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)/devLib $(WIRINGPI_ODROID_LIB_INSTALL_TARGETS) DESTDIR=$(STAGING_DIR) PREFIX=/usr LDCONFIG=true
endef

define WIRINGPI_ODROID_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)/wiringPi $(WIRINGPI_ODROID_LIB_INSTALL_TARGETS) DESTDIR=$(TARGET_DIR) PREFIX=/usr LDCONFIG=true
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)/devLib $(WIRINGPI_ODROID_LIB_INSTALL_TARGETS) DESTDIR=$(TARGET_DIR) PREFIX=/usr LDCONFIG=true
	$(INSTALL) -D -m 0755 $(@D)/gpio/gpio $(TARGET_DIR)/usr/bin/gpio
endef

$(eval $(generic-package))
