# Configuration for probot-stale - https://github.com/probot/stale
---

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 90

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 7

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels: []

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - ":question: undecided"

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: false

# Label to use when marking as stale
staleLabel: ":thumbsdown: wontfix"

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  Thanks for your contribution!
  <br/>
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs within the
  next 7 days. Please check if the issue is still relevant in the most current
  version of RaspberryMatic and tell us. Also check that all relevant details,
  <hr/>
  Vielen Dank für die Unterstützung!
  <br/>
  Dieses Problem wurde automatisch als veraltet markiert, da es in letzter
  Zeit keine Aktivitäten gab. Es wird geschlossen, wenn nicht innerhalb der
  nächsten 7 Tage weitere Aktivitäten stattfinden. Bitte überprüfen Sie, ob
  das Problem auch in der aktuellsten Version von RaspberryMatic noch relevant
  ist, und teilen Sie uns dies mit. Überprüfen Sie auch, ob alle relevanten
  Details, Logs und Reproduktionsschritte enthalten sind oder aktualisiert
  werden müssen.

# Comment to post when removing the stale label.
# unmarkComment: >
#   Your comment here.

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This issue has been automatically closed because of inactivity. Please
  open a new issue if still relevant and make sure to include all relevant
  details, logs and reproduction steps.
  <hr/>
  Dieses Problem wurde aufgrund von Inaktivität automatisch geschlossen.
  Bitte öffnen Sie ein neues Issue, falls dies noch relevant ist und stellen
  Sie sicher das alle relevanten Details, Logs und Reproduktionsschritte
  enthalten sind.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Limit to only `issues` or `pulls`
only: issues

# Optionally, specify configuration settings that are specific to just 'issues' or 'pulls':
# pulls:
#   daysUntilStale: 30
#   markComment: >
#     This pull request has been automatically marked as stale because it has not had
#     recent activity. It will be closed if no further activity occurs. Thank you
#     for your contributions.

# issues:
#   exemptLabels:
#     - confirmed
