#!/bin/sh
mountpoint -q ${UM_MOUNTPOINT}
if [ $? -eq 0 ]; then
  if [ -d "${UM_MOUNTPOINT}/measurement" ]; then
    echo "measurement directory already exists"
    touch "/var/status/USBinitialised"
    # CCU2 compatibility
    touch "/var/status/SDinitialised"
  else 
    echo "measurement directory not exists"
    mkdir ${UM_MOUNTPOINT}/measurement
    if [ $? -ne 0 ]; then
      echo "error creating measurement directory"
    else 
      echo "measurement directory created successfully"
      touch "/var/status/USBinitialised"
      # CCU2 compatibility
      touch "/var/status/SDinitialised"
    fi
  fi
fi
