#!/bin/sh
#
# Starts multimacd.
#

LOGLEVEL_RFD=5
CFG_TEMPLATE_DIR=/etc/config_templates
PIDFILE=/var/run/multimacd.pid

[[ -r /var/hm_mode ]] && . /var/hm_mode
[[ "${HM_MODE}" == "HM-LGW" ]] && exit 0

init() {

  # make sure there is no /dev/ttyS0
  if [[ -e /dev/ttyS0 ]]; then
    rm -f /dev/ttyS0
  fi

  if [[ ! -e /var/etc/multimacd.conf ]]; then
    cp -a ${CFG_TEMPLATE_DIR}/multimacd.conf /var/etc/
  fi

  if [[ ! -e /etc/config/syslog ]]; then
    cp -a ${CFG_TEMPLATE_DIR}/syslog /etc/config
  fi

  if [[ -e /etc/config/syslog ]]; then
    . /etc/config/syslog
  fi

}

waitStartupComplete() {
  STEPS=5
  for i in $(seq 1 ${STEPS}); do
    sleep 2
    echo -n "."
    MMDSTATUSPID=$(cat /var/status/multimacd.status 2>&1)
    MMDPID=$(pidof multimacd)
    if [[ "${MMDSTATUSPID}" == "${MMDPID}" ]]; then
      echo "OK"
      break
    fi
    if [[ ${i} -eq ${STEPS} ]]; then
      echo "ERROR"
    fi
  done
}

start() {
  echo -n "Starting multimacd: "
  if [[ -n "${HM_HMIP_DEV}" ]]; then
    init
    start-stop-daemon -S -N -10 -q -b -m -p ${PIDFILE} --exec /bin/multimacd -- -f /var/etc/multimacd.conf -l ${LOGLEVEL_RFD}
    waitStartupComplete
  else
    echo "not required"
  fi
}

stop() {
  echo -n "Stopping multimacd: "
  if [[ -n "${HM_HMIP_DEV}" ]]; then
    start-stop-daemon -K -q -p ${PIDFILE}
    rm -f ${PIDFILE}
  fi
  echo "OK"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
