#!/bin/sh
#
# Starts multimacd.
#

LOGLEVEL_RFD=5
CFG_TEMPLATE_DIR=/etc/config_templates
PIDFILE=/var/run/multimacd.pid

[[ -r /var/hm_mode ]] && . /var/hm_mode

# skip this startup if not in normal mode
[[ "${HM_MODE}" != "NORMAL" ]] && exit 0

init() {
  # make sure /var/etc/multimacd.conf contains the correct
  # coprocessor device path
  sed "s|^Coprocessor Device Path = /dev/.*$|Coprocessor Device Path = ${HM_HOST_GPIO_UART}|" ${CFG_TEMPLATE_DIR}/multimacd.conf >/var/etc/multimacd.conf

  # make sure /dev/eq3loop exists
  if [[ ! -c /dev/eq3loop ]]; then
    # load eq3_char_loop kernel module
    modprobe eq3_char_loop
  fi
}

waitStartupComplete() {
  STEPS=5
  for i in $(seq 1 ${STEPS}); do
    sleep 2
    echo -n "."
    MMDSTATUSPID=$(cat /var/status/multimacd.status 2>&1)
    MMDPID=$(pidof multimacd)
    if [[ "${MMDSTATUSPID}" == "${MMDPID}" ]]; then
      echo "OK"
      break
    fi
    if [[ ${i} -eq ${STEPS} ]]; then
      echo "ERROR"
    fi
  done
}

start() {
  echo -n "Starting multimacd: "
  if [[ -n "${HM_HMIP_DEV}" ]] &&
     [[ -n "${HM_HMRF_DEV}" ]]; then
    init
    if [[ -c /dev/eq3loop ]]; then
      # get the current syslog settings
      [[ -r /etc/config/syslog ]] && . /etc/config/syslog

      start-stop-daemon -S -N -10 -q -b -m -p ${PIDFILE} --exec /bin/multimacd -- -f /var/etc/multimacd.conf -l ${LOGLEVEL_RFD}
      waitStartupComplete
    else
      echo "/dev/eq3loop missing"
    fi
  else
    echo "not required"
  fi
}

stop() {
  echo -n "Stopping multimacd: "
  if [[ -n "${HM_HMIP_DEV}" ]]; then
    start-stop-daemon -K -q -p ${PIDFILE}
    rm -f ${PIDFILE}
  fi
  echo "OK"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
