#!/bin/sh
export NODE_PATH=/usr/lib/node_modules
HOMEPATH=/usr/local/addons/mediola/neo_server/
DAEMON=node
DAEMON_ARGS=${HOMEPATH}/automation.js
PIDFILE=/var/run/neo_server.pid

ADDONNAME=neo_server
CONFIGDIR=/usr/local/etc/config
ADDONDIR=/usr/local/addons/mediola

# change to addon directory
cd ${HOMEPATH}

do_start()
{
	start-stop-daemon --start --quiet --make-pidfile --background --nicelevel -10 --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
}

do_stop()
{
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
	if [ -e $PIDFILE ];then
		rm $PIDFILE
	fi		
}

case "$1" in
  ""|start)
	if [ -e /usr/local/addons/mediola/Disabled ];then
		echo "Neo Disabled"
	else
   		do_start
   		echo "OK"
	fi
    ;;

  info)
    VER=$(cat ${ADDONDIR}/VERSION)
    echo "Version: ${VER}"
    echo "Info: <b>mediola NEO SERVER CCU Addon</b><br>"
    echo "Info: Copyright (c) 2014-2018 mediola connected living AG<br>"
    echo "Info: <a href='http://www.mediola.com'>mediola connected living AG</a>"
    echo "Name: NEO SERVER"
    echo "Operations: uninstall restart"
    echo "Config-Url: /addons/mediola/index.html"
    echo "Update: /addons/mediola/update-check.cgi"
    ;;

  stop)
 	echo -n "Stopping neo_server: "
	do_stop
	echo "OK"
    ;;
    
  restart)
		do_stop
		do_start
    ;;
    
  uninstall)
	do_stop
	touch /etc/config/neoDisabled
	${ADDONDIR}/update_addon mediola
    rm -rf ${ADDONDIR}
    rm -rf ${CONFIGDIR}/addons/www/mediola
    rm /etc/config/rc.d/97NeoServer 
    echo "OK"
    ;;

  *)
    	echo "usage:"
    	echo "  ${ADDONNAME} [info|start|stop|restart|uninstall]"
	exit 1
    ;;
esac

exit 0
