#!/bin/sh
#
# Starts ssdpd
#

start() {
  echo -n "Starting ssdpd: "

  # adjust the oom score (which is inherited by start-stop-daemon)
  # to ensure that others are killed first in case of low memory situations
  echo -900 >/proc/$$/oom_score_adj

  start-stop-daemon -S -q -b -m -p /var/run/ssdpd.pid --exec /bin/ssdpd
  [[ $? -eq 0 ]] && echo "OK" || echo "ERROR"
}
stop() {
  echo -n "Stopping ssdpd: "
  start-stop-daemon -K -q -p /var/run/ssdpd.pid
  [[ $? -eq 0 ]] && ( rm -f /var/run/ssdpd.pid && echo "OK" ) || echo "ERROR"
}
restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
