#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     # put the psplash progess bar to the
     # corresponding level
     name=$(basename $i)
     /usr/bin/psplash-write "MSG Starting ${name:3}..."
     /usr/bin/psplash-write "PROGRESS $((${name:1:2}))"

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

/usr/bin/psplash-write "MSG http://$(hostname)/"
/usr/bin/psplash-write "PROGRESS 100"
