#!/bin/sh
# shellcheck shell=dash disable=SC2169
#
# Startup script to init the random number generator interface (urandom)
#

save_urandom() {
  if [[ ! -c /dev/urandom ]]; then
    return
  fi

  if [[ -d /etc/config ]]; then
    dd if=/dev/urandom of=/etc/config/random-seed count=1 bs=512 &>/dev/null
  fi
}

init_urandom() {
  if [[ ! -c /dev/urandom ]]; then
    return
  fi

  if [[ -s /etc/config/random-seed ]]; then
    cat /etc/config/random-seed >/dev/urandom
    [[ -x /bin/rndaddtoentcnt ]] && /bin/rndaddtoentcnt 4096
  else
    # initialize urandom with /proc/timer_list
    head -3 /proc/timer_list | tail -1 | cut -d' ' -f3 >/dev/urandom
    [[ -x /bin/rndaddtoentcnt ]] && /bin/rndaddtoentcnt 128
  fi

  # make sure we save the entropy pool right away for the next boot
  save_urandom
}

start() {
  echo -n "Initializing urandom: "

  init_urandom

  echo "OK"
}

stop() {
  echo -n "Saving urandom: "

  save_urandom

  echo "OK"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
