#!/bin/sh
#
# Startup script to check for a factory reset
#

# function to check if a factory reset (clearing whole /usr/local) should be performed
# in addition we also resize /usr/local in case it hasn't been resized to SD card
# boundaries
check_factory_reset() {

  # only continue if .doFactoryReset file exists
  if [[ ! -r /usr/local/.doFactoryReset ]]; then
    return 1
  fi

  # source all data from /var/hm_mode
  [[ -r /var/hm_mode ]] && . /var/hm_mode
  
  if [[ "${HM_HOST}" != "oci" ]]; then

    # extract partition number and device name
    DEVNODE=$(mountpoint -d /usr/local)
    DEVNAME=$(mountpoint -n /usr/local | cut -d' ' -f1)
    PARTNUM=$(echo -n ${DEVNAME} | tail -c 1)
    DEV="/dev/$(readlink /sys/dev/block/${DEVNODE} | awk -F/ '{print $(NF-1)}')"

    # find out maximum SD card size (in cylinders)
    START_CHS=$(parted -s ${DEV} unit chs print | grep "^ ${PARTNUM} " | awk '{print $2}')
    END_CHS=$(parted -s ${DEV} unit chs print | grep "^ ${PARTNUM} " | awk '{print $3}')
    MAX_CHS=$(parted -s ${DEV} unit chs print | grep "Disk ${DEV}" | cut -d' ' -f3)

    # umount /usr/local to regenerate it
    umount -f /usr/local

    # only resize the partition if END_CHS != MAX_CHS
    if [[ -n "${START_CHS}" && -n "${END_CHS}" && -n "${MAX_CHS}" && "${END_CHS}" != "${MAX_CHS}" ]]; then
      # use resizepart to resize the /usr/local partition to the maximum size of
      # the disk
      parted -s ${DEV} resizepart ${PARTNUM} 100%
    fi

    # force PARTUUID to 0xDEEDBEEF (because parted changes partuuid) even
    # if no repartitioning was performed.
    echo -en '\xEF\xBE\xED\xDE' | dd of=${DEV} conv=notrunc bs=1 seek=$((0x1B8)) 2>/dev/null

    # we create a clean ext4 partition now
    mkfs.ext4 -F -L userfs "${DEVNAME}"
    tune2fs -c 0 -i 0 "${DEVNAME}"
    e2fsck -pDf "${DEVNAME}"

    # mount /usr/local again
    mount /usr/local
  else
    rm -rf /usr/local
  fi

  # make sure a potential rf copro is factory
  # reset as well
  touch /usr/local/.doCoproFactoryReset

  return 0
}

start() {
  echo -n "Checking for Factory Reset: "

  check_factory_reset

  if [[ $? -eq 0 ]]; then
    echo "cleared, OK"
  else
    echo "not required"
  fi
}

restart() {
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    # nothing
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
