#!/bin/sh
#
# Startup script to ensure we have a valid filesystem
#

init_system() {

  CFG_TEMPLATE_DIR=/etc/config_templates

  # ensure some pathes are there and have
  # correct permissions
  chmod 775 /var
  mkdir -p /var/log
  chmod 775 /var/log
  mkdir -p /var/tmp
  chmod 775 /var/tmp
  mkdir -p /var/rega
  chmod 775 /var/rega
  mkdir -p /var/run
  chmod 775 /var/run
  mkdir -p /var/spool
  chmod 775 /var/spool
  mkdir -p /var/lock
  chmod 775 /var/lock
  mkdir -p /var/cache
  chmod 775 /var/cache
  mkdir -p /var/lib
  chmod 775 /var/lib
  mkdir -p /var/lib/misc
  chmod 775 /var/lib/misc
  mkdir -p /var/lib/dbus
  chmod 775 /var/lib/dbus
  mkdir -p /var/empty
  chmod 600 /var/empty
  mkdir -p /var/etc
  chmod 775 /var/etc
  mkdir -p /var/status
  chmod 775 /var/status

  # create /media/usbX directories for automounting USB devices
  for i in $(seq 1 8); do
    mkdir -p /media/usb${i}
  done

  # SSH dir setup (/root/.ssh is linked to /usr/local/etc/ssh)
  mkdir -p /usr/local/etc/ssh

  # create a /usr/local/tmp directory for creating things like backup files, etc.
  # (we need it on-disk or /tmp will be not enough in case of a filled up /usr/local)
  mkdir -p /usr/local/tmp
  rm -rf /usr/local/tmp/*

  # make sure /usr/local/etc/config exists and has
  # correct permissions
  mkdir -p /usr/local/etc/config
  chmod 775 /usr/local/etc/config

  # make sure the timezone setup is fine
  if [[ ! -e /etc/config/TZ ]]; then
    cp -a ${CFG_TEMPLATE_DIR}/TZ /etc/config/
  fi

  # update /etc/config/localtime and /etc/config/timezone
  /bin/updateTZ.sh

  # if /etc/config/timezone is set to Europe/Berlin we
  # assume a german keyboard layout
  if [[ $(cat /etc/config/timezone) == "Europe/Berlin" ]]; then
    /sbin/loadkmap </etc/de.kmap
  fi

  # if no network config is present we make sure to put a template file
  # there
  if [[ ! -e /etc/config/netconfig ]] ; then
    cp -a ${CFG_TEMPLATE_DIR}/netconfig /etc/config/
  fi

  # if no shadow file with password information is in place we have to
  # put the template file there.
  if [[ ! -s /etc/config/shadow ]] ; then
    cp -a ${CFG_TEMPLATE_DIR}/shadow /etc/config/
  fi

  # load watchdog kernel module
  if [[ "${HM_HOST}" != "tinkerboard" ]]; then
    modprobe bcm2835_wdt nowayout=1 heartbeat=15
  fi

  # load tunneling interface support
  modprobe tun
}

start() {
  echo -n "Initializing System: "

  # source all data from /var/hm_mode
  [[ -r /var/hm_mode ]] && . /var/hm_mode

  # call rc.init before initializing the system
  if [[ ! -e /etc/config/safemode ]]; then
    if [[ -x /usr/local/etc/rc.init ]]; then
      /usr/local/etc/rc.init
    fi
  fi

  # make sure the system is properly initialized
  init_system

  # start hss_led if it exists
  if [[ -x /bin/hss_led ]]; then
    start-stop-daemon -S -q -b -m -p /var/run/hss_led.pid --exec /bin/hss_led -- -l 6
  fi

  # call rc.postinit after init of system is finished
  if [[ ! -e /etc/config/safemode ]]; then
    if [[ -x /usr/local/etc/rc.postinit ]]; then
      /usr/local/etc/rc.postinit
    fi
  fi

  # save all HM_ env variables
  set | grep '^HM_' >/var/hm_mode

  echo "OK"
}

stop() {
  echo -n "Cleaning up System: "

  if [[ -f /var/run/hss_led.pid ]]; then
    start-stop-daemon -K -q -p /var/run/hss_led.pid
  fi

  echo "OK"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
