#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	printf "Starting network: "
	# source all data from /var/hm_mode
    [[ -r /var/hm_mode ]] && . /var/hm_mode
  
    if [[ "${HM_HOST}" != "oci" ]]; then
	  /sbin/ifup -a 2>/dev/null
	  echo "OK"
	else
	  echo "SKIP"
	fi
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
