#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

# source all data from /var/hm_mode
[[ -r /var/hm_mode ]] && . /var/hm_mode

# oci platform does not require own rngd
[[ "${HM_HOST}" == "oci" ]] && exit 0

case "$1" in
  start)
	printf "Starting network: "
	/sbin/ifup -a 2>/dev/null
	echo "OK"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
