#!/bin/sh

# source all data from /var/hm_mode
[[ -r /var/hm_mode ]] && . /var/hm_mode

# oci platform does not require own urandom
[[ "${HM_HOST}" == "oci" ]] && exit 0

NAME=chrony
DAEMON=/usr/sbin/chronyd
CLIENT=/usr/bin/chronyc
CFG_TEMPLATE_DIR=/etc/config_templates

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

init() {
  if [[ ! -e /etc/config/ntpclient ]]; then
    cp $CFG_TEMPLATE_DIR/ntpclient /etc/config
  fi

  if [[ -r /etc/config/ntpclient ]]; then
    . /etc/config/ntpclient
  fi

  # make sure "ntp.homematic.com" is not used anymore
  if [[ "${NTPSERVERS}" == "ntp.homematic.com" ]]; then
    cp ${CFG_TEMPLATE_DIR}/ntpclient /etc/config/
    . /etc/config/ntpclient
  fi

  # add the DHCP queried NTP servers at the beginning of NTPSERVERS
  if [[ -s /var/etc/ntp-dhcp.conf ]] &&
     [[ ! -f /etc/config/noDHCPNTP ]]; then
    . /var/etc/ntp-dhcp.conf
    NTPSERVERS="${NTPSERVERS_DHCP} ${NTPSERVERS}"
  fi

  # if still empty we add the default gateway as a potential NTP
  # source
  if [[ -z "${NTPSERVERS}" ]]; then
    # try the gateway
    NTPSERVERS=$(/sbin/ip route | grep default | head -1 | cut -d' ' -f3)
  fi

  # make sure /var/lib/chrony exists so that the drift file
  # can be saved later on
  mkdir -p /var/lib/${NAME}
}

case "$1" in
  start)
    init
    printf "Starting $NAME: "

    # call ntpdate to perform a single sync to the servers
    /usr/bin/ntpdate -b -s -u ${NTPSERVERS} 2>/dev/null
    if [[ $? -ne 0 ]]; then
      # use default NTP servers because the user selected
      # ones didn't work out
      echo -n "using default NTPs, "
      . ${CFG_TEMPLATE_DIR}/ntpclient

      /usr/bin/ntpdate -b -s -u ${NTPSERVERS} 2>/dev/null
      if [[ $? -ne 0 ]]; then
        echo -n "could not sync to '${NTPSERVERS}', FAIL"
        exit 0
      fi
    fi

    # start daemon
    start-stop-daemon -S -q -x ${DAEMON}
    if [[ $? -eq 0 ]]; then
      # use client to add ntp servers
      for server in ${NTPSERVERS}; do
        ${CLIENT} add server ${server} >/dev/null 2>&1
        [ $? = 0 ] && touch /var/status/hasNTP
      done
    fi

    if [[ -e /var/status/hasNTP ]]; then
      ${CLIENT} burst 2/10 >/dev/null 2>&1
      echo "OK"
    else
      echo "FAIL"

      # make sure chronyd is stopped
      start-stop-daemon -K -q -p /var/run/chrony/chronyd.pid
    fi
    ;;
  stop)
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -p /var/run/chrony/chronyd.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    rm -f /var/status/hasNTP
    ;;
  restart|reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
