#!/bin/sh
#
# Starts eq3configd.
#
init () {

  # we only extract BidCos-Address and SerialNumber to /etc/config/ids
  # in case there isn't a 'ids' file only
  if [[ ! -f /etc/config/ids ]] ; then
    grep -E "BidCoS-Address|SerialNumber" /var/ids >/etc/config/ids
  fi
	
	if [[ ! -e /etc/config/crypttool.cfg ]] ; then
			touch /etc/config/crypttool.cfg
	fi
}

start() {
	echo -n "Starting eq3configd: "
	init
	start-stop-daemon -S -q -p /var/run/eq3configd.pid --exec /bin/eq3configd &
	echo "OK"
	echo -n "Starting ssdpd: "
	start-stop-daemon -S -q -p /var/run/ssdpd.pid --exec /bin/ssdpd &
	echo "OK"
}
stop() {
	echo -n "Stopping ssdpd: "
	start-stop-daemon -K -q -p /var/run/ssdpd.pid
	echo "OK"
	echo -n "Stopping eq3configd: "
	start-stop-daemon -K -q -p /var/run/eq3configd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

