#!/bin/sh
#
# Starts setclock.
#

CFG_TEMPLATE_DIR=/etc/config_templates

init() {
	export TZ=`cat /etc/config/TZ`

	if [ ! -e /etc/config/ntpclient ] ; then
		cp $CFG_TEMPLATE_DIR/ntpclient /etc/config
	fi

	if [ -e /etc/config/ntpclient ] ; then
		. /etc/config/ntpclient
	fi
}

start() {
	echo -n "Starting setclock: "
	init

	FOUND=0
	GATEWAY=`route -n | awk '{if ($1 == "0.0.0.0") print $2}'`
	if [ ! -z "$NTPSERVERS" ] ; then
		for NTPSERVER in $NTPSERVERS ; do
			NTP_DAY=`ntpclient -h $NTPSERVER -c 1 -i 1 2>/dev/null | sed "s/ .*$//" `
			if [ -z $NTP_DAY ] ; then
				echo "$NTPSERVER not found"
				continue
			fi
			ntpclient -h $NTPSERVER -s -i 1
			FOUND=1
			hwclock -wu
			break
		done
	fi
	if [ $FOUND == 0 ] ; then
		echo "try gateway $GATEWAY"
		NTP_DAY=`ntpclient -h ntp.homematic.com -c 1 -i 1 2>/dev/null | sed "s/ .*$//" `
		if [ "$NTP_DAY" != "" ] ; then
			echo "$GATEWAY found"
			ntpclient -h $GATEWAY -s -i 1
			hwclock -wu
		else
			echo "GATEWAY not found"
		fi
	fi

	daemonize /bin/setclock
	
	echo "OK"
}
stop() {
	echo -n "Stopping setclock: "
	killall setclock
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

