#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	# Only run this if ssh is explicitly enabled
	[ -f /etc/config/sshEnabled ] || exit 0

	# Create any missing keys
	if [[ ! -f /usr/local/etc/ssh_host_dsa_key ]] ||
	   [[ ! -f /usr/local/etc/ssh_host_ecdsa_key ]] ||
	   [[ ! -f /usr/local/etc/ssh_host_ed25519_key ]] ||
	   [[ ! -f /usr/local/etc/ssh_host_rsa_key ]]; then
		mkdir -p /tmp/etc/ssh
		cp -a /usr/local/etc/ssh_host_*_key* /tmp/etc/ssh/
		/usr/bin/ssh-keygen -A -f /tmp
		cp -a /tmp/etc/ssh/* /usr/local/etc/
		rm -rf /tmp/etc/ssh
	fi

	# fix permissions
	chmod 600 /usr/local/etc/ssh_host_*_key

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

