#!/bin/sh
#
# Starts eq3configcmd update-lgw-firmware for RF- and Wired-Gateways
#

start() {
	waitForIP
	echo -n "."
	updateCopro
	echo -n "."
	updateRFFirmware
	echo -n "."
	updateWiredFirmware
}

waitForIP() {
	for i in $(seq 1 10)
	do
		if [ -f /var/status/hasIP ] ; then
			break;
		fi 
		sleep 1
	done	
}

updateCopro() {
	echo "Updating RF Lan Gateway Coprocessor Firmware" | logger -p user.info 
	/bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 1
}

updateRFFirmware() {
	echo "Updating RF Lan Gateway Firmware" | logger -p user.info 
	/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/rfd.conf -l 1 
}

updateWiredFirmware() {
	echo "Updating Wired Lan Gateway Firmware" | logger -p user.info 
	/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/hs485d.conf -l 1
}

restart() {
	stop
	start
}

case "$1" in
  start)
	echo -n "Starting LGWFirmwareUpdate: "
	start
	echo "OK"
	;;
  stop)
	echo -n "Stopping LGWFirmwareUpdate: "
	echo "OK"
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
