#!/bin/sh
#
# Starts eq3configcmd setlgwkey.
#

CFG_DIR=/etc/config

source /var/hm_mode 2>/dev/null

# skip this startup in LAN Gateway mode
[[ "${HM_MODE}" == "HM-LGW" ]] && exit 0

start() {
	echo -n "Setting LAN Gateway keys: "
	/bin/setlgwkey.sh
	echo "OK"
}

stop() {
	echo ""
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
