#!/bin/sh
#
# start script to setup the board leds correctly once the
# system finished booting
#

start() {
  echo -n "Setup onboard LEDs: "

  # source all data from /var/hm_mode
  [[ -r /var/hm_mode ]] && . /var/hm_mode

  # signal that the system is successfully started
  if [[ "${HM_HMRF_DEV}" == "RPI-RF-MOD" ]] ||
     [[ "${HM_HMIP_DEV}" == "RPI-RF-MOD" ]]; then

    if [[ ! -f /var/status/hasLink ]]; then
      # blink yellow
      GREEN=timer
      RED=timer
      BLUE=none
    elif [[ ! -f /var/status/hasInternet ]]; then
      # constant yellow
      GREEN=none
      RED=none
      BLUE=timer
    elif [[ ! -f /var/status/HMServerStarted ]]; then
      # blink red
      GREEN=none
      RED=timer
      BLUE=none
    else
      # constant blue
      GREEN=none
      RED=none
      BLUE=default-on
    fi

    # setup the LEDs of the RPI-RF-MOD
    echo ${GREEN} >/sys/class/leds/rpi_rf_mod\:green/trigger
    echo ${RED}   >/sys/class/leds/rpi_rf_mod\:red/trigger
    echo ${BLUE}  >/sys/class/leds/rpi_rf_mod\:blue/trigger
  fi

  # start is finished lets set the LEDs
  if [[ -f "${HM_LED_GREEN}/trigger" ]]; then
    echo "heartbeat" >${HM_LED_GREEN}/trigger
  fi
  if [[ -f "${HM_LED_RED}/trigger" ]]; then
    echo "mmc0" >${HM_LED_RED}/trigger
  fi
  if [[ -f "${HM_LED_YELLOW}/trigger" ]]; then
    echo "none" >${HM_LED_YELLOW}/trigger
  fi

  echo "booted, OK"
}

restart() {
  stop
  start
}

stop() {
  echo -n "Setup onboard LEDs: "

  # source all data from /var/hm_mode
  [[ -r /var/hm_mode ]] && . /var/hm_mode

  # stop starts, lets set the LEDs
  if [[ -f "${HM_LED_GREEN}/trigger" ]]; then
    echo "mmc0" >${HM_LED_GREEN}/trigger
  fi
  if [[ -f "${HM_LED_RED}/trigger" ]]; then
    echo "timer" >${HM_LED_RED}/trigger
  fi
  if [[ -f "${HM_LED_YELLOW}/trigger" ]]; then
    echo "none" >${HM_LED_YELLOW}/trigger
  fi

  echo "shutdown, OK"
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
