#!/bin/sh
#
# set System Start Led Signal
#

CFG_TEMPLATE_DIR=/etc/config_templates
SERIAL=$(cat /sys/module/plat_eq3ccu2/parameters/board_serial)

init() {
	# power led on
	echo 255 > /sys/class/leds/power/brightness
	echo default-on > /sys/class/leds/power/trigger
	# internet led off
	echo none > /sys/class/leds/internet/trigger
	# info led fast
	echo timer > /sys/class/leds/info/trigger
	echo 255 > /sys/class/leds/info/brightness
	echo 100 > /sys/class/leds/info/delay_off
	echo 100 > /sys/class/leds/info/delay_on

        chmod 775 /var
        mkdir /var/log
        chmod 775 /var/log
        mkdir /var/tmp
        chmod 775 /var/tmp
        mkdir /var/rega
        chmod 775 /var/rega
        mkdir /var/run
        chmod 775 /var/run
        mkdir /var/spool
        chmod 775 /var/spool
        mkdir /var/lock
        chmod 775 /var/lock
        mkdir /var/cache
        chmod 775 /var/cache
        mkdir /var/lib
        chmod 775 /var/lib
        mkdir /var/lib/misc
        chmod 775 /var/lib/misc
        mkdir /var/empty
        chmod 600 /var/empty
        mkdir /var/etc
        chmod 775 /var/etc
	#
	# crontab dirs
        mkdir -p /var/spool/cron
        chmod 775 /var/spool
        chmod 775 /var/spool/cron
        if [ ! -d /usr/local/crontabs ] ; then
        	mkdir -p /usr/local/crontabs
        	chmod 775 /usr/local/crontabs
        fi
	ln -s /usr/local/crontabs /var/spool/cron/crontabs 
        if [ ! -e /usr/local/crontabs/root ] ; then
                cp $CFG_TEMPLATE_DIR/crontab.root /usr/local/crontabs/root
		else
				#if /usr/local/contabs/root exists, ensure that logrotate entry exists
				cat /usr/local/crontabs/root | grep -q logrotate
				if [ $? -ne 0 ]
				then
					echo '0 4 * * * /usr/sbin/logrotate -f /etc/logrotate.conf || logger -p error -t "logrotate" "logrotate aborted with error $?"' >> /usr/local/crontabs/root
				fi
        fi
        # Bug fix
        grep "setInterfaceClock" /usr/local/crontabs/root
        if [ $? == 0 ] ; then
                echo "update crontab file"
                sed 's/setInterfaceClock/SetInterfaceClock/g' /usr/local/crontabs/root > /usr/local/crontabs/root.tmp
                mv /usr/local/crontabs/root.tmp /usr/local/crontabs/root
        fi
        grep "dutyccu" /usr/local/crontabs/root
        if [ $? == 1 ] ; then
                echo "added dutyccu"
                echo '*/3 * * * * /bin/dutyccu' >> /usr/local/crontabs/root
        fi
        
	if [ ! -e /usr/local/etc/config/shadow ] ; then
		cp $CFG_TEMPLATE_DIR/shadow /usr/local/etc/config/shadow
	fi

	modprobe spidev
        modprobe ic200_spi
        modprobe spi_eq3_gpio
        modprobe spi_bitbang
        mknod spidev0.0 c 153 0
        modprobe gpio-keys
        modprobe fsl_usb2_udc.ko
	if grep -q "eQ3Mode=production" /proc/cmdline ; then
          modprobe g_multi luns=1 cdrom=1 ro=1 removable=0,0 file=/usr/share/eq3/install.iso host_addr=00:1a:22:00:05:86 dev_addr=00:1a:22:00:05:87 iManufacturer="eQ-3" iProduct="CCU2" idVendor="0x1b1f" idProduct="0xc016" iSerialNumber="$SERIAL"
	fi
	
	# Tunneling
        modprobe tun
       
	# USB
        modprobe ehci-hcd

	# HM/HmIP Dual Protocol
	modprobe mxs_raw_auart
	modprobe eq3_char_loop
	 
	if [ ! -d /usr/local/etc/config ] ; then
                mkdir -p /usr/local/etc/config
        	chmod 775 /usr/local/etc/config
        fi


        if [ ! -e /etc/config/TZ ] ; then
                cp $CFG_TEMPLATE_DIR/TZ /etc/config
        fi
        if [ ! -e /etc/config/netconfig ] ; then
                cp $CFG_TEMPLATE_DIR/netconfig /etc/config
        fi
        if [ ! -e /etc/config/shadow ] ; then
                cp $CFG_TEMPLATE_DIR/shadow /etc/config
        fi

	export TZ=`cat /etc/config/TZ`
 
}

start() {
	echo -n "LED Code: System start: "
	init
	echo "OK"
    # Firewall konfigurieren
    echo -n "Init Firewall: "
    setfirewall.tcl
	echo -n "Starting crond: "
	start-stop-daemon -S -q -p /var/run/crond.pid --exec /usr/sbin/crond	
	echo "OK"
}

stop () {
	start-stop-daemon -K -q -p /var/run/crond.pid
	/bin/update_firmware_pre
}

restart() {
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

