#!/bin/sh
#
# raspi-fanshim daemon starting and stopping
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

DAEMON=/opt/raspi-fanshim/FanshimService
PIDFILE=/var/run/FanshimService.pid

test -e /etc/config/enableFanshim || exit 0
test -x $DAEMON || exit 0

case $1 in
  start)
    echo -n "Starting FanShim daemon: "

    # now start the daemon
    start-stop-daemon --start --background --pidfile ${PIDFILE} --make-pidfile --quiet --exec ${DAEMON}
    [[ $? = 0 ]] && echo "OK" || echo "FAIL"
  ;;

  stop)
    echo -n "Stopping FanShim daemon: "
    if [[ -f ${PIDFILE} ]]; then
      start-stop-daemon --stop --quiet --pidfile ${PIDFILE}
      [[ $? = 0 ]] && echo "OK" || echo "FAIL"
      rm -f ${PIDFILE}
    else
      echo "OK"
    fi
  ;;

  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
  ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
