---
name: OpenCCU (snapshot)
version: 3.89.8.20260901-56ed0b2
stage: experimental
slug: openccu-dev
image: ghcr.io/openccu/openccu
arch:
  - aarch64
  - amd64
description: HomeMatic/homematicIP CCU central based on OpenCCU (Snapshot)
url: https://github.com/OpenCCU/OpenCCU/
ingress: true
ingress_stream: true
panel_title: OpenCCU (snapshot)
panel_icon: mdi:router-wireless
startup: services
map:
  - type: data
    read_only: false
    path: /usr/local
  - type: backup
    read_only: false
init: false
backup_pre: /bin/sh -c "/bin/echo 'load tclrega.so; rega system.Save()' | /bin/tclsh && /bin/sync"
backup_exclude:
  - "*/tmp/.watchdog"
timeout: 240
devices:
  - /dev/raw-uart
  - /dev/raw-uart1
  - /dev/mmd_hmip
  - /dev/mmd_bidcos
  - /dev/eq3loop
  - /dev/i2c-0
  - /dev/i2c-1
udev: true
usb: true
uart: true
kernel_modules: true
realtime: true
ports:
  22/tcp: null
  80/tcp: null
  443/tcp: null
  2001/tcp: null
  2000/tcp: null
  2010/tcp: null
  9292/tcp: null
  1999/tcp: null
  8181/tcp: null
  42001/tcp: null
  42000/tcp: null
  42010/tcp: null
  49292/tcp: null
  41999/tcp: null
  48181/tcp: null
  9293/tcp: null
  9294/tcp: null
  43438/udp: null
  1900/udp: null
  43439/udp: null
  161/udp: null
  8701/tcp: null
  1901/udp: null
  1902/udp: null
  5987/udp: null
  8088/tcp: null
  9099/tcp: null
  10000/udp: null
  48899/udp: null
  49880/udp: null
  8082/tcp: null
  2098/tcp: null
  2099/tcp: null
  8083/tcp: null
  9092/tcp: null
  5435/tcp: null
  2121/tcp: null
  2122/tcp: null
  1883/tcp: null
  8883/tcp: null
  2110/tcp: null
  8911/tcp: null
  5855/udp: null
  2812/tcp: null
environment:
  HM_RUNNING_IN_HA: "1"
  HM_HAPROXY_SRC: 172.30.32.2/32
privileged:
  - IPC_LOCK
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
  - NET_ADMIN
