#!/bin/sh
#
# Starts eq3configd.
#
init () {
	radio_mac=$(cat /var/rf_address)
	board_serial=$(cat /var/board_serial)
	echo "BidCoS-Address=$radio_mac" > /var/ids
	echo "SerialNumber=$board_serial" >> /var/ids
	if [ ! -e /etc/config/ids ] ; then
    		cp /var/ids /etc/config
	fi
	
	if [ ! -e /etc/config/crypttool.cfg ] ; then
			touch /etc/config/crypttool.cfg
	fi
}

start() {
	echo -n "Starting eq3configd: "
	init
#	start-stop-daemon -S -q -p /var/run/eq3configd.pid --exec /bin/eq3configd &
#	start-stop-daemon -S -q -p /var/run/ssdpd.pid --exec /bin/ssdpd &
	echo "OK"
}
stop() {
	echo -n "Stopping eq3configd: "
	start-stop-daemon -K -q -p /var/run/eq3configd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

