#!/bin/sh

STARTPWD=$(pwd)
ROOT_FS=rootfs.tar

RC=1

if [ -f ${STARTPWD}/${ROOT_FS} ]; then
  echo -ne "Overriding container files in / ... "
  rm -rf --one-file-system /
  tar -xf ${ROOT_FS}
  if [ $? -ne 0 ]; then
    echo "ERROR: (tar)"
    RC=1
  else
    echo "OK<br>"
    RC=0
  fi
else
  echo "INFO: no rootfs update found, OK<br>"
fi

exit ${RC}
