name: Bug Report
description: Report a bug/issue related to RaspberryMatic
labels: ":bug: bug-report"
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Rules
  - type: markdown
    attributes:
      value: |
        1. Do **NOT** use this ticket/issue system for support requests! It is meant to be used to report bugs only and not to search for help if you have problems using RaspberryMatic.
        2. Do **NOT** submit bug reports about anything but the two most recently released versions!
        3. Before you open a new bug/issue report here, please make sure that it hasn't been reported yet and please make sure to cross-check the discussion fora discussed below and try to discuss your problem there first before you are opening a new bug report here.

        If you have problems while using RaspberryMatic and are seeking for help, please consult our [GitHub Community Forum](https://github.com/jens-maus/RaspberryMatic/discussions) or the public [RaspberryMatic Forum](https://homematic-forum.de/forum/viewforum.php?f=65).
  - type: markdown
    attributes:
      value: |
        ## The problem
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the issue you are experiencing
      description: Provide a clear and concise description of what the bug is.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the behavior you expected
      description: Describe what you expected to happen or it should look/behave.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the issue
      description: |
        Please tell us exactly how to reproduce your issue.
        Provide clear and concise step by step instructions and add code snippets if needed.
      value: |
        1.
        2.
        3.
        ...
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    validations:
      required: true
    attributes:
      label: What is the version this bug report is based on?
      placeholder: 3.XX.YY-YYYYMMDD
      description: >
        The RaspberryMatic version you are using Can be found in the help page of the WebUI and starts with `3.XX.YY-YYYYMMDD`.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Which base platform are you running?
      description: >
        This is the platform you are using to run RaspberryMatic on and corresponds to the image you are usually downloading for updating RaspberryMatic. 
      options:
        - rpi4 (RaspberryPi4)
        - rpi3 (RaspberryPi3)
        - rpi2 (RaspberryPi2)
        - rpi0 (RaspberryPi)
        - tinkerboard (ASUS Tinkerboard)
        - odroid-c2 (ODROID C2)
        - odroid-c4 (ODROID C4)
        - odroid-n2 (ODROID N2/N2+)
        - intelnuc (intel NUC)
        - ova (Open Virtual Infrastructure)
        - oci (Open Container Infrastructure)
        - ha-addon (HomeAssistant Add-on)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Which HomeMatic/homematicIP radio module are you using?
      description: >
        This is the radio module you are potentially using to communicate to HomeMatic/homematicIP devices.
      options:
        - RPI-RF-MOD
        - HM-MOD-RPI-PCB
        - HmIP-RFUSB
        - HM-CFG-LAN
        - HM-CFG-USB-2
        - n/a
  - type: markdown
    attributes:
      value: |
        ## Details
  - type: textarea
    validations:
      required: true
    attributes:
      label: Anything in the logs that might be useful for us?
      description: >
        The RaspberryMatic logs can be found in the `/var/log` directory on the central.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
