#!/bin/sh
# shellcheck shell=dash disable=SC2169,SC1091

[[ -r /var/hm_mode ]] && . /var/hm_mode

echo "Powering off container"
if [[ -n "${HM_RUNNING_IN_HA}" ]]; then
  curl -X POST -H "Authorization: Bearer ${HM_SUPERVISOR_TOKEN}" -H "Content-Type: application/json" http://supervisor/addons/self/stop
else
  kill -USR2 1
fi
