#!/bin/sh

mkdir -p /var/status

rm -f /var/status/hasLink
rm -f /var/status/hasIP
rm -f /var/status/hasInternet
rm -f /var/status/hasNTP

# stop WPA Supplicant if this is a WiFi connection
case ${IFACE} in
  wlan*)
    killall -q wpa_supplicant
  ;;
esac

exit 0
