#!/bin/sh
#
# Prepares start of hs485d. 
#
# Writes /etc/config/InterfacesList.xml
# It must be started before webserver!
# It does NOT start hs485d itself! 
#

LOGLEVEL_HS485D=5

CFG_TEMPLATE_DIR=/etc/config_templates

source /var/hm_mode 2>/dev/null

# skip this startup in LAN Gateway mode
[[ ${HM_MODE} == "HMLGW" ]] && exit 0

init() {
	if [ ! -d /etc/config/hs485d ] ; then
  		mkdir /etc/config/hs485d
	fi
	if [ -e /etc/config/syslog ] ; then
  		. /etc/config/syslog
	fi
	if [ ! -e /etc/config/InterfacesList.xml ] ; then
		cp $CFG_TEMPLATE_DIR/InterfacesList.xml /etc/config
	else
		cmp -s $CFG_TEMPLATE_DIR/InterfacesList.xml /etc/config/InterfacesList.xml || cp $CFG_TEMPLATE_DIR/InterfacesList.xml /etc/config
	fi

  # if there is no HmIP support enabled we have to strip
  # the HmIP-RF part in InterfacesList.xml
  if [[ ${HM_MODE} != "HmIP" ]] || [[ -z $(cat /var/rf_address) ]]; then
    if [[ ${HM_MODE} != "HmIP-RFUSB" ]]; then
      # remove HmIP-RF from InterfacesList.xml because not required (BidCos-RF only mode)
      line_start=$(cat /etc/config/InterfacesList.xml | grep -n '>HmIP-RF<' | cut -d: -f1 | head -1)
      line_end=$(cat /etc/config/InterfacesList.xml | grep -n '>HmIP-RF<' | cut -d: -f1 | tail -1)
    else
      # remove BidCos-RF from InterfacesList.xml because not required (HmIP-RFUSB only mode)
      line_start=$(cat /etc/config/InterfacesList.xml | grep -n '>BidCos-RF<' | cut -d: -f1 | head -1)
      line_end=$(cat /etc/config/InterfacesList.xml | grep -n '>BidCos-RF<' | cut -d: -f1 | tail -1)
    fi
    if [[ -n ${line_start} && -n ${line_end} ]]; then
      line_start=$((${line_start}-1))
      line_end=$((${line_end}+1))
      sed -i "${line_start},${line_end}d" /etc/config/InterfacesList.xml
    fi
  fi
}

start() {
	echo -n "Preparing start of hs485d: "
	init
	/bin/hs485dLoader -l $LOGLEVEL_HS485D -ds -dd /etc/config/hs485d.conf
	echo "OK"
}

stop() {
	echo -n ""
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
