#!/bin/sh
# shellcheck shell=dash disable=SC2169 source=/dev/null
#
# Start all init scripts in /etc/init.d
# executing them in numerical order.

# mount all filesystems
/bin/mount -a

# create /var/run and /var/cache
/bin/mkdir -p /var/run /var/cache

# create ld.so.cache file
/sbin/ldconfig -C /var/cache/ld.so.cache

for i in /etc/init.d/S??* ;do

  # Ignore dangling symlinks (if any).
  [[ ! -f "${i}" ]] && continue

  case "${i}" in
    *.sh)
      # Source shell script for speed.
      (
        trap - INT QUIT TSTP
        set start
        . "${i}"
      )
      ;;
    *)
      # No sh extension, so fork subprocess.
      ${i} start
    ;;
  esac
done

[[ -r /VERSION ]] && . /VERSION

echo "Finished Boot: ${VERSION} (${PRODUCT})"
