#!/bin/sh
# shellcheck shell=dash disable=SC2169 source=/dev/null
#
# Startup script to bind mount /data to /usr/local
# (required for Home Assistant Add-on only)
#

[[ -z "${HM_RUNNING_IN_HA}" ]] && exit 0

start() {
  echo -n "Mounting /data as /usr/local (Home Assistant Add-On): "

  # Home Assistant Add-on expects persistent data to be stored in /data
  if [[ -f "/data/options.json" ]]; then
    mount -o bind /data /usr/local
  fi

  # remount /dev as rw to allow multimacd to create mmd_bidcos/mmd_hmip
  # later on and unmount /dev_host on HA because not required.
  mount -o rw,remount /dev

  echo "OK"
}

stop() {
  echo -n "Unmounting /data from /usr/local (Home Assistant Add-On): "

  umount /usr/local

  echo "OK"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
