#!/bin/sh
# shellcheck shell=dash disable=SC2169
#
# Startup script for ha-proxy which proxies HTTP
# requests from the HomeAssistant UI to the HomeMatic WebUI
#

[[ -z "${RUNNING_IN_HA}" ]] && exit 0

start() {
  printf  "Starting ha-proxy: "

  if start-stop-daemon -S -q -m -b -p /var/run/ha-proxy.pid --exec /bin/ha-proxy.js; then
    echo "OK"
  else
    echo "FAIL"
  fi
}

stop() {
  printf "Stopping ha-proxy: "
  if start-stop-daemon -K -q -p /var/run/ha-proxy.pid; then
    echo "OK"
  else
    echo "FAIL"
  fi
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
    echo "Usage: ha-proxy {start|stop|restart}"
    exit 1
esac

exit $?
