#!/bin/sh
# shellcheck shell=dash disable=SC3010,SC3028,SC2169 source=/dev/null
#
# Starts tailscaled
#

DAEMON="tailscaled"

# only continue if tailscale is enabled
[[ ! -e /etc/config/tailscaleEnabled ]] && exit 0

TAILSCALED_EXEC="/usr/sbin/${DAEMON}"
TAILSCALED_ARGS="-statedir /etc/config/${DAEMON} -state /etc/config/${DAEMON}.state -socket /var/run/tailscale/${DAEMON}.sock"
TAILSCALED_PID="/var/run/tailscale/${DAEMON}.pid"
TAILSCALED_PORT=41641
TAILSCALE_EXEC="/usr/bin/tailscale"
TAILSCALE_WEB_ARGS="-listen 127.0.0.1:25899"
TAILSCALE_UP_ARGS="--advertise-exit-node --advertise-routes $(/sbin/ip route | grep -oE '^\b([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]+\b' | xargs | tr ' ' ',')"
TAILSCALE_PID="/var/run/tailscale/tailscale.pid"

# allow to override the variables
[[ -r /etc/config/tailscaleEnabled ]] && . /etc/config/tailscaleEnabled

case "${1}" in
	start)
		echo -n "Starting ${DAEMON}: "

		# create necessary directories
		mkdir -p /var/run/tailscale /var/lib/tailscale

		# make sure we have a valid PATH variable
		export PATH=/sbin:/usr/bin:/usr/sbin

		# make sure ip forwarding is turned on for v4/v6
		/sbin/sysctl -q net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1 2>/dev/null

		# shellcheck disable=SC2086
		if ! start-stop-daemon -b -S -q -m -p "${TAILSCALED_PID}" -x ${TAILSCALED_EXEC} -- ${TAILSCALED_ARGS} -port ${TAILSCALED_PORT}; then
			echo "FAILED (${TAILSCALED_EXEC})"
			exit 1
		fi

		# shellcheck disable=SC2086
		if ! start-stop-daemon -b -S -q -m -p "${TAILSCALE_PID}" -x ${TAILSCALE_EXEC} -- web ${TAILSCALE_WEB_ARGS}; then
			echo "FAILED (${TAILSCALE_EXEC})"
		else
			echo "OK"
		fi

		# make sure to set tailscale 'up' with the right cmdline args
		# shellcheck disable=SC2086
		${TAILSCALE_EXEC} up ${TAILSCALE_UP_ARGS} >/dev/null 2>&1 &

		## adjust the resolv.conf manually because the original way from tailscale return an error see next comment lines
		# Health check:
		#     - dns-os: writing to "/etc/resolv.pre-tailscale-backup.conf" in rename of "/etc/resolv.conf": open /etc/resolv.pre-tailscale-backup.conf: read-only file system
		#     - dns: writing to "/etc/resolv.pre-tailscale-backup.conf" in rename of "/etc/resolv.conf": open /etc/resolv.pre-tailscale-backup.conf: read-only file system

		# Append the nameserver directive to resolv.conf
		/bin/sed -i '1s/^/nameserver 100.100.100.100\n/' /var/etc/resolv.conf
		# the search directive is not added, because currently we can not in a defined way fetch it
	;;
	stop)
		echo -n "Stopping ${DAEMON}: "
		start-stop-daemon -K -q -p ${TAILSCALE_PID}
		start-stop-daemon -K -q -p ${TAILSCALED_PID}
		echo "OK"

		# roll the manual added entries back, if tailscale is stopped

		# Remove the "nameserver" line
		/bin/sed -i '/^nameserver 100\.100\.100\.100$/d' /var/etc/resolv.conf
	;;
	restart|reload)
		${0} stop
		${0} start
	;;
	*)
		echo "Usage: ${0} {start|stop|restart}"
		exit 1
esac

exit 0
