#!/bin/sh
# shellcheck shell=dash source=/dev/null
#
# Starts tailscaled
#

TAILSCALED_EXEC="/usr/sbin/tailscaled"
TAILSCALED_ARGS="-state /etc/config/tailscaled.state -socket /var/run/tailscale/tailscaled.sock"
TAILSCALED_PID="/var/run/tailscale/tailscaled.pid"
TAILSCALED_PORT=41641
TAILSCALE_EXEC="/usr/bin/tailscale"
TAILSCALE_ARGS="-listen 127.0.0.1:25899"
TAILSCALE_PID="/var/run/tailscale/tailscale.pid"

# only continue if tailscale is enabled
[[ ! -e /etc/config/tailscaleEnabled ]] && exit 0
[[ -r /etc/config/tailscaleEnabled ]] && . /etc/config/tailscaleEnabled

case "${1}" in
  start)
    echo -n "Starting tailscaled: "

    # create necessary directories
    mkdir -p /var/run/tailscale /var/lib/tailscale

    # shellcheck disable=SC2086
    if ! start-stop-daemon -b -S -q -m -p "${TAILSCALED_PID}" -x ${TAILSCALED_EXEC} -- ${TAILSCALED_ARGS} -port ${TAILSCALED_PORT}; then
      echo "FAILED (${TAILSCALED_EXEC})"
      exit 1
    fi

    # shellcheck disable=SC2086
    if ! start-stop-daemon -b -S -q -m -p "${TAILSCALE_PID}" -x ${TAILSCALE_EXEC} -- web ${TAILSCALE_ARGS}; then
      echo "FAILED (${TAILSCALE_EXEC})"
    else
      echo "OK"
    fi
  ;;
  stop)
    echo -n "Stopping tailscaled: "
    start-stop-daemon -K -q -p ${TAILSCALE_PID}
    start-stop-daemon -K -q -p ${TAILSCALED_PID}
    echo "OK"
  ;;
  restart|reload)
    ${0} stop
    ${0} start
  ;;
  *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
esac

exit 0
