#!/bin/sh
#
# Starts lighttpd.
#

[[ -r /var/hm_mode ]] && . /var/hm_mode

PIDFILE=/var/run/lighttpd.pid
PIDFILE_ANGEL=/var/run/lighttpd-angel.pid

# skip this startup if not in normal mode
[[ "${HM_MODE}" != "NORMAL" ]] && exit 0

start() {
  echo -n "Starting lighttpd: "

  # check if a valid/non-expired SSL cert exists and if
  # not we regenerate it.
  if ! /usr/bin/openssl x509 -checkend 86400 -noout -in /etc/config/server.pem 2>/dev/null >/dev/null; then
    [[ -f /etc/config/server.pem ]] && mv -f /etc/config/server.pem /etc/config/server.pem_$(date +'%Y%m%d')
    echo -n "creating new SSL cert... "
    IP=$(ip -4 route get 1 | head -1 | cut -d' ' -f8 | tr -d '\n')
    /usr/bin/openssl req -new -x509 -nodes -keyout /etc/config/server.pem \
                                           -out /etc/config/server.pem \
                                           -days 3650 \
                                           -addext "subjectAltName = DNS:$(hostname),IP:${IP}" \
                                           -addext "keyUsage = keyCertSign,digitalSignature,keyEncipherment" \
                                           -addext "extendedKeyUsage = serverAuth" \
                                           -addext "nsCertType = server,sslCA" \
                                           -subj "/C=DE/O=HomeMatic/OU=$(cat /var/board_serial)/CN=$(hostname)" 2>/dev/null >/dev/null
  fi

  # activate/deactivate service interface authentication
  if [[ -f /etc/config/authEnabled ]] && [[ -f /etc/lighttpd/conf.d/auth.conf ]]; then
    echo "include \"/etc/lighttpd/conf.d/auth.conf\"" >/var/etc/lighttpd_auth.conf
  else
    echo "" >/var/etc/lighttpd_auth.conf
  fi

  # activate/deactivate automatic https redirect
  if [[ -f /etc/config/httpsRedirectEnabled ]]; then
    echo "include \"/etc/lighttpd/conf.d/proxy_httpsredirect.conf\"" >/var/etc/lighttpd_proxy.conf
  else
    echo "include \"/etc/lighttpd/conf.d/proxy_normal.conf\"" >/var/etc/lighttpd_proxy.conf
  fi

  # adjust the oom score (which is inherited by start-stop-daemon)
  # to ensure that others are killed first in case of low memory situations
  echo -900 >/proc/$$/oom_score_adj

  start-stop-daemon -S -q -b -m -p ${PIDFILE_ANGEL} --exec /usr/sbin/lighttpd-angel -- -f /etc/lighttpd/lighttpd.conf -D
  [[ $? -eq 0 ]] && echo "OK" || echo "ERROR"
}
stop() {
  echo -n "Stopping lighttpd: "
  start-stop-daemon -K -q -p ${PIDFILE_ANGEL}
  rm -f ${PIDFILE_ANGEL}
  [[ ! -f ${PIDFILE} ]] && echo "OK" || echo "ERROR"
}
restart() {
  stop
  start
}
reload() {
  echo -n "Reloading lighttpd: "

  # activate/deactivate service interface authentication
  if [[ -f /etc/config/authEnabled ]] && [[ -f /etc/lighttpd/conf.d/auth.conf ]]; then
    echo "include \"/etc/lighttpd/conf.d/auth.conf\"" >/var/etc/lighttpd_auth.conf
  else
    echo "" >/var/etc/lighttpd_auth.conf
  fi

  # activate/deactivate automatic https redirect
  if [[ -f /etc/config/httpsRedirectEnabled ]]; then
    echo "include \"/etc/lighttpd/conf.d/proxy_httpsredirect.conf\"" >/var/etc/lighttpd_proxy.conf
  else
    echo "include \"/etc/lighttpd/conf.d/proxy_normal.conf\"" >/var/etc/lighttpd_proxy.conf
  fi

  start-stop-daemon -K -s HUP -q -p ${PIDFILE_ANGEL}
  sleep 2
  [[ -f ${PIDFILE} ]] && echo "OK" || echo "ERROR"
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  reload)
    reload
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
