#!/bin/sh
#
# Starts lighttpd.
#

source /var/hm_mode 2>/dev/null

# skip this startup in LAN Gateway mode
[[ "${HM_MODE}" == "HM-LGW" ]] && exit 0

start() {
	echo -n "Starting lighttpd: "
	if [[ ! -f /etc/config/server.pem ]]; then
          echo -n "."
          /usr/bin/openssl req -new -x509 -nodes -keyout /etc/config/server.pem \
                                                 -out /etc/config/server.pem \
                                                 -days 3650 \
                                                 -subj "/C=DE/O=HomeMatic/OU=$(cat /var/board_serial)/CN=$(hostname)" 2>/dev/null >/dev/null
        fi

	start-stop-daemon -S -q -b -m -p /var/run/lighttpd-angel.pid --exec /usr/sbin/lighttpd-angel -- -f /etc/lighttpd/lighttpd.conf -D
	[[ $? -eq 0 ]] && echo "OK" || echo "ERROR"
}
stop() {
	echo -n "Stopping lighttpd: "
	start-stop-daemon -K -q -p /var/run/lighttpd-angel.pid
	rm -f /var/run/lighttpd-angel.pid
	[[ ! -f /var/run/lighttpd.pid ]] && echo "OK" || echo "ERROR"
}
restart() {
	stop
	start
}
reload() {
	echo -n "Reloading lighttpd: "
	start-stop-daemon -K -s HUP -q -p /var/run/lighttpd-angel.pid
	sleep 2
	[[ -f /var/run/lighttpd.pid ]] && echo "OK" || echo "ERROR"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  reload)
	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?

