#!/bin/sh
#
# Starts lighttpd.
#

start() {
	echo -n "Starting lighttpd: "
	export TZ=`cat /etc/config/TZ`
	if [[ ! -f /etc/config/server.pem ]]; then
          echo -n "."
          /usr/bin/openssl req -new -x509 -nodes -keyout /etc/config/server.pem \
                                                 -out /etc/config/server.pem \
                                                 -days 3650 \
                                                 -subj "/C=DE/O=HomeMatic/OU=$(cat /var/board_serial)/CN=$(hostname)" 2>/dev/null >/dev/null
        fi

	start-stop-daemon -S -q -p /var/run/lighttpd.pid --exec /usr/sbin/lighttpd -- -f /etc/lighttpd/lighttpd.conf
	[[ $? -eq 0 ]] && echo "OK" || echo "ERROR"
}
stop() {
	echo -n "Stopping lighttpd: "
	start-stop-daemon -K -q -p /var/run/lighttpd.pid
	[[ ! -f /var/run/lighttpd.pid ]] && echo "OK" || echo "ERROR"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

