#!/bin/sh
#
# init script to start/stop the Mediola NEOServer Addon
#

# source all data from /var/hm_mode
[[ -r /var/hm_mode ]] && . /var/hm_mode

# skip this startup in LAN Gateway mode
[[ "${HM_MODE}" == "HM-LGW" ]] && exit 0

# disable the watchdog if NEOServer is disabled
if [[ -e /etc/config/neoDisabled ]] || [[ -e /usr/local/addons/mediola/Disabled ]]; then
  # make sure the watchdog is disabled
  if grep -q "/usr/local/addons/mediola/bin/watchdog" /usr/local/crontabs/root 2>/dev/null; then
    sed -i '/\/usr\/local\/addons\/mediola\/bin\/watchdog/d' /usr/local/crontabs/root
  fi
fi

# if NEOServer is permanently disabled exit immediately
[[ -e /etc/config/neoDisabled ]] && exit 0

start() {
  echo -n "Starting NeoServer: "

  if [[ ! -e /etc/config/safemode ]]; then
    /opt/mediola/startup.sh 2>/dev/null >/dev/null
    /usr/local/addons/mediola/bin/watchdog
  else
    echo "skipping (safemode)"
  fi
}

stop() {
  if [[ -f /usr/local/addons/mediola/rc.d/97NeoServer ]]; then
    /usr/local/addons/mediola/rc.d/97NeoServer stop
  fi
}

restart() {
  stop
  sleep 2
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart}"
    exit 1
esac

exit $?
