#!/bin/sh
#
# Starts rfd.
#

LOGLEVEL_RFD=5
CFG_TEMPLATE_DIR=/etc/config_templates
PIDFILE=/var/run/rfd.pid

source /var/hm_mode 2>/dev/null

# skip this startup in LAN Gateway mode
[[ ${HM_MODE} == "HMLGW" ]] && exit 0

init() {

	if [ ! -d /etc/config/rfd ] ; then
  		mkdir /etc/config/rfd
	fi

	#Migration for existing rfd.conf in user space
	if [ ! -e /etc/config/rfd.conf ] ; then
		cp $CFG_TEMPLATE_DIR/rfd.conf /etc/config/rfd.conf
  fi

  # patch some settings to match what this hardware expects.
  if [[ ${HM_MODE} == "HmIP" ]]; then
    sed -i 's/^ComPortFile = \/dev\/.*$/ComPortFile = \/dev\/mmd_bidcos/' /etc/config/rfd.conf
  else
    sed -i 's/^ComPortFile = \/dev\/.*$/ComPortFile = \/dev\/ttyAMA0/' /etc/config/rfd.conf
  fi
  sed -i 's/^#*AccessFile = \/dev\/.*$/AccessFile = \/dev\/null/' /etc/config/rfd.conf
  sed -i 's/^#*ResetFile = \/dev\/.*$/ResetFile = \/dev\/null/' /etc/config/rfd.conf
  if ! grep -q "Improved Coprocessor Initialization" /etc/config/rfd.conf ; then
    sed -i 's/\[Interface 0\]/Improved\ Coprocessor\ Initialization\ =\ true\n\n&/' /etc/config/rfd.conf
  fi

	if [ ! -e /etc/config/syslog ] ; then
		cp $CFG_TEMPLATE_DIR/syslog /etc/config
	fi
	if [ -e /etc/config/syslog ] ; then
  		. /etc/config/syslog
	fi

}

waitStartupComplete() {
	STEPS=20
    for i in $(seq 1 $STEPS)
    do
		sleep 2
		echo -n "."
        RFDSTATUSPID=`cat /var/status/rfd.status 2>&1`
        RFDPID=`pidof rfd`
        if [ "$RFDSTATUSPID" = "$RFDPID" ] 
		then
            echo "OK"
            break
        fi
        if [ $i -eq $STEPS ] 
		then
            echo "ERROR"
        fi
    done
}

start() {
	echo -n "Starting rfd: "
	init
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec /bin/rfd -- -f /etc/config/rfd.conf -l $LOGLEVEL_RFD
	waitStartupComplete
}
stop() {
	echo -n "Stopping rfd: "
	start-stop-daemon -K -q -p $PIDFILE
	rm -f $PIDFILE
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

