#! /bin/sh
DAEMON="OpenVPN"
ADDONNAME=mhmopenvpn
ADDONDIR=/etc/config/addons/$ADDONNAME
WWWDIR=/etc/config/addons/www/$ADDONNAME
CONFIGDIR=/usr/local/etc/config
RCDDIR=$CONFIGDIR/rc.d

openvpn=$ADDONDIR/openvpn
piddir=/var/run/openvpn

case "$1" in
  ""|start)
	test -x $openvpn || {
	        echo 1>&2 "$openvpn not installed"
	        exit 5 
	}

	logger -t homematic -p user.info "starting mhmopenvpn"
        mkdir -p /dev/net
        mknod /dev/net/tun c 10 200
        insmod $ADDONDIR/tun.ko
        $openvpn --daemon \
		--config $ADDONDIR/client.conf \
		--cd $ADDONDIR \
	&& logger -t homematic -p user.info "starting mhmopenvpn"

  ;;

  stop)
	killall -KILL openvpn  >/dev/null 2>&1 || true
	logger -t homematic -p user.info "killed mhmopenvpn"
  ;;
  
  info)
	echo "Info: <center><b>www.meine-homematic.de</b></center><br><br>"
	echo "Basis Paket, OpenVPN 2.09"
        echo "Info: Ermöglicht einen gesicherten Fernzugriff auf die heimische HomeMatic CCU. Stellt zusätzlich Zugriff auf einen Mail Server und ein SMS Gateway bereit."
        echo "Name: mhmopenvpn"
        echo "Version: 1.0"
        echo "Operations: uninstall restart"
	echo "Config-Url: /addons/$ADDONNAME/index.html"
	echo "Update: http://www.meine-homematic.de/ver.php"
  ;;
  
  restart)
	logger -t homematic -p user.info "restarting mhmopenvpn"
	$0 stop
	sleep 2
	$0 start
  ;;
  
  uninstall)
	$0 stop
	rm  -rf $ADDONDIR
	logger -t homematic -p user.info "uninstalled mhmopenvpn"	
  ;;

  *)
        echo "Usage: tools {start|stop|info|restart|uninstall}" >&2
        exit 1
  ;;
esac

exit 0
