#!/bin/sh

# source all data from /var/hm_mode
[[ -r /var/hm_mode ]] && . /var/hm_mode

# signal that we are about to setup the network
# connection using a blinking blue LED
if [[ "${HM_HMRF_DEV}" == "RPI-RF-MOD" ]] ||
   [[ "${HM_HMIP_DEV}" == "RPI-RF-MOD" ]]; then
  echo none >/sys/class/leds/rpi_rf_mod\:green/trigger
  echo none >/sys/class/leds/rpi_rf_mod\:red/trigger
  echo timer >/sys/class/leds/rpi_rf_mod\:blue/trigger
fi

# performance tuning to reduce TCP performance spikes
/sbin/sysctl -w net.ipv4.tcp_timestamps=0 >/dev/null 2>&1 || true

# we exit if if-up.d is called for "lo"
if [[ "${IFACE}" == "lo" ]]; then
  exit 0
fi

# only continue if this network interface exists
if [[ ! -L "/sys/class/net/${IFACE}" ]]; then
  echo -n "${IFACE}:missing, "
  exit 0
fi

# only continue if another interface hasn't
# setup everything correctly already
if [[ -e /var/status/hasIP ]]; then
  /sbin/ip link set ${IFACE} down
  echo -n "${IFACE}:disabled, "

  # make sure that the wifi power is disabled
  # if not required
  case "${IFACE}" in
    wlan*)
      /usr/sbin/rfkill block wlan
    ;;
  esac
  exit 0
fi

# make sure iface is really up
if [[ "$(cat /sys/class/net/${IFACE}/operstate)" == "down" ]]; then
  /sbin/ip link set ${IFACE} up
  sleep 5
fi

# start WPA Supplicant if this is a WiFi connection
case "${IFACE}" in
  eth*)
    # if eth0 doesn't have a link we don't continue
    if [[ "${IFACE}" == "eth0" && "$(cat /sys/class/net/${IFACE}/carrier)" == "0" ]]; then
      /sbin/ip link set ${IFACE} down
      echo -n "${IFACE}:no link, "
      exit 0
    fi
  ;;

  wlan*)
    if [[ -e /etc/config/wpa_supplicant.conf ]]; then
      /usr/sbin/rfkill unblock wlan
      /usr/sbin/wpa_supplicant -B w -D wext -i ${IFACE} -c /etc/config/wpa_supplicant.conf -s
    else
      /sbin/ip link set ${IFACE} down
      echo -n "${IFACE}:no config, "
      # make sure that the wifi power is disabled
      # if not required
      /usr/sbin/rfkill block wlan
      exit 0
    fi
  ;;
esac

echo -n "${IFACE}: up, "

# cleanup first
RESOLV_CONF=/var/etc/resolv.conf
rm -f "${RESOLV_CONF}"
mkdir -p /var/status
rm -f /var/status/hasLink
rm -f /var/status/hasIP
rm -f /var/status/hasInternet

# source in the network config
[[ -r /etc/config/netconfig ]] && . /etc/config/netconfig

# setup the hostname
echo "${HOSTNAME}" >/etc/hostname
hostname "${HOSTNAME}"

# setup /etc/hosts
echo "127.0.0.1 localhost" >/etc/hosts
echo "127.0.1.1 ${HOSTNAME}" >>/etc/hosts

# restart syslogd to update hostname
/etc/init.d/S07logging restart 2>/dev/null >/dev/null

# set multicast routes
/sbin/ip route del 224.0.0.0/4 2>/dev/null
/sbin/ip route add 224.0.0.0/4 dev ${IFACE}

# check if we booting via nfs
if grep -q nfsroot /proc/cmdline ; then
   echo Running from nfs root. Skipping network configuration.

   # has IP  
   touch /var/status/hasLink
   touch /var/status/hasIP

   # check internet connection; use fix ip to google because no nameserver (nfs boot)
   /usr/bin/wget -q --spider http://216.58.213.238/
   if [[ $? -eq 0 ]]; then
     touch /var/status/hasInternet
   elif ping -q -W 5 -c 1 8.8.8.8 >/dev/null 2>/dev/null; then
     touch /var/status/hasInternet
   fi

   exit 0
fi

# make sure no other udhcpc is running
killall -q udhcpc

# if DHCP is enabled we run udhcpc
case "${MODE}" in

  # if DHCP is enabled we "only" run udhcpc
  DHCP)
    echo -n "dhcp, "

    /sbin/udhcpc -b -t 100 -T 3 -S -x hostname:${HOSTNAME} -i ${IFACE} -F ${HOSTNAME} -V eQ3-CCU2 -s /bin/dhcp.script -p /var/run/udhcpc_${IFACE}.pid 2>/dev/null >/dev/null
    if [[ ! -f "/var/run/udhcpc_${IFACE}.pid" ]]; then
      killall checkDHCP
      /bin/checkDHCP ${IFACE} &
    fi
  ;;

  # everything else means we are setting a static IP
  *)
    echo -n "static, "

    # we checked the link state already way earlier
    touch /var/status/hasLink

    /sbin/ip addr add ${IP}/${NETMASK} dev ${IFACE}
    /sbin/ip route del default 2>/dev/null
    /sbin/ip route add default via ${GATEWAY}

    if [[ -n "${NAMESERVER1}" ]]; then
      echo nameserver "${NAMESERVER1}" >>${RESOLV_CONF}
    fi

    if [[ -n "${NAMESERVER2}" ]]; then
      echo nameserver "${NAMESERVER2}" >>${RESOLV_CONF}
    fi

    # update CURRENT_XYZ in /etc/config/netconfig

    # update /etc/config/netconfig
    eq3configcmd netconfigcmd -i ${IP} -g ${GATEWAY} -n ${NETMASK}

    if [[ -n "${NAMESERVER1}" ]]; then
      eq3configcmd netconfigcmd -d1 ${NAMESERVER1}
    else
      eq3configcmd netconfigcmd -d1 ""
    fi

    if [[ -n "${NAMESERVER2}" ]]; then
      eq3configcmd netconfigcmd -d2 ${NAMESERVER2}
    else
      eq3configcmd netconfigcmd -d2 ""
    fi

    touch /var/status/hasIP

    # check internet connection
    /usr/bin/wget -q --spider http://google.com/
    if [[ $? -eq 0 ]]; then
      touch /var/status/hasInternet
    elif ping -q -W 5 -c 1 google.com >/dev/null 2>/dev/null; then
      touch /var/status/hasInternet
    fi
  ;;

esac

# init the firewall only in case
# we are in normal startup mode
if [[ "${HM_MODE}" == "NORMAL" ]]; then
  # set firewall rules
  /bin/setfirewall.tcl
  echo -n "firewall, "
fi

IP=$(ip -4 route get 1 | head -1 | cut -d' ' -f8 | tr -d '\n')
echo -n "${IP}, "

exit 0
