#!/bin/sh

# only continue if another interface hasn't
# setup everything correctly already
if [[ -e /var/status/hasIP ]]; then
  exit 0
fi

# we exit if if-up.d is called for "lo"
if [[ ${IFACE} == "lo" ]]; then
  exit 0
fi

# make sure iface is really up
if [[ $(cat /sys/class/net/${IFACE}/operstate) == "down" ]]; then
  /sbin/ifconfig ${IFACE} up
  sleep 5
fi

# start WPA Supplicant if this is a WiFi connection
case ${IFACE} in
  wlan*)
    if [[ -e /etc/config/wpa_supplicant.conf ]]; then
      /usr/sbin/wpa_supplicant -B w -D wext -i ${IFACE} -c /etc/config/wpa_supplicant.conf -dd
    else
      exit 0
    fi
  ;;
esac

# cleanup first
RESOLV_CONF=/var/etc/resolv.conf
rm -f ${RESOLV_CONF}
mkdir -p /var/status
rm -f /var/status/hasLink
rm -f /var/status/hasIP
rm -f /var/status/hasInternet

# source in the network config
. /etc/config/netconfig

hostname ${HOSTNAME}

# set multicast routes
route del -net 224.0.0.0 netmask 240.0.0.0 2>/dev/null
route add -net 224.0.0.0 netmask 240.0.0.0 dev ${IFACE}

# check if we booting via nfs
if grep -q nfsroot /proc/cmdline ; then
   echo Running from nfs root. Skipping network configuration.

   # has IP  
   touch /var/status/hasLink
   touch /var/status/hasIP

   # check internet connection; use fix ip because no nameserver (nfs boot) 
   if ping -W 5 -c 1 google.com >/dev/null; then
     touch /var/status/hasInternet
   fi
   exit 0
fi

# make sure no other udhcpc is running
killall -q udhcpc

# if DHCP is enabled we run udhcpc
case ${MODE} in

  # if DHCP is enabled we "only" run udhcpc
  DHCP)
    /sbin/udhcpc -b -t 100 -T 3 -S -x hostname:${HOSTNAME} -i ${IFACE} -C -F ${HOSTNAME} -V eQ3-CCU2 -s /bin/dhcp.script -p /var/run/udhcpc_${IFACE}.pid
    if [[ ! -f "/var/run/udhcpc_${IFACE}.pid" ]]; then
      killall checkDHCP
      /bin/checkDHCP ${IFACE} &
    fi
  ;;

  # everything else means we are setting a static IP
  *)
    if [[ $(cat /sys/class/net/${IFACE}/carrier) -eq 1 ]]; then
      echo "${IFACE}: link detected"
      touch /var/status/hasLink
    else
      echo "${IFACE}: no link detected"
      exit 1
    fi

    /sbin/ifconfig ${IFACE} ${IP} netmask ${NETMASK}
    /sbin/route del default 2>/dev/null
    /sbin/route add default gw ${GATEWAY}

    if [[ -n ${NAMESERVER1} ]]; then
      echo nameserver ${NAMESERVER1} >>${RESOLV_CONF}
    fi

    if [[ -n ${NAMESERVER2} ]]; then
      echo nameserver ${NAMESERVER2} >>${RESOLV_CONF}
    fi

    # update CURRENT_XYZ in /etc/config/netconfig

    # update /etc/config/netconfig
    eq3configcmd netconfigcmd -i ${IP} -g ${GATEWAY} -n ${NETMASK}

    if [[ -n ${NAMESERVER1} ]]; then
      eq3configcmd netconfigcmd -d1 ${NAMESERVER1}
    else
      eq3configcmd netconfigcmd -d1 ""
    fi

    if [[ -n ${NAMESERVER2} ]]; then
      eq3configcmd netconfigcmd -d2 ${NAMESERVER2}
    else
      eq3configcmd netconfigcmd -d2 ""
    fi

    touch /var/status/hasIP

    # check internet connection; use fix ip because no nameserver (nfs boot)
    if ping -W 5 -c 1 google.com >/dev/null 2>/dev/null; then
      touch /var/status/hasInternet
    fi
  ;;

esac

exit 0
