#!/bin/sh
#
# Starts lighttpd.
#

start() {
	echo -n "Starting lighttpd: "
	export TZ=`cat /etc/config/TZ`
	start-stop-daemon -S -q -p /var/run/lighttpd.pid --exec /usr/sbin/lighttpd -- -f /etc/lighttpd/lighttpd.conf

	echo "OK"
	if [ -f /etc/config/server.pem ] ; then
		echo -n "Starting lighttpd with SSL support: "
		start-stop-daemon -S -q -p /var/run/lighttpd_ssl.pid --exec /usr/sbin/lighttpd -- -f /etc/lighttpd/lighttpd_ssl.conf
		echo "OK"
	fi
}
stop() {
	echo -n "Stopping lighttpd: "
	start-stop-daemon -K -q -p /var/run/lighttpd.pid
	start-stop-daemon -K -q -p /var/run/lighttpd_ssl.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

