#!/bin/sh
#
# Starts eq3configd.
#

init () {

  # we output the BidCos-Address and the
  # SerialNumber to /var/ids
  echo "BidCoS-Address=$(cat /var/rf_address)" >/var/ids
  echo "SerialNumber=$(cat /var/board_serial)" >>/var/ids

  if [[ ! -e /etc/config/ids ]] ; then
    cp /var/ids /etc/config/
  fi
	
	if [[ ! -e /etc/config/crypttool.cfg ]] ; then
			touch /etc/config/crypttool.cfg
	fi
}

start() {
	echo -n "Starting eq3configd: "
	init
	start-stop-daemon -S -q -b -m -p /var/run/eq3configd.pid --exec /bin/eq3configd
	echo "OK"
	echo -n "Starting ssdpd: "
	start-stop-daemon -S -q -b -m -p /var/run/ssdpd.pid --exec /bin/ssdpd
	echo "OK"
}
stop() {
	echo -n "Stopping ssdpd: "
	start-stop-daemon -K -q -p /var/run/ssdpd.pid
	rm -f /var/run/ssdpd.pid
	echo "OK"
	echo -n "Stopping eq3configd: "
	start-stop-daemon -K -q -p /var/run/eq3configd.pid
	rm -f /var/run/eq3configd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

