#!/bin/sh
#
# Starts eq3configd.
#

init () {

  # we output the BidCos-Address and the
  # SerialNumber to /var/ids
  echo "BidCoS-Address=$(cat /var/rf_address)" >/var/ids
  echo "SerialNumber=$(cat /var/board_serial)" >>/var/ids

  # in case we have a BidCos-RF device (no empty /var/rf_address)
  # and there is no already existing /etc/config/ids we have to
  # copy it over
  if [[ -s /var/rf_address ]] && [[ ! -e /etc/config/ids ]] ; then
    cp /var/ids /etc/config/
  fi

  if [[ ! -e /etc/config/crypttool.cfg ]] ; then
    touch /etc/config/crypttool.cfg
  fi
}

start() {
  echo -n "Starting eq3configd: "
  init

  # adjust the oom score (which is inherited by start-stop-daemon)
  # to ensure that others are killed first in case of low memory situations
  echo -900 >/proc/$$/oom_score_adj 2> /dev/null

  start-stop-daemon -S -q -b -m -p /var/run/eq3configd.pid --exec /bin/eq3configd
  echo "OK"
}
stop() {
  echo -n "Stopping eq3configd: "
  start-stop-daemon -K -q -p /var/run/eq3configd.pid
  rm -f /var/run/eq3configd.pid
  echo "OK"
}
restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
