var HARDWARE_VERSION="A1",FIRMWARE_VERSION="2.4.1",TASKMANAGER_VERSION="2.4.1",PLATFORM="CCU3",hasLocalStorage=!0;if("undefined"==typeof localStorage||null==localStorage)hasLocalStorage=!1,localStorage={};require("x.core.js");console.log((new Date).toString()+" ===========> started");var os=require("os"),fs=require("fs"),path=require("path"),async=require("async"),ls=require("node-localstorage").LocalStorage,xhub=require("x.hub.js"),v5=require("x.hub.v5.js"),miot=require("xnm.aio.m10T.js"),xnm=xnm||{};xnm.aio=xnm.aio||{};
xnm.aio.xhub=xnm.aio.xhub||{};global.HARDWARE_VERSION="EA";global.FIRMWARE_VERSION="development";global.TASKMANAGER_VERSION="2.4.1";global.PLATFORM=null;global.NAME=null;global.VID=null;global.CLOUD_URL="https://webservice.mediola.com";global.CONTROL_SERVER="v5ws.mediola.com";global.LOAD_MODULES=null;global.DATA_FOLDER=null;global.APP_FOLDER=null;global.LOG_ROOT=null;global.WEB_SERVER_PORT=80;global.STM=null;global.HM_CHIP=null;global.HM_LOCAL_PORT=9099;global.ENOCEAN_PORT=null;
global.ZWAVE2_URL=null;global.ZWAVE2_PORT=null;global.SAFE_MODE=!1;
function _loadCompilerConfig(){"undefined"!=typeof HARDWARE_VERSION&&HARDWARE_VERSION&&(global.HARDWARE_VERSION=HARDWARE_VERSION);"undefined"!=typeof FIRMWARE_VERSION&&FIRMWARE_VERSION&&(global.FIRMWARE_VERSION=FIRMWARE_VERSION);"undefined"!=typeof TASKMANAGER_VERSION&&TASKMANAGER_VERSION&&(global.TASKMANAGER_VERSION=TASKMANAGER_VERSION);"undefined"!=typeof PLATFORM&&PLATFORM&&(global.PLATFORM=PLATFORM);"undefined"!=typeof NAME&&NAME&&(global.NAME=NAME);"undefined"!=typeof VID&&VID&&(global.VID=VID);
"undefined"!=typeof CLOUD_URL&&CLOUD_URL&&(global.CLOUD_URL=CLOUD_URL);"undefined"!=typeof CONTROL_SERVER&&CONTROL_SERVER&&(global.CONTROL_SERVER=CONTROL_SERVER);"undefined"!=typeof LOAD_MODULES&&LOAD_MODULES&&(global.LOAD_MODULES=LOAD_MODULES)}
function _loadProgrammEnv(){process&&process.env&&(process.env.HARDWARE_VERSION&&(global.HARDWARE_VERSION=process.env.HARDWARE_VERSION),process.env.FIRMWARE_VERSION&&(global.FIRMWARE_VERSION=process.env.FIRMWARE_VERSION),process.env.TASKMANAGER_VERSION&&(global.TASKMANAGER_VERSION=process.env.TASKMANAGER_VERSION),process.env.PLATFORM&&(global.PLATFORM=process.env.PLATFORM),process.env.NAME&&(global.NAME=process.env.NAME),process.env.VID&&(global.VID=process.env.VID))}
function _loadConfigFile(){function d(d){if(d)for(var e in d)d.hasOwnProperty(e)&&(global[e]="DATA_FOLDER"==e||"APP_FOLDER"==e||"LOG_ROOT"==e?path.isAbsolute(d[e])?d[e]:path.resolve(__dirname,d[e]):d[e])}function e(){try{var f=require("./package.json");f&&d(f.config)}catch(e){}}function k(){try{var f=require("./config.json");d(f)}catch(e){}}switch(global.HARDWARE_VERSION){case "A1":e();break;case "EA":k()}}
function _loadRuntimeConfig(){switch(global.HARDWARE_VERSION){case "A1":if(null==global.PLATFORM)switch(os.platform()){case "darwin":global.PLATFORM="MAC";break;case "win32":global.PLATFORM="WIN";break;default:global.PLATFORM="LINUX"}null==global.NAME&&(global.NAME="NEO Server");null==global.VID&&(global.VID=null);null==global.CLOUD_URL&&(global.CLOUD_URL="https://webservice.mediola.com");null==global.CONTROL_SERVER&&(global.CONTROL_SERVER="v5ws.mediola.com");null==global.LOAD_MODULES&&(global.LOAD_MODULES=
["knx"]);null==global.DATA_FOLDER&&(global.DATA_FOLDER=null);null==global.APP_FOLDER&&(global.APP_FOLDER=null);null==global.LOG_ROOT&&(global.LOG_ROOT=null);null==global.WEB_SERVER_PORT&&(global.WEB_SERVER_PORT=8088);null==global.HM_CHIP&&(global.HM_CHIP=null);null==global.HM_LOCAL_PORT&&(global.HM_LOCAL_PORT=9099);null==global.ENOCEAN_PORT&&(global.ENOCEAN_PORT=null);null==global.ZWAVE2_URL&&(global.ZWAVE2_URL=null);null==global.ZWAVE2_PORT&&(global.ZWAVE2_PORT=null);null==global.STM&&(global.STM=
null);break;case "EA":if(null==global.PLATFORM&&(global.PLATFORM="A20"),null==global.NAME&&(global.NAME="AIO GATEWAY V5+"),null==global.VID&&(global.VID=null),null==global.CLOUD_URL&&(global.CLOUD_URL="https://webservice.mediola.com"),null==global.CONTROL_SERVER&&(global.CONTROL_SERVER="v5ws.mediola.com"),null==global.LOAD_MODULES&&(global.LOAD_MODULES=["enocean","zway","knx","zigbee"]),null==global.DATA_FOLDER&&(global.DATA_FOLDER=path.resolve(__dirname,"./data")),null==global.APP_FOLDER&&(global.APP_FOLDER=
path.resolve(__dirname,"./data")),null==global.LOG_ROOT&&(global.LOG_ROOT="/var/log"),null==global.WEB_SERVER_PORT&&(global.WEB_SERVER_PORT=80),null==global.HM_CHIP&&(global.HM_CHIP="127.0.0.1"),null==global.HM_LOCAL_PORT&&(global.HM_LOCAL_PORT=9099),null==global.ENOCEAN_PORT&&(global.ENOCEAN_PORT=null),null==global.ZWAVE2_URL&&(global.ZWAVE2_URL="127.0.01"),null==global.ZWAVE2_PORT&&(global.ZWAVE2_PORT=9E3),!global.STM)switch(global.PLATFORM){case "MAC":global.STM=null;break;case "WIN":global.STM=
null;break;case "A20":global.STM="/dev/ttyS2";break;case "PI2":global.STM="/dev/spidev0.1";break;default:global.STM="/dev/ttyACM0"}}"undefined"!=typeof global.CONTROL_SERVER&&global.CONTROL_SERVER&&(require("x.hub.v5.js").CloudConnect.prototype.CLOUD_SERVER=global.CONTROL_SERVER);"undefined"!=typeof global.CLOUD_URL&&global.CLOUD_URL&&(require("x.hub.taskman.js").Cloud.prototype.URL=global.CLOUD_URL);"undefined"!=typeof global.TASKMANAGER_VERSION&&global.TASKMANAGER_VERSION&&(require("x.hub.taskman.js").TaskManager.NS_VERSION=
global.TASKMANAGER_VERSION)}
function _setupServer(){var d=null;switch(global.PLATFORM){case "MAC":d=new xhub.Server(global.STM);break;case "WIN":d=new xhub.Server(global.STM);break;case "A20":d=new xhub.Server(global.STM);break;case "PI2":d=new xhub.Server(global.STM,null,"gpio26");break;default:d=new xhub.Server(global.STM)}d.hostType=global.PLATFORM;xhub.server=d;v5.server=d;d.HWV=global.HARDWARE_VERSION;d.VERSION=global.FIRMWARE_VERSION;d.DEFAULT_NAME=global.NAME;var e=null,k=Date.now();d.on("serialevent",function(c,b){require("x.logger.js").getLogger("x.hub.m.gateway.Serial").log("trace",
"SERIAL EVENT: "+c);var a=e,q=Date.now()-k;k=Date.now();e=c;if(!(a==c&&1E3>q)){a=null;try{a=JSON.parse(c)}catch(g){}a&&(require("x.hub.eventbus.js").emit("gatewayevent",a,{address:"ST"},b),"EVT"!=b&&"STA"!=b||d.sendUDPMessage(b+":"+JSON.stringify(a)+"\r\n"))}});d.setCmdFunc("refreshhm",function(c,b){b(JSON.stringify({XC_SUC:{}}))});d.setCmdFunc("resethm",function(c,b){require("x.hub.m.hm.js").resetChip(function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))})});
d.setCmdFunc("addSensor",function(c,b){c.query.type&&"ENOCEAN"==c.query.type.toUpperCase()?require("x.hub.m.enocean.js").addSensor(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):b(null)});d.setCmdFunc("LearnSC",function(c,b){if(c.query.type&&"HM"==c.query.type.toUpperCase()){var a=require("x.hub.m.hm.js");c.query.key&&c.query.sgtin?a.learnIPDevice(null,c.query.sgtin,c.query.key,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",
msg:a.error.message}})):b(JSON.stringify({XC_SUC:{devices:a.data}}))}):c.query.qrkey?a.learnIPDeviceQR(null,c.query.qrkey,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{devices:a.data}}))}):c.query.adr?a.learnRFDeviceSN(null,c.query.adr,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{devices:a.data}}))}):a.learnRFDevice(null,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",
msg:a.error.message}})):b(JSON.stringify({XC_SUC:{devices:a.data}}))})}else c.query.type&&"ENOCEAN"==c.query.type.toUpperCase()?require("x.hub.m.enocean.js").learnDevice(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:a.data}))}):c.query.type&&"ZIGBEE"==c.query.type.toUpperCase()?require("x.hub.m.zigbee.js").learnDevice(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:a.data}))}):
b(null)});d.setCmdFunc("SendSC",function(c,b){c.query.type&&"HM"==c.query.type.toUpperCase()?c.query.address&&c.query.data?require("x.hub.m.hm.js").executeCommandLegacy(null,c.query.address,c.query.data,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):b(JSON.stringify({XC_ERR:{code:"001000",msg:"address or data invalid"}})):c.query.type&&"ENOCEAN"==c.query.type.toUpperCase()?c.query.address&&c.query.data?require("x.hub.m.enocean.js").executeCommandLegacy(null,
c.query.address,c.query.data,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):b(JSON.stringify({XC_ERR:{code:"001000",msg:"address or data invalid"}})):c.query.type&&"ZWAVE"==c.query.type.toUpperCase()?c.query.address&&c.query.data&&c.query.devicetype?require("x.hub.m.zwave.js").executeCommandLegacy(null,c.query.address,c.query.devicetype,c.query.data,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):
b(JSON.stringify({XC_SUC:{}}))}):b(JSON.stringify({XC_ERR:{code:"001000",msg:"address or data or devicetype invalid"}})):c.query.type&&"ZWAVE2"==c.query.type.toUpperCase()?require("x.hub.m.zway.js").executeCommandLegacy(c.query.address,c.query.data,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):c.query.type&&"KNX"==c.query.type.toUpperCase()?require("x.hub.m.knx.js").executeCommandLegacy(c.query.address,c.query.data,function(a){a.error?
b(JSON.stringify({XC_ERR:{code:a.error.code?a.error.code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):c.query.type&&"ZIGBEE"==c.query.type.toUpperCase()?require("x.hub.m.zigbee.js").executeCommandLegacy(c.query.address,c.query.data,function(a){a.error?b(JSON.stringify({XC_ERR:{code:a.error.code?a.error.code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):"PI2"==d.hostType&&"RGB"==c.query.type&&c.query.data&&8==c.query.data.length?(v5&&v5.setRGBColor(c.query.data.substr(2)),
b(JSON.stringify({XC_SUC:{}}))):b(null)});d.setCmdFunc("delSensor",function(c,b){c.query.type&&"HM"==c.query.type.toUpperCase()?c.query.adr?require("x.hub.m.hm.js").deleteDevice(null,c.query.adr,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):b(JSON.stringify({XC_ERR:{code:"001000",msg:"adr invalid"}})):c.query.type&&"ENOCEAN"==c.query.type.toUpperCase()?require("x.hub.m.enocean.js").delSensor(c.query.address,function(a){a.error?
b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):c.query.type&&"ZIGBEE"==c.query.type.toUpperCase()?require("x.hub.m.zigbee.js").removeDevice(c.query.address,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):b(null)});d.setCmdFunc("gethmconfig",function(c,b){c.query.address?require("x.hub.m.hm.js").getConfig({address:c.query.address},function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",
msg:a.error.message}})):b(JSON.stringify({XC_SUC:{config:a.data}}))}):b(null)});d.setCmdFunc("sethmconfig",function(c,b){c.query.address&&c.query.config?require("x.hub.m.hm.js").setConfig({address:c.query.address},c.query.config,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):b(null)});d.setCmdFunc("setVar",function(c,b){require("x.hub.sysvarman.js").setVar(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):
b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("delVar",function(c,b){require("x.hub.sysvarman.js").delVar(c.query.id,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"001000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))})});var f=[],h=null;d.setCmdFunc("getStates",function(c,b){var a=function(a,b){var c=f;f=[];a?c.forEach(function(b){b(JSON.stringify({XC_ERR:{code:"001000",msg:a.message}}))}):0<b.length?c.forEach(function(a){a(JSON.stringify({XC_SUC:b}))}):c.forEach(function(a){a(JSON.stringify({XC_SUC:{}}))})},
d=[],g=[],e=[],n=f.length,r=(new Date).getTime();0!=n&&18E4<r-h&&(a(Error("get states dead lock")),n=f.length);-1==f.indexOf(b)&&f.push(b);0==n&&(h=(new Date).getTime(),async.parallel([function(a){if("A20"!=global.PLATFORM&&"PI2"!=global.PLATFORM)a();else if(localStorage&&"true"==localStorage.getItem("x.hub.Server.DISABLE_ST_STATES"))a();else{var b=setTimeout(function(){g.push({type:"ST_ERROR",state:"st timeout"});a&&(a(),a=null)},1E4);xhub.server._doSTMCommandRequest("/cmd?XC_FNC=getStates",!1,function(c){b&&
(clearTimeout(b),b=null);if(a){try{var d=JSON.parse(c);d.XC_SUC?Array.isArray(d.XC_SUC)?g=g.concat(d.XC_SUC):0<Object.keys(d.XC_SUC).length&&(g=g.push(d.XC_SUC)):g.push({type:"ST_ERROR",state:"st return:"+c});a()}catch(q){g.push({type:"ST_ERROR",state:"st return invalid json"}),a()}a=null}})}},function(a){require("x.hub.m.hm.js").getAllStatesLegacy(function(b){b.error?d.push({type:"HM_ERROR",state:b.error}):d=d.concat(b.data);a()})},function(a){-1==global.LOAD_MODULES.indexOf("enocean")?a():require("x.hub.m.enocean.js").getAllStatesLegacy(function(b){b.error?
d.push({type:"ENOCEAN_ERROR",state:b.error}):d=d.concat(b.data);a()},c.query)},function(a){-1==global.LOAD_MODULES.indexOf("zwave")?a():require("x.hub.m.zwave.js").getAllStatesLegacy(function(b){b.error?d.push({type:"ZWAVE_ERROR",state:b.error}):d=d.concat(b.data);a()})},function(a){require("x.hub.m.zway.js").getAllStatesLegacy(function(b){b.error?d.push({type:"ZWAVE2_ERROR",state:b.error}):d=d.concat(b.data);a()})},function(a){-1==global.LOAD_MODULES.indexOf("knx")?a():require("x.hub.m.knx.js").getAllStatesLegacy(function(b){b.error?
d.push({type:"KNX_ERROR",state:b.error}):d=d.concat(b.data);a()})},function(a){-1==global.LOAD_MODULES.indexOf("zigbee")?a():require("x.hub.m.zigbee.js").getAllStatesLegacy(function(b){b.error?d.push({type:"ZIGBEE_ERROR",state:b.error}):d=d.concat(b.data);a()})},function(a){require("x.hub.taskman.js").readAllTasks(function(b){if(b.error)d.push({type:"TASK_ERROR",state:b.error});else{var c=[];b.data.forEach(function(a){a&&c.push({type:"TASK",id:a.id,active:a.active})});d=d.concat(c)}a()})},function(a){require("x.hub.sysvarman.js").getSysvarStates(function(b){b.error?
d.push({type:"SYSVAR_ERROR",state:b.error}):e=e.concat(b.data);a()})}],function(b){b?a(b,d):g&&0<g.length?require("x.hub.sysvarman.js").processSysvarST(xhub.server,g,function(c){c&&!c.error&&c.data&&0<c.data.length&&(d=d.concat(c.data));a(b,d)}):(e&&0<e.length&&(d=d.concat(e)),a(b,d))}))});d.setCmdFunc("getSI",function(c,b){d.doSTMCommand("XC_FNC=GetSI",function(a){a&&a.XC_SUC&&(a.XC_SUC.HWV=d.HWV,!err&&tz&&(a.XC_SUC.TZ=tz+""));b(JSON.stringify(a))})});d.setCmdFunc("GetSI",function(c,b){d.getTimeZoneCompatiable(function(a,
c){d.doSTMCommand("XC_FNC=GetSI",function(g){g&&g.XC_SUC&&(g.XC_SUC.HWV=d.HWV,!a&&c&&(g.XC_SUC.TZ=c+""));b(JSON.stringify(g))})})});d.setCommandFunc("GetSI",function(c,b){d.getTimeZoneCompatiable(function(a,c){d.doSTMCommand("XC_FNC=GetSI",function(g){g&&g.XC_SUC?(g.XC_SUC.HWV=d.HWV,!a&&c&&(g.XC_SUC.TZ=c+""),b.send("{XC_SUC}"+JSON.stringify(g.XC_SUC))):b.send("{XC_ERR}")})})});d.setCommandFunc("setTZ",function(c,b){d.setTimeZoneCompatiable(c.query.data,function(a){a?b.send("{XC_ERR}"):b.send("{XC_SUC}")})});
d.setCmdFunc("setTZ",function(c,b){d.setTimeZoneCompatiable(c.query.data,function(a){a?b(JSON.stringify({XC_ERR:{}})):b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("SendM",function(c,b){if(c.query&&c.query.m&&c.query.cmd){var a=c.query.m,d=c.query.cmd;delete c.query.XC_FNC;delete c.query.m;delete c.query.cmd;var g=null;try{g=require("x.hub.m."+a+".js")}catch(e){}g&&g.executeCommand?g.executeCommand(c.query,d,function(){b('{"XC_SUC":{}}')}):b('{"XC_ERR":{"code":"000000","msg":"internal error"}}')}else b('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});
d.setCmdFunc("GetM",function(c,b){if(c.query&&c.query.m){var a=c.query.m;delete c.query.XC_FNC;delete c.query.m;var d=null;try{d=require("x.hub.m."+a+".js")}catch(g){}d&&d.updateStates?d.updateStates(c.query,function(a){a?b('{"XC_SUC":'+JSON.stringify(a)+"}"):b('{"XC_SUC":{}}')}):b('{"XC_ERR":{"code":"000000","msg":"internal error"}}')}else b('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});d.setCmdFunc("SendRM",function(c,b){require("x.logger.js").getLogger("CloudRemoteAccess").log("trace",
"execute command:"+JSON.stringify(c.query));c.query?require("x.hub.commandman.js").commandHandler2.executeCommandWithIdx(c.query.device,c.query.gateway,c.query.command,function(a){a.error?b('{"XC_ERR":{"code":"000000","msg":"'+a.error.message+'"}}'):b('{"XC_SUC":{}}')}):b('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});d.setCmdFunc("GetRM",function(c,b){require("x.logger.js").getLogger("CloudRemoteAccess").log("trace","get states:"+JSON.stringify(c.query));c.query?require("x.hub.commandman.js").commandHandler2.getStateWithIdx(c.query.device,
c.query.gateway,c.query.status,function(a){a.error?b('{"XC_ERR":{"code":"000000","msg":"'+a.error.message+'"}}'):b('{"XC_SUC":'+JSON.stringify(a.data)+"}")}):b('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});d.setCmdFunc("DoMacroRM",function(c,b){require("x.logger.js").getLogger("CloudRemoteAccess").log("trace","execute macro:"+JSON.stringify(c.query));c.query?require("x.hub.macroman.js").executeWithIdx2(c.query.groupIdx,c.query.macroIdx,function(a){a.error?b('{"XC_ERR":{"code":"000000","msg":"'+
a.error.message+'"}}'):b('{"XC_SUC":{}}')}):b('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});d.setCmdFunc("GetTask",function(c,b){require("x.hub.taskman.js").doWebRequest("Read",c,b)});d.setCmdFunc("CreateTask",function(c,b){require("x.hub.taskman.js").doWebRequest("Create",c,b)});d.setCmdFunc("UpdateTask",function(c,b){require("x.hub.taskman.js").doWebRequest("Update",c,b)});d.setCmdFunc("DeleteTask",function(c,b){require("x.hub.taskman.js").doWebRequest("Delete",c,b)});d.setCmdFunc("DoTask",
function(c,b){require("x.hub.taskman.js").doWebRequest("Do",c,b)});d.setCmdFunc("CancelTask",function(c,b){require("x.hub.taskman.js").doWebRequest("Cancel",c,b)});d.setCmdFunc("IsTaskRunning",function(c,b){require("x.hub.taskman.js").doWebRequest("isRunning",c,b)});d.setCmdFunc("SetTaskActive",function(c,b){require("x.hub.taskman.js").doWebRequest("SetTaskActive",c,b)});d.setCmdFunc("ToggleTaskActive",function(c,b){require("x.hub.taskman.js").doWebRequest("ToggleTaskActive",c,b)});d.setCmdFunc("SetAlarmActive",
function(c,b){require("x.hub.taskman.js").doWebRequest("SetAlarmActive",c,b)});d.setCmdFunc("SetAlarmDelay",function(c,b){require("x.hub.taskman.js").doWebRequest("SetAlarmDelay",c,b)});d.setCmdFunc("GetAlarmInfo",function(c,b){require("x.hub.taskman.js").doWebRequest("GetAlarmInfo",c,b)});d.setCmdFunc("SelectAlarmTask",function(c,b){require("x.hub.taskman.js").doWebRequest("SelectAlarmTask",c,b)});d.setCmdFunc("SetAlarmPin",function(c,b){require("x.hub.taskman.js").doWebRequest("SetAlarmPin",c,b)});
d.setCmdFunc("GetCloudServer",function(c,b){require("x.hub.taskman.js").doWebRequest("GetCloudServer",c,b)});d.setCmdFunc("SetCloudServer",function(c,b){require("x.hub.taskman.js").doWebRequest("SetCloudServer",c,b)});d.setCmdFunc("GetCloudDeviceTriggerGateway",function(c,b){require("x.hub.taskman.js").doWebRequest("GetCloudDeviceTriggerGateway",c,b)});d.setCmdFunc("RehauPinChallenge",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauPinChallenge",c,b)});d.setCmdFunc("RehauGetAlarmInfo",
function(c,b){require("x.hub.taskman.js").doWebRequest("RehauGetAlarmInfo",c,b)});d.setCmdFunc("RehauSetAlarmDelay",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauSetAlarmDelay",c,b)});d.setCmdFunc("RehauSetDoorAlarmDelay",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauSetDoorAlarmDelay",c,b)});d.setCmdFunc("RehauSetNewPin",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauSetNewPin",c,b)});d.setCmdFunc("RehauSelectAssociateTaskAlarm",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauSelectAssociateTaskAlarm",
c,b)});d.setCmdFunc("RehauSelectAssociateTaskPreAlarm",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauSelectAssociateTaskPreAlarm",c,b)});d.setCmdFunc("RehauSetAlarmActive",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauSetAlarmActive",c,b)});d.setCmdFunc("RehauAddAlarmKey",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauAddAlarmKey",c,b)});d.setCmdFunc("RehauUpdateAlarmKey",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauUpdateAlarmKey",c,b)});
d.setCmdFunc("RehauDeleteAlarmKey",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauDeleteAlarmKey",c,b)});d.setCmdFunc("RehauAddAlarmDoor",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauAddAlarmDoor",c,b)});d.setCmdFunc("RehauUpdateAlarmDoor",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauUpdateAlarmDoor",c,b)});d.setCmdFunc("RehauDeleteAlarmDoor",function(c,b){require("x.hub.taskman.js").doWebRequest("RehauDeleteAlarmDoor",c,b)});d.setCmdFunc("RehauSetAlarmConfirmation",
function(c,b){require("x.hub.taskman.js").doWebRequest("RehauSetAlarmConfirmation",c,b)});d.setCmdFunc("AddEventListener",function(c,b){var a=c.query.data;if(a&&a.sys){var d=require("x.hub.moduleman.js").modulemanager.getModule(a.sys);d?d.addStateDevice(a,function(a){a.error?b(JSON.stringify({XC_ERR:{code:"000000",msg:a.error.message}})):b(JSON.stringify({XC_SUC:{}}))}):b(JSON.stringify({XC_ERR:{code:"000000",msg:"no module for sys:"+a.sys}}))}else b(JSON.stringify({XC_ERR:{code:"000000",msg:"device format invalid"}}))});
d.setCmdFunc("GetMetaInfo",function(c,b){var a=require("x.hub.taskman.js").taskManager,d={XC_SUC:{version:String(a.version),deploy:{time:localStorage.getItem("x.hub.hubsyncman.SyncManager.TIMESTAMP"),userid:localStorage.getItem("x.hub.hubsyncman.SyncManager.USERID"),appid:localStorage.getItem("x.hub.hubsyncman.SyncManager.APPID")}}};"A1"==global.HARDWARE_VERSION&&(d.XC_SUC.trial=0!=a._mode%31);b(JSON.stringify(d))});d.setCmdFunc("ConfigSiegeniaWindow",function(c,b){require("x.hub.m.enocean.js").configSiegeniaWindow(null,
null,function(a){a.error?b(JSON.stringify({XC_ERR:{message:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("AddEnoceanVirtualDevice",function(c,b){require("x.hub.m.enocean.js").generateVirtualDevice(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("AddEnoceanDevice",function(c,b){require("x.hub.m.enocean.js").addSensor(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,
code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("UpdateEnoceanDevice",function(c,b){require("x.hub.m.enocean.js").updateSensor(c.query.address,c.query.device,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("TeachinEnocean",function(c,b){require("x.hub.m.enocean.js").teachinDevice(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});
d.setCmdFunc("GetUSBDevices",function(c,b){require("x.hub.peripheralman.js").getUSBDevices(function(a){a.error?b(JSON.stringify({XC_ERR:{message:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("SetLogger",function(c,b){c.query.level?(require("x.logger.js").setLevel(c.query.level,c.query.tag),b(JSON.stringify({XC_SUC:{}}))):b(JSON.stringify({XC_ERR:{message:"parameter invalid",code:"010001"}}))});d.setCmdFunc("GetLogger",function(c,b){var a=require("x.logger.js").getAll();
b(JSON.stringify({XC_SUC:a}))});d.setCmdFunc("DummyEvent",function(c,b){var a=c.query.data;require("x.hub.eventbus.js").emit("status",a);b(JSON.stringify({XC_SUC:{}}))});d.setCmdFunc("DummyTaskmanEvent",function(c,b){var a=c.query.event,d=c.query.meta;require("x.hub.taskman.js").onStatusEvt(a,d);b(JSON.stringify({XC_SUC:{}}))});d.setCmdFunc("GetZwaveStates",function(c,b){var a=c.query.devices;require("x.hub.m.zwave.js").__getStates(a,function(a){a.error?b(JSON.stringify({XC_ERROR:{message:a.error.message,
code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("DirectEvent",function(c,b){var a=c.query.event,d=c.query.tag;require("x.hub.m.gateway.js")._onEvent(a,{address:"http call"},d);b(JSON.stringify({XC_SUC:{}}))});d.setCmdFunc("GetHmMonitors",function(c,b){require("x.hub.m.hm.js").getMonitorStates(function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("GetHmDevices",function(c,b){require("x.hub.m.hm.js").getAllDevices(function(a){a.error?
b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("EnOceanSDK",function(c,b){require("x.hub.m.enocean.js")._doSDK(c.query.data,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ResetEnOceanSenderID",function(c,b){require("x.hub.m.enocean.js").resetDefaultSenderID(function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):
b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("SetRehauInoventHumidityAccessory",function(c,b){require("x.hub.m.enocean.js").setInoventHumidityAccessory(c.query.inoventID,c.query.humiditySensorID,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("SetRehauInoventCo2Accessory",function(c,b){require("x.hub.m.enocean.js").setInoventCo2Accessory(c.query.inoventID,c.query.co2SensorID,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,
code:a.error.code}})):b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("GetRehauInoventAccessories",function(c,b){require("x.hub.m.enocean.js").getInoventAccessories(c.query.inoventID,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("RawEnoceanPacket",function(c,b){var a=c.query.data;require("x.hub.m.enocean.js").__simulateRawEnoceanPacket(a,function(a){b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("SendESPFrame",
function(c,b){var a=c.query.type,d=c.query.data,g=c.query.optData,e=c.query.requireResponse;require("x.hub.m.enocean.js").__sendEspFrame(a,d,g,e,function(a){a.error?b(JSON.stringify({XC_ERROR:{message:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ZWaveInclusion",function(c,b){require("x.hub.m.zway.js").learnDevice(c.query,function(a,b,c){console.log("learn zwave procedure",a,b,c)},function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):
b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ZWaveExclusion",function(c,b){require("x.hub.m.zway.js").removeDevice(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ZWaveListDevices",function(c,b){require("x.hub.m.zway.js").listDevices(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ZWaveListInterviewResults",
function(c,b){require("x.hub.m.zway.js").listInterviewResults(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ZWaveResetController",function(c,b){require("x.hub.m.zway.js").resetController(function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ZWaveSetDeviceSetting",function(c,b){require("x.hub.m.zway.js").setDeviceSetting(c.query.deviceID,
c.query.setting,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ZWaveGetDeviceSetting",function(c,b){require("x.hub.m.zway.js").getDeviceSetting(c.query.deviceID,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ZWaveForcePollDevices",function(c,b){var a=require("x.hub.m.zway.js");if(c.query.deviceIDs){var d=c.query.deviceIDs.split(",");
a.forcePoll(d,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})}else b(JSON.stringify({XC_ERR:{msg:"no device id list",code:"000000"}}))});d.setCmdFunc("GetKnxIpGateways",function(c,b){require("x.hub.m.knx.js").getIPGateways(function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("AddKnxIpGateway",function(c,b){var a=c.query.data;require("x.hub.m.knx.js").addIPGateway(a,
function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("UptateKnxIpGateway",function(c,b){var a=c.query.data;require("x.hub.m.knx.js").updateIPGateway(a,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("DeleteKnxIpGateway",function(c,b){var a=c.query.data;require("x.hub.m.knx.js").deleteIPGateway(a,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,
code:a.error.code}})):b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("GetKnxDevices",function(c,b){require("x.hub.m.knx.js").getDevices(function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("AddKnxDevice",function(c,b){var a=c.query.data;require("x.hub.m.knx.js").addDevice(a,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("UptateKnxDevice",
function(c,b){var a=c.query.data;require("x.hub.m.knx.js").updateDevice(a,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("DeleteKnxDevice",function(c,b){var a=c.query.data;require("x.hub.m.knx.js").deleteDevice(a,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("ListKnxMonitors",function(c,b){require("x.hub.m.knx.js").listMonitors(function(a){a.error?
b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("SearchKnxIpGateways",function(c,b){require("x.hub.m.knx.js").searchKNXGateway(function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("DoZigbeeNativeCommandRaw",function(c,b){require("x.hub.m.zigbee.js").executeCommandNativeRaw(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,
code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCmdFunc("ListZigbeeDevices",function(c,b){require("x.hub.m.zigbee.js").listDevices(c.query,function(a){a.error?b(JSON.stringify({XC_ERR:{msg:a.error.message,code:a.error.code}})):b(JSON.stringify({XC_SUC:a.data}))})});d.setCommandFunc("AddGroup",function(c,b){b.send("{XC_SUC}")});d.setCommandFunc("setTaskDeviceAddress",function(c,b){var a=c.query.device,d=c.query.address;a&&d&&devices[a]&&(devices[a].address=d,localStorage&&localStorage.setItem("xnm.aio.xhub.siegenia."+
a,d));b.send("{XC_SUC}")});d.setCommandFunc("getTaskDeviceAddress",function(c,b){var a="{XC_ERR}",d=c.query.device;d&&devices[d]&&(a='{XC_SUC}{"address":"'+devices[d].address+'"}');b.send(a)});d.setCommandFunc("setAlarmGroup",function(c,b){for(var a in taskmanager._tasks)80<=a&&(taskmanager._tasks[a].active="1"==c.query.active?!0:!1);b.send("{XC_SUC}")});d.setCommandFunc("DelGroup",function(c,b){var a="{XC_ERR}",d=parseInt(c.query.id),g=parseInt(c.query.nid);taskmanager._tasks[d]&&c.query.nid&&(taskmanager._tasks[g]=
taskmanager._tasks[d],delete taskmanager._tasks[d],a="{XC_SUC}");b.send(a)});d.setCommandFunc("saveGroup",function(c,b){var a="{XC_ERR}",d=parseInt(c.query.id);taskmanager._tasks[d]&&(taskmanager._tasks[d].active="1"==c.query.active?!0:!1,a="{XC_SUC}");b.send(a)});d.setCommandFunc("GetAll",function(c,b){var a="",d=1,g=1,e;for(e in taskmanager._tasks){var f=taskmanager._tasks[e],h="0";f.active&&(h="1");for(var m="",p="",l=0,l=0;l<f.trigger.length;l++)p+=XC.getHexVal(d,2),""!=a&&(a+=","),a+='{"sys":"EVENT","id":"'+
XC.getHexVal(d++,2)+'","code":""}';for(l=0;l<f.action.length;l++)m+=XC.getHexVal(g,2),""!=a&&(a+=","),a+='{"sys":"ACTION","id":"'+XC.getHexVal(g++,2)+'","code":""}';""!=a&&(a+=",");a+='{"sys":"GROUP","id":"'+XC.getHexVal(e,2)+'","name":"'+f.name+'","active":"'+h+'","triggerids":"'+p+'","actionids":"'+m+'"}'}b.send("{XC_SUC}["+a+"]")});return d}
function _setupAutomationManagerMode(d){function e(b){var a=require("crypto"),c=new Buffer("fO4gAeDjh4HwO0D8+/9Bfw==","base64"),d=new Buffer("+ubtPBJR9uejkjXiN6c1Bg==","base64"),a=a.createDecipheriv("aes-128-cbc",c,d);a.setAutoPadding(!0);b=[a.update(new Buffer(b,"base64"))];b.push(a.final());return Buffer.concat(b).toString("utf8")}function k(b){if(!b)return 31*f(23,76)+2;try{var a=e(b);if(10>a.length||"t"!=a.charAt(0)||"a"!=a.charAt(2)||"k"!=a.charAt(9))return 31*f(23,76)+2;var c=a.charAt(1)+""+
a.charAt(5)+""+a.charAt(6);return 31*parseInt(c)}catch(d){return 31*f(23,76)+2}}function f(b,a){b=Math.ceil(b);a=Math.floor(a);return Math.floor(Math.random()*(a-b))+b}var h=require("x.hub.taskman.js"),c=localStorage.getItem("info");h.taskManager.version=global.TASKMANAGER_VERSION;h.taskManager._mode=c?k(c):k();c=require("body-parser");d._app.use("/xhub/activate/do",c.text({limit:"100kb"}));d._app.post("/xhub/activate/req",function(b,a){global.TMP_TOKEN=f(1,5E3);setTimeout(function(){global.TMP_TOKEN=
null},3E4);a.json({status:"success",data:global.TMP_TOKEN})});d._app.post("/xhub/activate/do",function(b,a){if(global.TMP_TOKEN)if(b.body)try{var c=e(b.body),d=""+global.TMP_TOKEN,f=c.substr(c.length-d.length);c.length<d.length||f!=d?a.json({status:"fail",message:"invalid token",code:0}):(localStorage.setItem("info",b.body),h.taskManager._mode=k(b.body),a.json({status:"success"}))}catch(n){a.json({status:"fail",message:"invalid request body",code:0})}else a.json({status:"fail",message:"no request body",
code:0});else a.json({status:"fail",message:"token expired",code:0})})}
function _setupLogger(){var d=require("fs-extra"),e=fm.fileManager;require("x.logger.js").setFile(e.getLogFile());require("x.logger.js").setLogFolder(e.getUserLogPath());require("x.logger.js")._fileMaxSize=2048;require("x.logger.js").setLevel("info");require("x.logger.js").setLevel("trace","x.core.debugf");require("x.logger.js").setTagFile("CloudRemoteAccess","cloud_access.log");d.ensureFileSync(path.resolve(e.getUserLogPath(),"v5p_taskmanager.log"));require("x.logger.js").setTagFile("x.hub.taskman",
"v5p_taskmanager.log");require("x.logger.js").setLogToConsole(!1,"x.hub.taskman");d.ensureFileSync(path.resolve(e.getUserLogPath(),"v5p_homematic.log"));require("x.logger.js").setTagFile("x.hub.m.hm","v5p_homematic.log");require("x.logger.js").setTagFile("xnm.aio.hm","v5p_homematic.log");require("x.logger.js").setLogToConsole(!1,"x.hub.m.hm");require("x.logger.js").setLogToConsole(!0,"x.hub.m.hm.Manager");require("x.logger.js").setLogToConsole(!1,"xnm.aio.hm");global.LOAD_MODULES&&-1!=global.LOAD_MODULES.indexOf("enocean")&&
(d.ensureFileSync(path.resolve(e.getUserLogPath(),"v5p_enocean.log")),require("x.logger.js").setTagFile("x.hub.m.enocean","v5p_enocean.log"),require("x.logger.js").setLogToConsole(!1,"x.hub.m.enocean"));global.LOAD_MODULES&&-1!=global.LOAD_MODULES.indexOf("zigbee")&&(d.ensureFileSync(path.resolve(e.getUserLogPath(),"v5p_zigbee.log")),require("x.logger.js").setTagFile("x.hub.m.zigbee","v5p_zigbee.log"),require("x.logger.js").setLogToConsole(!1,"x.hub.m.zigbee"));global.LOAD_MODULES&&-1!=global.LOAD_MODULES.indexOf("zway")&&
(d.ensureFileSync(path.resolve(e.getUserLogPath(),"v5p_zwave.log")),require("x.logger.js").setTagFile("x.hub.m.zway","v5p_zwave.log"),require("x.logger.js").setLogToConsole(!1,"x.hub.m.zway"),require("x.logger.js").setLogToConsole(!1,"x.hub.m.zway.Handler"));global.LOAD_MODULES&&-1!=global.LOAD_MODULES.indexOf("knx")&&(d.ensureFileSync(path.resolve(e.getUserLogPath(),"v5p_knx.log")),require("x.logger.js").setTagFile("x.hub.m.knx","v5p_knx.log"),require("x.logger.js").setTagFile("xnm.aio.knx","v5p_knx.log"),
require("x.logger.js").setLogToConsole(!1,"x.hub.m.knx"),require("x.logger.js").setLogToConsole(!1,"xnm.aio.knx"),require("x.logger.js").setLogToConsole(!0,"x.hub.m.knx.MonitorManager"));d.ensureFileSync(path.resolve(e.getUserLogPath(),"v5p_aiogateway.log"));require("x.logger.js").setTagFile("x.hub.m.gateway","v5p_aiogateway.log");require("x.logger.js").setTagFile("x.hub.m.gateway","v5p_aiogateway.log");require("x.logger.js").setLogToConsole(!1,"x.hub.m.gateway");d.ensureFileSync(path.resolve(e.getUserLogPath(),
"v5p_rf_st.log"));require("x.logger.js").setTagFile("x.hub.v5.USBSerial","v5p_rf_st.log");require("x.logger.js").setLogToConsole(!1,"x.hub.v5.USBSerial")}
function _setupDebugSite(d){var e=require("x.hub.fileman.js"),k=e.fileManager,f=require("express"),h=require("path"),c=require("ws").Server,b=h.join(__dirname,"site");d._app.use("/debug",f.static(b+"/debug"));d._app.use("/js",f.static(b+"/js"));this._wss=new c({server:d._httpserver,path:"/debug/tracker/ws"});this._wss.on("error",function(a){console.log("web socket server error:"+a.stack)}.bind(this));this._wss.on("connection",function(a){a.__watchDog=setTimeout(function(){a.close()},6E4);a.on("error",
function(b){console.log("web socket error:"+b.stack);a.close()}.bind(this));a.on("close",function(){if(a.__tags){var b=require("x.logger.js");a.__tags.forEach(function(c){b.removeLogTracker(c,a.__tracker)})}a.__tail&&a.__tail.unwatch()});a.on("message",function(b,c){try{var d=JSON.parse(b);if("main"==d.system){var e=new (require("tail").Tail)(h.resolve(k.getUserLogPath(),"v5plus_daemon"));a.__tail=e;e.on("line",function(b){a.send(b+"\r\n")});e.on("error",function(a){console.log("ERROR: ",a)})}else{e=
[];switch(d.system){case "homematic":e=["x.hub.m.hm","xnm.aio.hm"];break;case "knx":e=["x.hub.m.knx","xnm.aio.knx"];break;case "zwave":e=["x.hub.m.zway"];break;case "enocean":e=["x.hub.m.enocean"];break;case "zigbee":e=["x.hub.m.zigbee"];break;case "aio":e=["x.hub.m.gateway"];break;case "taskmanager":e=["x.hub.taskman"];break;case "script":e=["x.hub.scriptman"];break;case "rf":e=["x.hub.v5.USBSerial"]}if(0<e.length){a.__watchDog&&(clearTimeout(a.__watchDog),a.__watchDog=null);a.__tags=e;a.__tracker=
function(b){a.send(b+"\r\n")};var f=require("x.logger.js");e.forEach(function(b){f.setLogTracker(b,a.__tracker)})}}}catch(m){a.send(JSON.stringify({error:m.message})),a.close()}}.bind(this))}.bind(this));d._app.get("/debug/tracker/log",function(a,b){var c;switch(a.query.system){case "taskmanager":c="v5p_taskmanager.log";break;case "homematic":c="v5p_homematic.log";break;case "knx":c="v5p_knx.log";break;case "zigbee":c="v5p_zigbee.log";break;case "zwave":c="v5p_zwave.log";break;case "enocean":c="v5p_enocean.log";
break;case "aio":c="v5p_aiogateway.log";break;case "rf":c="v5p_rf_st.log";break;case "main":c="v5plus_daemon";break;default:b.status(404).send("system unknow")}c=h.join(e.fileManager.getUserLogPath(),c);b.sendFile(c)});b=h.join(__dirname,"site/debug/enocean");d._app.use("/debug/enocean/tracker",f.static(b));b=h.join(__dirname,"resources");d._app.use("/resources",f.static(b));this._wss=new c({server:d._httpserver,path:"/debug/enocean/ws"});this._wss.on("error",function(a){console.log("web socket server error:"+
a.stack)}.bind(this));this._wss.on("connection",function(a){console.log("web socket connected");var b={onFrame:function(b,c){a.send("+++++++++++++++++++++++++++++++++\r\n");a.send("EnOcean Frame:");a.send(c+"\r\n");a.send(JSON.stringify(b.toJSON())+"\r\n");a.send("+++++++++++++++++++++++++++++++++\r\n")},onTelegram:function(b){a.send("########################################################\r\n");a.send("EnOcean Telegram:\r\n");a.send(JSON.stringify(b.toJSON())+"\r\n");a.send("########################################################\r\n")},
onResolveEvents:function(b,c){a.send("===============================\r\n");a.send("Resolved Events from:"+b+"\r\n");c.forEach(function(b){a.send(JSON.stringify(b)+"\r\n")});a.send("===============================\r\n")}},c=require("x.hub.m.enocean.js");c.__addTelegramTracker(b);a.on("error",function(b){console.log("web socket error:"+b.stack);a.close()}.bind(this));a.on("close",function(){c.__removeTelegramTracker(b)});a.on("message",function(a,b){}.bind(this))}.bind(this));this._wss2=new c({server:d._httpserver,
path:"/siegenia/enocean/windowconfig"});this._wss2.on("error",function(a){console.log("web socket server error:"+a.stack)}.bind(this));this._wss2.on("connection",function(a){var b=require("x.hub.m.enocean.js");a.__watchDog=setTimeout(function(){a.close()},3E5);a.on("error",function(c){console.log("web socket error:"+c.stack);b._siegeniaHandler.stopCalibateWindow();a.close()}.bind(this));a.on("close",function(){clearTimeout(a.__watchDog);b._siegeniaHandler.stopCalibateWindow()});a.on("message",function(c,
d){try{var e=JSON.parse(c);"start"==e.command&&(b._siegeniaHandler.startCalibateWindow(e.windowID,function(b,c,d){b?a.send(JSON.stringify({error:b.message})):a.send(JSON.stringify({windowID:c,message:d}))}),b._siegeniaHandler.configWindow(e.params,e.windowID,function(b){b&&a.send(JSON.stringify({error:b.message,code:b.code}))}))}catch(f){a.send(JSON.stringify({error:f.message}))}}.bind(this))}.bind(this));this._wss3=new c({server:d._httpserver,path:"/zwave2/inclusion"});this._wss3.on("error",function(a){console.log("web socket server zwaveinclusion error:"+
a.stack)}.bind(this));this._wss3.on("connection",function(a){var b=require("x.hub.m.zway.js");a.__watchDog=setTimeout(function(){a.close()},3E5);a.on("error",function(b){console.log("web socket error:"+b.stack);a.close()}.bind(this));a.on("close",function(){clearTimeout(a.__watchDog)});a.on("message",function(c,d){try{var e=JSON.parse(c);"start"==e.command?b.learnDevice(null,function(b,c,d){a.send(JSON.stringify({progress:b,subprogress:c,message:d}))},function(b){b.error?a.send(JSON.stringify({finish:!0,
error:b.error.message,code:b.error.code,device:b.data})):a.send(JSON.stringify({finish:!0,device:b.data}));a.close()}):"updateInterview"==e.command&&(e.address?b.updateInterview(e.address,e.instanceID,e.commandClassID,function(b,c,d){a.send(JSON.stringify({progress:b,subprogress:c,message:d}))},function(b){b.error?a.send(JSON.stringify({finish:!0,error:b.error.message,code:b.error.code,device:b.data})):a.send(JSON.stringify({finish:!0,device:b.data}));a.close()}):a.send(JSON.stringify({finish:!0,
error:"no address parameter",code:"08999"})))}catch(f){a.send(JSON.stringify({error:f.message}))}}.bind(this))}.bind(this));this._wss4=new c({server:d._httpserver,path:"/taskman/tracker"});this._wss4.on("error",function(a){console.log("web socket server error:"+a.stack)}.bind(this));this._wss4.on("connection",function(a){var b=require("url").parse(a.upgradeReq.url),b=require("querystring").parse(b.query);b.taskID||a.close();a.__taskID=b.taskID;a.__watchDog=setTimeout(function(){a.close()},6E4);a.__tmListener=
function(b){a.send(b+"\r\n")};var c=require("x.hub.taskman.js");c.startTaskTrace(a.__taskID,a.__tmListener,function(b){b&&b.error&&(a.send(JSON.stringify({error:b.error.message})),a.close())});a.on("error",function(b){console.log("web socket error:"+b.stack);a.close()}.bind(this));a.on("close",function(){a.__taskID&&a.__tmListener&&c.stopTaskTrace(a.__taskID,a.__tmListener)});a.on("message",function(b,c){try{JSON.parse(b).alive&&(a.__watchDog&&(clearTimeout(a.__watchDog),a.__watchDog=null),a.__watchDog=
setTimeout(function(){a.close()},6E4))}catch(d){a.send(JSON.stringify({error:d.message})),a.close()}}.bind(this))}.bind(this))}_loadCompilerConfig();_loadProgrammEnv();_loadConfigFile();_loadRuntimeConfig();var fm=require("x.hub.fileman.js");
fm.init("A1"==global.HARDWARE_VERSION?"NEO Server":"v5plus",function(){var d=fm.fileManager,e=require("node-localstorage").LocalStorage;if("EA"==global.HARDWARE_VERSION)fs.existsSync("./data")||fs.mkdirSync("./data"),localStorage=new e("./data/localstorage"),fs.existsSync("./localstorage")&&fs.rmdirRecursiveSync("./localstorage");else if("A1"==global.HARDWARE_VERSION&&!hasLocalStorage)try{localStorage=new e(d.getUserRootDataPath()+path.sep+"localstorage")}catch(k){}_setupLogger();var f=_setupServer();
_setupDebugSite(f);"EA"==global.HARDWARE_VERSION&&"A20"==global.PLATFORM&&(console.log((new Date).toString()+" ===========> LED Start Sequence"),e=new miot.STMUpdater,e.hostType=f.hostType,e.resetST(),setTimeout(function(){f.startSTM(function(c){f.doSTMCommand("XC_FNC=SendSC&type=RGB&data=040305")})},500),0==v5.Native.checkResetPin()&&(console.log((new Date).toString()+" ===========> reset button pressed, start safe mode"),global.SAFE_MODE=!0));require("x.hub.deviceman.js").init(f._app,d,function(){require("x.hub.macroman.js").init(f._app,
d);require("x.hub.scriptman.js").init(f._app,f._httpserver);require("x.hub.commandman.js").init(f._app);var c=require("x.hub.taskman.js");global.SAFE_MODE&&(console.log("!!! run task manager in safe mode"),c.lock());c.init();require("x.hub.sysvarman.js").init(f._app,d);"A1"==global.HARDWARE_VERSION&&_setupAutomationManagerMode(f);f.startWebserver(global.WEB_SERVER_PORT,function(){"EA"==global.HARDWARE_VERSION&&"A20"==global.PLATFORM&&f.doSTMCommand("XC_FNC=SendSC&type=RGB&data=0400")});f.enableCloudConnect(new v5.CloudConnect);
"A20"==global.PLATFORM&&"EA"==global.HARDWARE_VERSION&&v5.Native.watchResetPin(f,function(b){XC.debugf("RESET: "+b);"reboot"==b?f.restart(0):"network"==b?v5.Native.resetNetwork(function(){f.restart(0)}):"passwords"==b?v5.reset(f,b,function(){f.restart(0)}):"factory"==b&&v5.reset(f,b,function(){v5.Native.resetHM(function(){v5.Native.resetZway(function(){v5.Native.resetZigbee(function(){v5.Native.resetNetwork(function(){f.restart(0)})})})})})})});"A20"==global.PLATFORM&&"EA"==global.HARDWARE_VERSION&&
require("x.hub.datastore.js").init(d);require("x.hub.peripheralman.js").init(f._app,f._httpserver);require("x.hub.hubsyncman.js").init(f._app,d);var h=require("x.hub.moduleman.js");global.LOAD_MODULES.forEach(function(c){h.Modules.push(c)});h.init();h.initModules();e=require("xnm.aio.gateway.js");e._autoSearchInterval&&clearInterval(e._autoSearchInterval)});process.on("uncaughtException",function(d){console.error(d.stack)});
process.on("SIGINT",function(){console.log("Got SIGINT.");-1!=global.LOAD_MODULES.indexOf("knx")?require("x.hub.m.knx.js").clean(function(){console.log("SIGINT callback.");process.exit(1)}):process.exit(1)});process.on("SIGTERM",function(){console.log("Got SIGTERM.");-1!=global.LOAD_MODULES.indexOf("knx")?require("x.hub.m.knx.js").clean(function(){console.log("SIGINT callback.");process.exit(1)}):process.exit(1)});
