var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(d){var l=0;return function(){return l<d.length?{done:!1,value:d[l++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,l,m){if(d==Array.prototype||d==Object.prototype)return d;d[l]=m.value;return d};$jscomp.getGlobal=function(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var l=0;l<d.length;++l){var m=d[l];if(m&&m.Math==Math)return m}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(d,l){var m=$jscomp.propertyToPolyfillSymbol[l];if(null==m)return d[l];m=d[m];return void 0!==m?m:d[l]};
$jscomp.polyfill=function(d,l,m,f){l&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(d,l,m,f):$jscomp.polyfillUnisolated(d,l,m,f))};$jscomp.polyfillUnisolated=function(d,l,m,f){m=$jscomp.global;d=d.split(".");for(f=0;f<d.length-1;f++){var h=d[f];if(!(h in m))return;m=m[h]}d=d[d.length-1];f=m[d];l=l(f);l!=f&&null!=l&&$jscomp.defineProperty(m,d,{configurable:!0,writable:!0,value:l})};
$jscomp.polyfillIsolated=function(d,l,m,f){var h=d.split(".");d=1===h.length;f=h[0];f=!d&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var r=0;r<h.length-1;r++){var b=h[r];if(!(b in f))return;f=f[b]}h=h[h.length-1];m=$jscomp.IS_SYMBOL_NATIVE&&"es6"===m?f[h]:null;l=l(m);null!=l&&(d?$jscomp.defineProperty($jscomp.polyfills,h,{configurable:!0,writable:!0,value:l}):l!==m&&(void 0===$jscomp.propertyToPolyfillSymbol[h]&&($jscomp.propertyToPolyfillSymbol[h]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(h):
$jscomp.POLYFILL_PREFIX+h),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[h],{configurable:!0,writable:!0,value:l})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(d){if(d)return d;var l=function(h,r){this.$jscomp$symbol$id_=h;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:r})};l.prototype.toString=function(){return this.$jscomp$symbol$id_};var m=0,f=function(h){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new l("jscomp_symbol_"+(h||"")+"_"+m++,h)};return f},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(d){if(d)return d;d=Symbol("Symbol.iterator");for(var l="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),m=0;m<l.length;m++){var f=$jscomp.global[l[m]];"function"===typeof f&&"function"!=typeof f.prototype[d]&&$jscomp.defineProperty(f.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return d},"es6",
"es3");$jscomp.iteratorPrototype=function(d){d={next:d};d[Symbol.iterator]=function(){return this};return d};$jscomp.iteratorFromArray=function(d,l){d instanceof String&&(d+="");var m=0,f=!1,h={next:function(){if(!f&&m<d.length){var r=m++;return{value:l(r,d[r]),done:!1}}f=!0;return{done:!0,value:void 0}}};h[Symbol.iterator]=function(){return h};return h};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(l){return l})}},"es6","es3");
var HARDWARE_VERSION="A1",FIRMWARE_VERSION="2.8.0",TASKMANAGER_VERSION="2.8.0",PLATFORM="CCU3",hasLocalStorage=!0;if("undefined"==typeof localStorage||null==localStorage)hasLocalStorage=!1,localStorage={};require("x.core.js");console.log((new Date).toString()+" ===========> started");
var os=require("os"),fs=require("fs"),path=require("path"),async=require("async"),ls=require("node-localstorage").LocalStorage,xhub=require("x.hub.js"),v5=require("x.hub.v5.js"),miot=require("xnm.aio.m10T.js"),pluginManager={init:function(){}},xnm=xnm||{};xnm.aio=xnm.aio||{};xnm.aio.xhub=xnm.aio.xhub||{};global.HARDWARE_VERSION="EA";global.FIRMWARE_VERSION="development";global.TASKMANAGER_VERSION="2.5.3";global.FIRMWARE_BUILD="0000";global.PLATFORM=null;global.NAME=null;global.VID=null;
global.CLOUD_URL="https://webservice.mediola.com";global.CONTROL_SERVER=null;global.LOAD_MODULES=null;global.SYSTEM_ROOT=null;global.DATA_FOLDER=null;global.APP_FOLDER=null;global.LOG_ROOT=null;global.LOG_LEVEL=null;global.WEB_SERVER_PORT=80;global.STM=null;global.HM_CHIP=null;global.HM_CHIP_USERNAME=null;global.HM_CHIP_PASSWORD=null;global.HM_LOCAL_PORT=9099;global.ENOCEAN_PORT=null;global.ZWAVE2_URL=null;global.ZWAVE2_PORT=null;global.ZIGBEE_URL=null;global.MBUS_PORT=null;global.SAFE_MODE=!1;
function _loadCompilerConfig(){"undefined"!=typeof HARDWARE_VERSION&&HARDWARE_VERSION&&(global.HARDWARE_VERSION=HARDWARE_VERSION);"undefined"!=typeof FIRMWARE_VERSION&&FIRMWARE_VERSION&&(global.FIRMWARE_VERSION=FIRMWARE_VERSION);"undefined"!=typeof FIRMWARE_BUILD&&FIRMWARE_BUILD&&(global.FIRMWARE_BUILD=FIRMWARE_BUILD);"undefined"!=typeof TASKMANAGER_VERSION&&TASKMANAGER_VERSION&&(global.TASKMANAGER_VERSION=TASKMANAGER_VERSION);"undefined"!=typeof PLATFORM&&PLATFORM&&(global.PLATFORM=PLATFORM);"undefined"!=
typeof NAME&&NAME&&(global.NAME=NAME);"undefined"!=typeof VID&&VID&&(global.VID=VID);"undefined"!=typeof CLOUD_URL&&CLOUD_URL&&(global.CLOUD_URL=CLOUD_URL);"undefined"!=typeof CONTROL_SERVER&&CONTROL_SERVER&&(global.CONTROL_SERVER=CONTROL_SERVER);"undefined"!=typeof LOAD_MODULES&&LOAD_MODULES&&(global.LOAD_MODULES=LOAD_MODULES)}
function _loadProgrammEnv(){if(process&&process.env){process.env.HARDWARE_VERSION&&(global.HARDWARE_VERSION=process.env.HARDWARE_VERSION);process.env.FIRMWARE_VERSION&&(global.FIRMWARE_VERSION=process.env.FIRMWARE_VERSION);process.env.FIRMWARE_BUILD&&(global.FIRMWARE_BUILD=process.env.FIRMWARE_BUILD);process.env.TASKMANAGER_VERSION&&(global.TASKMANAGER_VERSION=process.env.TASKMANAGER_VERSION);process.env.PLATFORM&&(global.PLATFORM=process.env.PLATFORM);process.env.NAME&&(global.NAME=process.env.NAME);
process.env.VID&&(global.VID=process.env.VID);process.env.SYSTEM_ROOT&&(global.SYSTEM_ROOT=process.env.SYSTEM_ROOT);var d=require("path");process.env.DATA_FOLDER&&(global.DATA_FOLDER=d.isAbsolute(process.env.DATA_FOLDER)?process.env.DATA_FOLDER:d.resolve(__dirname,process.env.DATA_FOLDER));process.env.APP_FOLDER&&(global.APP_FOLDER=d.isAbsolute(process.env.APP_FOLDER)?process.env.APP_FOLDER:d.resolve(__dirname,process.env.APP_FOLDER));process.env.LOG_ROOT&&(global.LOG_ROOT=d.isAbsolute(process.env.LOG_ROOT)?
process.env.LOG_ROOT:d.resolve(__dirname,process.env.LOG_ROOT))}}function _loadConfigFile(){function d(f){if(f)for(var h in f)f.hasOwnProperty(h)&&(global[h]="DATA_FOLDER"==h||"APP_FOLDER"==h||"LOG_ROOT"==h?path.isAbsolute(f[h])?f[h]:path.resolve(__dirname,f[h]):f[h])}function l(){try{var f=require("./package.json");f&&d(f.config)}catch(h){}}function m(){try{var f=require("./config.json");d(f)}catch(h){}}switch(global.HARDWARE_VERSION){case "A1":l();break;case "EA":case "CA":m()}}
function _loadRuntimeConfig(){switch(global.HARDWARE_VERSION){case "A1":if(null==global.PLATFORM)switch(os.platform()){case "darwin":global.PLATFORM="MAC";break;case "win32":global.PLATFORM="WIN";break;default:global.PLATFORM="LINUX"}null==global.NAME&&(global.NAME="NEO Server");null==global.VID&&(global.VID=null);null==global.CLOUD_URL&&(global.CLOUD_URL="https://webservice.mediola.com");null==global.CONTROL_SERVER&&(global.CONTROL_SERVER="v5ws.mediola.com");null==global.LOAD_MODULES&&(global.LOAD_MODULES=
["knx","sonos"]);null==global.DATA_FOLDER&&(global.DATA_FOLDER=null);null==global.APP_FOLDER&&(global.APP_FOLDER=null);null==global.LOG_ROOT&&(global.LOG_ROOT=null);null==global.LOG_LEVEL&&(global.LOG_LEVEL="fatal");null==global.WEB_SERVER_PORT&&(global.WEB_SERVER_PORT=8088);null==global.HM_CHIP&&(global.HM_CHIP=null);null==global.HM_LOCAL_PORT&&(global.HM_LOCAL_PORT=9099);null==global.ENOCEAN_PORT&&(global.ENOCEAN_PORT=null);null==global.ZWAVE2_URL&&(global.ZWAVE2_URL=null);null==global.ZWAVE2_PORT&&
(global.ZWAVE2_PORT=null);null==global.ZIGBEE_URL&&(global.ZIGBEE_URL=null);null==global.STM&&(global.STM=null);break;case "EA":null==global.PLATFORM&&(global.PLATFORM="A20");null==global.NAME&&(global.NAME="AIO GATEWAY V5+");null==global.VID&&(global.VID=null);null==global.CLOUD_URL&&(global.CLOUD_URL="https://webservice.mediola.com");null==global.CONTROL_SERVER&&(global.CONTROL_SERVER="v5ws.mediola.com");null==global.LOAD_MODULES&&(global.LOAD_MODULES=["enocean","zway","knx","zigbee","sonos"]);
null==global.DATA_FOLDER&&(global.DATA_FOLDER=path.resolve(__dirname,"./data"));null==global.APP_FOLDER&&(global.APP_FOLDER=path.resolve(__dirname,"./"));null==global.LOG_ROOT&&(global.LOG_ROOT="/var/log");null==global.LOG_LEVEL&&(global.LOG_LEVEL="fatal");null==global.WEB_SERVER_PORT&&(global.WEB_SERVER_PORT=80);null==global.HM_CHIP&&(global.HM_CHIP="127.0.0.1");null==global.HM_LOCAL_PORT&&(global.HM_LOCAL_PORT=9099);null==global.ENOCEAN_PORT&&(global.ENOCEAN_PORT=null);null==global.ZWAVE2_URL&&
(global.ZWAVE2_URL="127.0.0.1");null==global.ZWAVE2_PORT&&(global.ZWAVE2_PORT=9E3);null==global.ZIGBEE_URL&&(global.ZIGBEE_URL="127.0.0.1");if(!global.STM)switch(global.PLATFORM){case "MAC":global.STM=null;break;case "WIN":global.STM=null;break;case "A20":global.STM="/dev/ttyS2";break;case "PI2":global.STM="/dev/spidev0.1";break;default:global.STM="/dev/ttyACM0"}break;case "CA":if(null==global.PLATFORM&&(global.PLATFORM="PI-CM3+"),null==global.NAME&&(global.NAME="AIO GATEWAY V6+"),null==global.VID&&
(global.VID=null),null==global.CLOUD_URL&&(global.CLOUD_URL="https://webservice.mediola.com"),null==global.CONTROL_SERVER&&(global.CONTROL_SERVER="v6p-ccs.mediola.com"),null==global.LOAD_MODULES&&(global.LOAD_MODULES=["enocean","zway","knx","sonos","mbus"]),null==global.DATA_FOLDER&&(global.DATA_FOLDER=path.resolve(__dirname,"./data")),null==global.APP_FOLDER&&(global.APP_FOLDER=path.resolve(__dirname,"./")),null==global.LOG_ROOT&&(global.LOG_ROOT="/var/log"),null==global.LOG_LEVEL&&(global.LOG_LEVEL=
"fatal"),null==global.WEB_SERVER_PORT&&(global.WEB_SERVER_PORT=80),null==global.HM_CHIP&&(global.HM_CHIP=null),null==global.HM_LOCAL_PORT&&(global.HM_LOCAL_PORT=9099),null==global.ENOCEAN_PORT&&(global.ENOCEAN_PORT=null),null==global.ZWAVE2_URL&&(global.ZWAVE2_URL="127.0.0.1"),null==global.ZWAVE2_PORT&&(global.ZWAVE2_PORT=9E3),null==global.ZIGBEE_URL&&(global.ZIGBEE_URL="127.0.0.1"),!global.STM)switch(global.PLATFORM){case "PI-CM3+":global.STM="/dev/ttyAMA0";break;default:global.STM="/dev/ttyACM0"}}"undefined"!=
typeof global.CONTROL_SERVER&&global.CONTROL_SERVER&&(require("x.hub.v5.js").CloudConnect.prototype.CLOUD_SERVER=global.CONTROL_SERVER);"undefined"!=typeof global.CLOUD_URL&&global.CLOUD_URL&&(require("x.hub.taskman.js").Cloud.prototype.URL=global.CLOUD_URL);"undefined"!=typeof global.TASKMANAGER_VERSION&&global.TASKMANAGER_VERSION&&(require("x.hub.taskman.js").TaskManager.NS_VERSION=global.TASKMANAGER_VERSION)}
function _setupServer(){var d=null;switch(global.HARDWARE_VERSION){case "CA":d=new xhub.ServerV6(global.STM);pluginManager.init(d);break;case "A1":d=new xhub.ServerNEO(global.STM);break;default:switch(global.PLATFORM){case "MAC":d=new xhub.Server(global.STM);break;case "WIN":d=new xhub.Server(global.STM);break;case "A20":d=new xhub.Server(global.STM);break;case "PI2":d=new xhub.Server(global.STM,null,"gpio26");break;case "PI-CM3+":d=new xhub.ServerV6(global.STM);pluginManager.init(d);break;default:d=
new xhub.Server(global.STM)}}d.hostType=global.PLATFORM;xhub.server=d;v5.server=d;d.HWV=global.HARDWARE_VERSION;d.VERSION=global.FIRMWARE_VERSION;d.BUILD=global.FIRMWARE_BUILD;d.DEFAULT_NAME=global.NAME;var l=null,m=Date.now();d.on("serialevent",function(b,a){require("x.logger.js").getLogger("x.hub.m.gateway.Serial").log("trace","SERIAL EVENT: "+b);var c=l,e=Date.now()-m;m=Date.now();l=b;if(!(c==b&&1E3>e)){c=null;try{c=JSON.parse(b)}catch(g){}c&&(require("x.hub.eventbus.js").emit("gatewayevent",c,
{address:"ST"},a),"EVT"!=a&&"STA"!=a||d.sendUDPMessage(a+":"+JSON.stringify(c)+"\r\n"))}});var f=require("x.hub.v6.js");f._centralUnit=new f.CentralUnit(d);f._centralUnit.init();d.setCmdFunc("refreshhm",function(b,a){a(JSON.stringify({XC_SUC:{}}))});"EA"==global.HARDWARE_VERSION&&d.setCmdFunc("resethm",function(b,a){require("x.hub.m.hm.js").resetChip(function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("addSensor",function(b,
a){b.query.type&&"ENOCEAN"==b.query.type.toUpperCase()&&"CA"!=global.HARDWARE_VERSION?require("x.hub.m.enocean.js").addSensor(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(null)});d.setCmdFunc("LearnSC",function(b,a){if(b.query.type&&"HM"==b.query.type.toUpperCase()&&"CA"!=global.HARDWARE_VERSION){var c=require("x.hub.m.hm.js");b.query.key&&b.query.sgtin?c.learnIPDevice(null,b.query.sgtin,b.query.key,function(e){e.error?
a(JSON.stringify({XC_ERR:{code:"001000",msg:e.error.message}})):a(JSON.stringify({XC_SUC:{devices:e.data}}))}):b.query.qrkey?c.learnIPDeviceQR(null,b.query.qrkey,function(e){e.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:e.error.message}})):a(JSON.stringify({XC_SUC:{devices:e.data}}))}):b.query.adr?c.learnRFDeviceSN(null,b.query.adr,function(e){e.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:e.error.message}})):a(JSON.stringify({XC_SUC:{devices:e.data}}))}):c.learnRFDevice(null,function(e){e.error?
a(JSON.stringify({XC_ERR:{code:"001000",msg:e.error.message}})):a(JSON.stringify({XC_SUC:{devices:e.data}}))})}else b.query.type&&"ENOCEAN"==b.query.type.toUpperCase()&&"CA"!=global.HARDWARE_VERSION?require("x.hub.m.enocean.js").learnDevice(b.query,function(e){e.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:e.error.message}})):a(JSON.stringify({XC_SUC:e.data}))}):b.query.type&&"ZIGBEE"==b.query.type.toUpperCase()?require("x.hub.m.zigbee.js").learnDevice(b.query,function(e){e.error?a(JSON.stringify({XC_ERR:{code:"001000",
msg:e.error.message}})):a(JSON.stringify({XC_SUC:e.data}))}):a(null)});d.setCmdFunc("SendSC",function(b,a){b.query.type&&"HM"==b.query.type.toUpperCase()&&"CA"!=global.HARDWARE_VERSION?b.query.address&&b.query.data?require("x.hub.m.hm.js").executeCommandLegacy(null,b.query.address,b.query.data,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(JSON.stringify({XC_ERR:{code:"001000",msg:"address or data invalid"}})):b.query.type&&"ENOCEAN"==
b.query.type.toUpperCase()&&"CA"!=global.HARDWARE_VERSION?b.query.address&&b.query.data?require("x.hub.m.enocean.js").executeCommandLegacy(null,b.query.address,b.query.data,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(JSON.stringify({XC_ERR:{code:"001000",msg:"address or data invalid"}})):b.query.type&&"ZWAVE"==b.query.type.toUpperCase()?b.query.address&&b.query.data&&b.query.devicetype?require("x.hub.m.zwave.js").executeCommandLegacy(null,
b.query.address,b.query.devicetype,b.query.data,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(JSON.stringify({XC_ERR:{code:"001000",msg:"address or data or devicetype invalid"}})):b.query.type&&"ZWAVE2"==b.query.type.toUpperCase()?require("x.hub.m.zway.js").executeCommandLegacy(b.query.address,b.query.data,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):b.query.type&&
"KNX"==b.query.type.toUpperCase()?require("x.hub.m.knx.js").executeCommandLegacy(b.query.address,b.query.data,function(c){c.error?a(JSON.stringify({XC_ERR:{code:c.error.code?c.error.code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):b.query.type&&"ZIGBEE"==b.query.type.toUpperCase()?require("x.hub.m.zigbee.js").executeCommandLegacy(b.query.address,b.query.data,function(c){c.error?a(JSON.stringify({XC_ERR:{code:c.error.code?c.error.code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):
b.query.type&&"RGB"==b.query.type.toUpperCase()&&"CA"==global.HARDWARE_VERSION?d.setLED(b.query.data,function(c){c?a(JSON.stringify({XC_ERR:{code:c.code?c.code:"001000",msg:c.message}})):a(JSON.stringify({XC_SUC:{}}))}):b.query.type&&"MBUS"==b.query.type.toUpperCase()?require("x.hub.m.mbus.js").executeCommandLegacy(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(null)});d.setCmdFunc("delSensor",function(b,a){b.query.type&&
"HM"==b.query.type.toUpperCase()&&"CA"!=global.HARDWARE_VERSION?b.query.adr?require("x.hub.m.hm.js").deleteDevice(null,b.query.adr,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(JSON.stringify({XC_ERR:{code:"001000",msg:"adr invalid"}})):b.query.type&&"ENOCEAN"==b.query.type.toUpperCase()&&"CA"!=global.HARDWARE_VERSION?require("x.hub.m.enocean.js").delSensor(b.query.address,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",
msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):b.query.type&&"ZIGBEE"==b.query.type.toUpperCase()&&"CA"!=global.HARDWARE_VERSION?require("x.hub.m.zigbee.js").removeDevice(b.query.address,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(null)});d.setCmdFunc("setVar",function(b,a){require("x.hub.sysvarman.js").setVar(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))})});
d.setCmdFunc("delVar",function(b,a){require("x.hub.sysvarman.js").delVar(b.query.id,function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))})});d.setCommandFunc("setVar",function(b,a){require("x.hub.sysvarman.js").setVar(b.query,function(c){c.error?a.send("{XC_ERR}"+JSON.stringify({code:"010000",msg:c.error.message})):a.send("{XC_SUC}{}")})});d.setCommandFunc("delVar",function(b,a){require("x.hub.sysvarman.js").delVar(b.query.id,function(c){c.error?
a.send("{XC_ERR}"+JSON.stringify({code:"010000",msg:c.error.message})):a.send("{XC_SUC}{}")})});var h=[],r=null;d.setCmdFunc("getStates",function(b,a){var c=function(n,k){var v=h;h=[];n?v.forEach(function(u){u(JSON.stringify({XC_ERR:{code:"001000",msg:n.message}}))}):0<k.length?v.forEach(function(u){u(JSON.stringify({XC_SUC:k}))}):v.forEach(function(u){u(JSON.stringify({XC_SUC:{}}))})},e=[],g=[],p=[],q=h.length,t=(new Date).getTime();0!=q&&18E4<t-r&&(c(Error("get states dead lock")),q=h.length);-1==
h.indexOf(a)&&h.push(a);0==q&&(r=(new Date).getTime(),async.parallel([function(n){var k=function(v){var u=b.url;if("POST"==b.method&&b.json){var z=require("url");u=z.parse(u,!0);if(u.query)for(var A in b.json)u.query[A]=b.json[A];u=z.format(u)}var w=setTimeout(function(){v&&(v({type:"ST_ERROR",state:"st timeout"}),v=null)},1E4);xhub.server._doSTMCommandRequest(u,!1,function(B){w&&(clearTimeout(w),w=null);if(v){try{var x=[],y=JSON.parse(B);y.XC_SUC?(Array.isArray(y.XC_SUC)?x=x.concat(y.XC_SUC):0<Object.keys(y.XC_SUC).length&&
(x=x.push(y.XC_SUC)),v(null,x)):v({type:"ST_ERROR",state:"st return:"+B})}catch(C){v({type:"ST_ERROR",state:"st return invalid json"})}v=null}})};"EA"!=global.HARDWARE_VERSION&&"CA"!=global.HARDWARE_VERSION?n():localStorage&&"true"==localStorage.getItem("x.hub.Server.DISABLE_ST_STATES")?n():k(function(v,u){v?k(function(z,A){z?k(function(w,B){w?g.push(w):g=g.concat(B);n()}):(g=g.concat(A),n())}):(g=g.concat(u),n())})},function(n){"EA"!=global.HARDWARE_VERSION?n():require("x.hub.m.hm.js").getAllStatesLegacy(function(k){k.error?
e.push({type:"HM_ERROR",state:k.error}):e=e.concat(k.data);n()})},function(n){-1==global.LOAD_MODULES.indexOf("enocean")||"CA"==global.HARDWARE_VERSION?n():require("x.hub.m.enocean.js").getAllStatesLegacy(function(k){k.error?e.push({type:"ENOCEAN_ERROR",state:k.error}):e=e.concat(k.data);n()},b.query)},function(n){-1==global.LOAD_MODULES.indexOf("zwave")?n():require("x.hub.m.zwave.js").getAllStatesLegacy(function(k){k.error?e.push({type:"ZWAVE_ERROR",state:k.error}):e=e.concat(k.data);n()})},function(n){-1==
global.LOAD_MODULES.indexOf("zway")?n():require("x.hub.m.zway.js").getAllStatesLegacy(function(k){k.error?e.push({type:"ZWAVE2_ERROR",state:k.error}):e=e.concat(k.data);n()})},function(n){-1==global.LOAD_MODULES.indexOf("mbus")?n():require("x.hub.m.mbus.js").getAllStatesLegacy(function(k){k.error?e.push({type:"MBUS_ERROR",state:k.error}):e=e.concat(k.data);n()})},function(n){-1==global.LOAD_MODULES.indexOf("knx")?n():require("x.hub.m.knx.js").getAllStatesLegacy(function(k){k.error?e.push({type:"KNX_ERROR",
state:k.error}):e=e.concat(k.data);n()})},function(n){-1==global.LOAD_MODULES.indexOf("zigbee")?n():require("x.hub.m.zigbee.js").getAllStatesLegacy(function(k){k.error?e.push({type:"ZIGBEE_ERROR",state:k.error}):e=e.concat(k.data);n()})},function(n){require("x.hub.taskman.js").readAllTasks(function(k){if(k.error)e.push({type:"TASK_ERROR",state:k.error});else{var v=[];k.data.forEach(function(u){u&&v.push({type:"TASK",id:u.id,active:u.active})});e=e.concat(v)}n()})},function(n){require("x.hub.sysvarman.js").getSysvarStates(function(k){k.error?
e.push({type:"SYSVAR_ERROR",state:k.error}):p=p.concat(k.data);n()})}],function(n){n?c(n,e):g&&0<g.length?require("x.hub.sysvarman.js").processSysvarST(xhub.server,g,function(k){k&&!k.error&&k.data&&0<k.data.length&&(e=e.concat(k.data));c(n,e)}):(p&&0<p.length&&(e=e.concat(p)),c(n,e))}))});d.setCmdFunc("GetSI",function(b,a){d.getTimeZoneCompatiable(function(c,e){d.doSTMCommand("XC_FNC=GetSI",function(g){g&&g.XC_SUC&&(g.XC_SUC.HWV=d.HWV,g.XC_SUC.FWV_ST=g.XC_SUC.FWV,g.XC_SUC.FWV=d.VERSION,!c&&e&&(g.XC_SUC.TZ=
e+""));a(JSON.stringify(g))})})});d.setCommandFunc("GetSI",function(b,a){d.getTimeZoneCompatiable(function(c,e){d.doSTMCommand("XC_FNC=GetSI",function(g){g&&g.XC_SUC?(g.XC_SUC.HWV=d.HWV,!c&&e&&(g.XC_SUC.TZ=e+""),a.send("{XC_SUC}"+JSON.stringify(g.XC_SUC))):a.send("{XC_ERR}")})})});d.setCommandFunc("setTZ",function(b,a){d.setTimeZoneCompatiable(b.query.data,function(c){c?a.send("{XC_ERR}"):a.send("{XC_SUC}")})});d.setCmdFunc("setTZ",function(b,a){d.setTimeZoneCompatiable(b.query.data,function(c){c?
a(JSON.stringify({XC_ERR:{}})):a(JSON.stringify({XC_SUC:{}}))})});d.setCommandFunc("setLocation",function(b,a){b=b.query;d.setLocation(b?b.lat:null,b?b.long:null,function(c){c?a(JSON.stringify({XC_ERR:{code:c.code?c.code:"000000",msg:c.message}})):a(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("setLocation",function(b,a){b=b.query;d.setLocation(b?b.lat:null,b?b.long:null,function(c){c?a(JSON.stringify({XC_ERR:{code:c.code?c.code:"000000",msg:c.message}})):a(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("SendM",
function(b,a){if(b.query&&b.query.m&&b.query.cmd){var c=b.query.m,e=b.query.cmd;delete b.query.XC_FNC;delete b.query.m;delete b.query.cmd;var g=null;try{g=require("x.hub.m."+c+".js")}catch(p){}g&&g.executeCommand?g.executeCommand(b.query,e,function(){a('{"XC_SUC":{}}')}):a('{"XC_ERR":{"code":"000000","msg":"internal error"}}')}else a('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});d.setCmdFunc("GetM",function(b,a){if(b.query&&b.query.m){var c=b.query.m;delete b.query.XC_FNC;delete b.query.m;
var e=null;try{e=require("x.hub.m."+c+".js")}catch(g){}e&&e.updateStates?e.updateStates(b.query,function(g){g?a('{"XC_SUC":'+JSON.stringify(g)+"}"):a('{"XC_SUC":{}}')}):a('{"XC_ERR":{"code":"000000","msg":"internal error"}}')}else a('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});d.setCmdFunc("SendRM",function(b,a){require("x.logger.js").getLogger("x.hub.v5.CloudConnect").log("debug","execute command:"+JSON.stringify(b.query));b.query?require("x.hub.commandman.js").commandHandler2.executeCommandWithIdx(b.query.device,
b.query.gateway,b.query.command,function(c){c.error?a('{"XC_ERR":{"code":"000000","msg":"'+c.error.message+'"}}'):a('{"XC_SUC":{}}')}):a('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});d.setCmdFunc("GetRM",function(b,a){require("x.logger.js").getLogger("x.hub.v5.CloudConnect").log("debug","get states:"+JSON.stringify(b.query));b.query?require("x.hub.commandman.js").commandHandler2.getStateWithIdx(b.query.device,b.query.gateway,b.query.status,function(c){c.error?a('{"XC_ERR":{"code":"000000","msg":"'+
c.error.message+'"}}'):a('{"XC_SUC":'+JSON.stringify(c.data)+"}")}):a('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});d.setCmdFunc("DoMacroRM",function(b,a){require("x.logger.js").getLogger("x.hub.v5.CloudConnect").log("debug","execute macro:"+JSON.stringify(b.query));b.query?require("x.hub.macroman.js").executeWithIdx2(b.query.groupIdx,b.query.macroIdx,function(c){c.error?a('{"XC_ERR":{"code":"000000","msg":"'+c.error.message+'"}}'):a('{"XC_SUC":{}}')}):a('{"XC_ERR":{"code":"000001", "msg":"invalid request"}}')});
d.setCmdFunc("GetTask",function(b,a){require("x.hub.taskman.js").doWebRequest("Read",b,a)});d.setCmdFunc("CreateTask",function(b,a){require("x.hub.taskman.js").doWebRequest("Create",b,a)});d.setCmdFunc("UpdateTask",function(b,a){require("x.hub.taskman.js").doWebRequest("Update",b,a)});d.setCmdFunc("DeleteTask",function(b,a){require("x.hub.taskman.js").doWebRequest("Delete",b,a)});d.setCmdFunc("DoTask",function(b,a){require("x.hub.taskman.js").doWebRequest("Do",b,a)});d.setCmdFunc("CancelTask",function(b,
a){require("x.hub.taskman.js").doWebRequest("Cancel",b,a)});d.setCmdFunc("IsTaskRunning",function(b,a){require("x.hub.taskman.js").doWebRequest("isRunning",b,a)});d.setCmdFunc("SetTaskActive",function(b,a){require("x.hub.taskman.js").doWebRequest("SetTaskActive",b,a)});d.setCmdFunc("ToggleTaskActive",function(b,a){require("x.hub.taskman.js").doWebRequest("ToggleTaskActive",b,a)});d.setCmdFunc("SetAlarmActive",function(b,a){require("x.hub.taskman.js").doWebRequest("SetAlarmActive",b,a)});d.setCmdFunc("SetAlarmDelay",
function(b,a){require("x.hub.taskman.js").doWebRequest("SetAlarmDelay",b,a)});d.setCmdFunc("GetAlarmInfo",function(b,a){require("x.hub.taskman.js").doWebRequest("GetAlarmInfo",b,a)});d.setCmdFunc("SelectAlarmTask",function(b,a){require("x.hub.taskman.js").doWebRequest("SelectAlarmTask",b,a)});d.setCmdFunc("SetAlarmPin",function(b,a){require("x.hub.taskman.js").doWebRequest("SetAlarmPin",b,a)});d.setCmdFunc("GetCloudServer",function(b,a){require("x.hub.taskman.js").doWebRequest("GetCloudServer",b,
a)});d.setCmdFunc("SetCloudServer",function(b,a){require("x.hub.taskman.js").doWebRequest("SetCloudServer",b,a)});d.setCmdFunc("GetCloudDeviceTriggerGateway",function(b,a){require("x.hub.taskman.js").doWebRequest("GetCloudDeviceTriggerGateway",b,a)});d.setCommandFunc("SendSC",function(b,a){b.query.type&&"RGB"==b.query.type.toUpperCase()&&"CA"==global.HARDWARE_VERSION?d.setLED(b.query.data,function(c){c?a.send("{XC_ERR}"+JSON.stringify({code:c.code?c.code:"001000",msg:c.message})):a.send("{XC_SUC}"+
JSON.stringify({}))}):d._doSTMCommandRequest(b.url,!0,function(c){a.send(c)})});"EA"==global.HARDWARE_VERSION&&(d.setCmdFunc("RehauPinChallenge",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauPinChallenge",b,a)}),d.setCmdFunc("RehauGetAlarmInfo",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauGetAlarmInfo",b,a)}),d.setCmdFunc("RehauSetAlarmDelay",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauSetAlarmDelay",b,a)}),d.setCmdFunc("RehauSetDoorAlarmDelay",function(b,
a){require("x.hub.taskman.js").doWebRequest("RehauSetDoorAlarmDelay",b,a)}),d.setCmdFunc("RehauSetNewPin",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauSetNewPin",b,a)}),d.setCmdFunc("RehauSelectAssociateTaskAlarm",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauSelectAssociateTaskAlarm",b,a)}),d.setCmdFunc("RehauSelectAssociateTaskPreAlarm",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauSelectAssociateTaskPreAlarm",b,a)}),d.setCmdFunc("RehauSetAlarmActive",
function(b,a){require("x.hub.taskman.js").doWebRequest("RehauSetAlarmActive",b,a)}),d.setCmdFunc("RehauAddAlarmKey",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauAddAlarmKey",b,a)}),d.setCmdFunc("RehauUpdateAlarmKey",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauUpdateAlarmKey",b,a)}),d.setCmdFunc("RehauDeleteAlarmKey",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauDeleteAlarmKey",b,a)}),d.setCmdFunc("RehauAddAlarmDoor",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauAddAlarmDoor",
b,a)}),d.setCmdFunc("RehauUpdateAlarmDoor",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauUpdateAlarmDoor",b,a)}),d.setCmdFunc("RehauDeleteAlarmDoor",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauDeleteAlarmDoor",b,a)}),d.setCmdFunc("RehauSetAlarmConfirmation",function(b,a){require("x.hub.taskman.js").doWebRequest("RehauSetAlarmConfirmation",b,a)}));d.setCmdFunc("AddEventListener",function(b,a){if((b=b.query.data)&&b.sys){var c=require("x.hub.moduleman.js").modulemanager.getModule(b.sys);
c?c.addStateDevice(b,function(e){e.error?a(JSON.stringify({XC_ERR:{code:"000000",msg:e.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(JSON.stringify({XC_ERR:{code:"000000",msg:"no module for sys:"+b.sys}}))}else a(JSON.stringify({XC_ERR:{code:"000000",msg:"device format invalid"}}))});d.setCmdFunc("GetMetaInfo",function(b,a){b=require("x.hub.taskman.js").taskManager;var c={XC_SUC:{version:String(b.version),deploy:{time:localStorage.getItem("x.hub.hubsyncman.SyncManager.TIMESTAMP"),userid:localStorage.getItem("x.hub.hubsyncman.SyncManager.USERID"),
appid:localStorage.getItem("x.hub.hubsyncman.SyncManager.APPID")}}};"A1"==global.HARDWARE_VERSION&&(c.XC_SUC.trial=0!=b._mode%31);a(JSON.stringify(c))});d.setCmdFunc("GetUSBDevices",function(b,a){require("x.hub.peripheralman.js").getUSBDevices(function(c){c.error?a(JSON.stringify({XC_ERR:{message:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("SetLogger",function(b,a){b.query.level?require("x.hub.logman.js").setLoggger(b.query.tag,b.query.level,function(){a(JSON.stringify({XC_SUC:{}}))}):
a(JSON.stringify({XC_ERR:{message:"parameter invalid",code:"010001"}}))});d.setCmdFunc("GetLogger",function(b,a){b=require("x.logger.js").getAll();a(JSON.stringify({XC_SUC:b}))});d.setCmdFunc("DummyEvent",function(b,a){var c=require("x.hub.eventbus.js"),e=b.query.data,g=b.query.type;g||(g="status");switch(g){case "status":c.emit("status",e);break;case "gatewayevent":c.emit("gatewayevent",e,b.query.rinfo,b.query.tag);break;case "hm":require("x.hub.m.hm.js").onDeviceEvent(e,!0);break;default:c.emit(g,
e)}a(JSON.stringify({XC_SUC:{}}))});d.setCmdFunc("DummyTaskmanEvent",function(b,a){var c=b.query.event;b=b.query.meta;require("x.hub.taskman.js").onStatusEvt(c,b);a(JSON.stringify({XC_SUC:{}}))});d.setCmdFunc("DirectEvent",function(b,a){var c=b.query.event;b=b.query.tag;require("x.hub.m.gateway.js")._onEvent(c,{address:"http call"},b);a(JSON.stringify({XC_SUC:{}}))});d.setCmdFunc("GetHmMonitors",function(b,a){require("x.hub.m.hm.js").getMonitorStates(function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,
code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});"EA"==global.HARDWARE_VERSION?(d.setCmdFunc("gethmconfig",function(b,a){b.query.address?require("x.hub.m.hm.js").getConfig({address:b.query.address},function(c){c.error?a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{config:c.data}}))}):a(null)}),d.setCmdFunc("sethmconfig",function(b,a){b.query.address&&b.query.config?require("x.hub.m.hm.js").setConfig({address:b.query.address},b.query.config,function(c){c.error?
a(JSON.stringify({XC_ERR:{code:"001000",msg:c.error.message}})):a(JSON.stringify({XC_SUC:{}}))}):a(null)}),d.setCmdFunc("GetHmDevices",function(b,a){require("x.hub.m.hm.js").getAllDevices(function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})}),d.setCmdFunc("ConfigSiegeniaWindow",function(b,a){require("x.hub.m.enocean.js").configSiegeniaWindow(null,null,function(c){c.error?a(JSON.stringify({XC_ERR:{message:c.error.message,code:c.error.code}})):
a(JSON.stringify({XC_SUC:{}}))})}),d.setCmdFunc("AddEnoceanVirtualDevice",function(b,a){require("x.hub.m.enocean.js").generateVirtualDevice(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})}),d.setCmdFunc("AddEnoceanDevice",function(b,a){require("x.hub.m.enocean.js").addSensor(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})}),d.setCmdFunc("UpdateEnoceanDevice",
function(b,a){require("x.hub.m.enocean.js").updateSensor(b.query.address,b.query.device,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})}),d.setCmdFunc("TeachinEnocean",function(b,a){require("x.hub.m.enocean.js").teachinDevice(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})}),d.setCmdFunc("EnOceanSDK",function(b,a){require("x.hub.m.enocean.js")._doSDK(b.query.data,
function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})}),d.setCmdFunc("ResetEnOceanSenderID",function(b,a){require("x.hub.m.enocean.js").resetDefaultSenderID(function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:{}}))})}),d.setCmdFunc("SetRehauInoventHumidityAccessory",function(b,a){require("x.hub.m.enocean.js").setInoventHumidityAccessory(b.query.inoventID,b.query.humiditySensorID,
function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:{}}))})}),d.setCmdFunc("SetRehauInoventCo2Accessory",function(b,a){require("x.hub.m.enocean.js").setInoventCo2Accessory(b.query.inoventID,b.query.co2SensorID,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:{}}))})}),d.setCmdFunc("GetRehauInoventAccessories",function(b,a){require("x.hub.m.enocean.js").getInoventAccessories(b.query.inoventID,
function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})}),d.setCmdFunc("RawEnoceanPacket",function(b,a){b=b.query.data;require("x.hub.m.enocean.js").__simulateRawEnoceanPacket(b,function(c){a(JSON.stringify({XC_SUC:{}}))})}),d.setCmdFunc("SendESPFrame",function(b,a){var c=b.query.type,e=b.query.data,g=b.query.optData;b=b.query.requireResponse;require("x.hub.m.enocean.js").__sendEspFrame(c,e,g,b,function(p){p.error?a(JSON.stringify({XC_ERROR:{message:p.error.message,
code:p.error.code}})):a(JSON.stringify({XC_SUC:p.data}))})})):"CA"==global.HARDWARE_VERSION&&d.setCmdFunc("SetFGW14Baudrate",function(b,a){var c=require("x.hub.m.enocean.js");b.query&&b.query.baudrate&&!isNaN(parseInt(b.query.baudrate))?c.setFGW14Baudrate(parseInt(b.query.baudrate),function(e){e.error?a(JSON.stringify({XC_ERR:{message:e.error.message,code:e.error.code}})):a(JSON.stringify({XC_SUC:{}}))}):a(JSON.stringify({XC_ERR:{message:"invalid request",code:"000000"}}))});d.setCmdFunc("ZWaveInclusion",
function(b,a){require("x.hub.m.zway.js").learnDevice(b.query,function(c,e,g){console.log("learn zwave procedure",c,e,g)},function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("ZWaveExclusion",function(b,a){require("x.hub.m.zway.js").removeDevice(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("ZWaveListDevices",function(b,
a){require("x.hub.m.zway.js").listDevices(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("ZWaveListInterviewResults",function(b,a){require("x.hub.m.zway.js").listInterviewResults(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("ZWaveResetController",function(b,a){require("x.hub.m.zway.js").resetController(function(c){c.error?
a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("ZWaveSetDeviceSetting",function(b,a){require("x.hub.m.zway.js").setDeviceSetting(b.query.deviceID,b.query.setting,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("ZWaveGetDeviceSetting",function(b,a){require("x.hub.m.zway.js").getDeviceSetting(b.query.deviceID,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,
code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("ZWaveForcePollDevices",function(b,a){var c=require("x.hub.m.zway.js");b.query.deviceIDs?(b=b.query.deviceIDs.split(","),c.forcePoll(b,function(e){e.error?a(JSON.stringify({XC_ERR:{msg:e.error.message,code:e.error.code}})):a(JSON.stringify({XC_SUC:e.data}))})):a(JSON.stringify({XC_ERR:{msg:"no device id list",code:"000000"}}))});d.setCmdFunc("GetZwaveStates",function(b,a){b=b.query.devices;require("x.hub.m.zwave.js").__getStates(b,
function(c){c.error?a(JSON.stringify({XC_ERROR:{message:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("GetKnxIpGateways",function(b,a){require("x.hub.m.knx.js").getIPGateways(function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("AddKnxIpGateway",function(b,a){b=b.query.data;require("x.hub.m.knx.js").addIPGateway(b,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,
code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("UptateKnxIpGateway",function(b,a){b=b.query.data;require("x.hub.m.knx.js").updateIPGateway(b,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("DeleteKnxIpGateway",function(b,a){b=b.query.data;require("x.hub.m.knx.js").deleteIPGateway(b,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:{}}))})});
d.setCmdFunc("GetKnxDevices",function(b,a){require("x.hub.m.knx.js").getDevices(function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("AddKnxDevice",function(b,a){b=b.query.data;require("x.hub.m.knx.js").addDevice(b,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("UptateKnxDevice",function(b,a){b=b.query.data;require("x.hub.m.knx.js").updateDevice(b,
function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("DeleteKnxDevice",function(b,a){b=b.query.data;require("x.hub.m.knx.js").deleteDevice(b,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("ListKnxMonitors",function(b,a){require("x.hub.m.knx.js").listMonitors(function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,
code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("SearchKnxIpGateways",function(b,a){require("x.hub.m.knx.js").searchKNXGateway(function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("DoZigbeeNativeCommandRaw",function(b,a){require("x.hub.m.zigbee.js").executeCommandNativeRaw(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});
d.setCmdFunc("ListZigbeeDevices",function(b,a){require("x.hub.m.zigbee.js").listDevices(b.query,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:c.data}))})});d.setCmdFunc("RefreshMbusDeviceStates",function(b,a){b=b.query.address;require("x.hub.m.mbus.js").updateStates(b,function(c){c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:{}}))})});d.setCmdFunc("DummyMbusMessage",function(b,
a){b=b.query.message;require("x.hub.m.mbus.js").dummyMbusMessage(b,function(c){c&&c.error?a(JSON.stringify({XC_ERR:{msg:c.error.message,code:c.error.code}})):a(JSON.stringify({XC_SUC:{}}))})});"EA"==global.HARDWARE_VERSION&&(d.setCommandFunc("AddGroup",function(b,a){a.send("{XC_SUC}")}),d.setCommandFunc("setTaskDeviceAddress",function(b,a){var c=b.query.device;b=b.query.address;c&&b&&devices[c]&&(devices[c].address=b,localStorage&&localStorage.setItem("xnm.aio.xhub.siegenia."+c,b));a.send("{XC_SUC}")}),
d.setCommandFunc("getTaskDeviceAddress",function(b,a){var c="{XC_ERR}";(b=b.query.device)&&devices[b]&&(c='{XC_SUC}{"address":"'+devices[b].address+'"}');a.send(c)}),d.setCommandFunc("setAlarmGroup",function(b,a){for(var c in taskmanager._tasks)80<=c&&(taskmanager._tasks[c].active="1"==b.query.active?!0:!1);a.send("{XC_SUC}")}),d.setCommandFunc("DelGroup",function(b,a){var c="{XC_ERR}",e=parseInt(b.query.id),g=parseInt(b.query.nid);taskmanager._tasks[e]&&b.query.nid&&(taskmanager._tasks[g]=taskmanager._tasks[e],
delete taskmanager._tasks[e],c="{XC_SUC}");a.send(c)}),d.setCommandFunc("saveGroup",function(b,a){var c="{XC_ERR}",e=parseInt(b.query.id);taskmanager._tasks[e]&&(taskmanager._tasks[e].active="1"==b.query.active?!0:!1,c="{XC_SUC}");a.send(c)}),d.setCommandFunc("GetAll",function(b,a){b="";var c=1,e=1,g;for(g in taskmanager._tasks){var p=taskmanager._tasks[g],q="0";p.active&&(q="1");var t="",n="",k;for(k=0;k<p.trigger.length;k++)n+=XC.getHexVal(c,2),""!=b&&(b+=","),b+='{"sys":"EVENT","id":"'+XC.getHexVal(c++,
2)+'","code":""}';for(k=0;k<p.action.length;k++)t+=XC.getHexVal(e,2),""!=b&&(b+=","),b+='{"sys":"ACTION","id":"'+XC.getHexVal(e++,2)+'","code":""}';""!=b&&(b+=",");b+='{"sys":"GROUP","id":"'+XC.getHexVal(g,2)+'","name":"'+p.name+'","active":"'+q+'","triggerids":"'+n+'","actionids":"'+t+'"}'}a.send("{XC_SUC}["+b+"]")}));return d}
function _setupAutomationManagerMode(d){function l(b){var a=require("crypto"),c=new Buffer("fO4gAeDjh4HwO0D8+/9Bfw==","base64"),e=new Buffer("+ubtPBJR9uejkjXiN6c1Bg==","base64");a=a.createDecipheriv("aes-128-cbc",c,e);a.setAutoPadding(!0);b=[a.update(new Buffer(b,"base64"))];b.push(a.final());return Buffer.concat(b).toString("utf8")}function m(b){if(!b)return 31*f(23,76)+2;try{var a=l(b);if(10>a.length||"t"!=a.charAt(0)||"a"!=a.charAt(2)||"k"!=a.charAt(9))return 31*f(23,76)+2;var c=a.charAt(1)+""+
a.charAt(5)+a.charAt(6);return 31*parseInt(c)}catch(e){return 31*f(23,76)+2}}function f(b,a){b=Math.ceil(b);a=Math.floor(a);return Math.floor(Math.random()*(a-b))+b}var h=require("x.hub.taskman.js"),r=localStorage.getItem("info");h.taskManager.version=global.TASKMANAGER_VERSION;h.taskManager._mode=r?m(r):m();r=require("body-parser");d._app.use("/xhub/activate/do",r.text({limit:"100kb"}));d._app.post("/xhub/activate/req",function(b,a){global.TMP_TOKEN=f(1,5E3);setTimeout(function(){global.TMP_TOKEN=
null},3E4);a.json({status:"success",data:global.TMP_TOKEN})});d._app.post("/xhub/activate/do",function(b,a){if(global.TMP_TOKEN)if(b.body)try{var c=l(b.body),e=""+global.TMP_TOKEN,g=c.substr(c.length-e.length);c.length<e.length||g!=e?a.json({status:"fail",message:"invalid token",code:0}):(localStorage.setItem("info",b.body),h.taskManager._mode=m(b.body),a.json({status:"success"}))}catch(p){a.json({status:"fail",message:"invalid request body",code:0})}else a.json({status:"fail",message:"no request body",
code:0});else a.json({status:"fail",message:"token expired",code:0})})}
function _setupDebugSite(d){var l=require("x.hub.fileman.js"),m=l.fileManager,f=require("express"),h=require("path"),r=require("ws").Server,b=h.join(__dirname,"site");d._app.use("/debug",f.static(b+"/debug"));d._app.use("/js",f.static(b+"/js"));this._wss=new r({server:d._httpserver,path:"/debug/tracker/ws"});this._wss.on("error",function(a){console.log("web socket server error:"+a.stack)}.bind(this));this._wss.on("connection",function(a){a.__watchDog=setTimeout(function(){a.close()},6E4);a.on("error",
function(c){console.log("web socket error:"+c.stack);a.close()}.bind(this));a.on("close",function(){if(a.__tags){var c=require("x.logger.js");a.__tags.forEach(function(e){c.removeLogTracker(e,a.__tracker)})}a.__tail&&a.__tail.unwatch()});a.on("message",function(c,e){try{var g=JSON.parse(c);if("main"==g.system){var p=new (require("tail").Tail)(h.resolve(m.getUserLogPath(),"v5plus_daemon"));a.__tail=p;p.on("line",function(t){a.send(t+"\r\n")});p.on("error",function(t){console.log("ERROR: ",t)})}else{c=
[];switch(g.system){case "homematic":c=["x.hub.m.hm","xnm.aio.hm"];break;case "knx":c=["x.hub.m.knx","xnm.aio.knx"];break;case "zwave":c=["x.hub.m.zway"];break;case "enocean":c=["x.hub.m.enocean"];break;case "zigbee":c=["x.hub.m.zigbee"];break;case "aio":c=["x.hub.m.gateway"];break;case "taskmanager":c=["x.hub.taskman"];break;case "script":c=["x.hub.scriptman"];break;case "rf":c=["x.hub.v5.USBSerial","x.hub.v6.STM"]}if(0<c.length){a.__watchDog&&(clearTimeout(a.__watchDog),a.__watchDog=null);a.__tags=
c;a.__tracker=function(t){a.send(t+"\r\n")};var q=require("x.logger.js");c.forEach(function(t){q.setLogTracker(t,a.__tracker)})}}}catch(t){a.send(JSON.stringify({error:t.message})),a.close()}}.bind(this))}.bind(this));d._app.get("/debug/tracker/log",function(a,c){switch(a.query.system){case "taskmanager":var e="v5p_taskmanager.log";break;case "homematic":e="v5p_homematic.log";break;case "knx":e="v5p_knx.log";break;case "zigbee":e="v5p_zigbee.log";break;case "zwave":e="v5p_zwave.log";break;case "enocean":e=
"v5p_enocean.log";break;case "aio":e="v5p_aiogateway.log";break;case "rf":e="v5p_rf_st.log";break;case "main":e="v5plus_daemon";break;default:c.status(404).send("system unknow")}a=h.join(l.fileManager.getUserLogPath(),e);c.sendFile(a)});b=h.join(__dirname,"site/debug/enocean");d._app.use("/debug/enocean/tracker",f.static(b));b=h.join(__dirname,"resources");d._app.use("/resources",f.static(b));this._wss=new r({server:d._httpserver,path:"/debug/enocean/ws"});this._wss.on("error",function(a){console.log("web socket server error:"+
a.stack)}.bind(this));this._wss.on("connection",function(a){console.log("web socket connected");var c={onFrame:function(g,p){a.send("+++++++++++++++++++++++++++++++++\r\n");a.send("EnOcean Frame:");a.send(p+"\r\n");a.send(JSON.stringify(g.toJSON())+"\r\n");a.send("+++++++++++++++++++++++++++++++++\r\n")},onTelegram:function(g){a.send("########################################################\r\n");a.send("EnOcean Telegram:\r\n");a.send(JSON.stringify(g.toJSON())+"\r\n");a.send("########################################################\r\n")},
onResolveEvents:function(g,p){a.send("===============================\r\n");a.send("Resolved Events from:"+g+"\r\n");p.forEach(function(q){a.send(JSON.stringify(q)+"\r\n")});a.send("===============================\r\n")}},e=require("x.hub.m.enocean.js");e.__addTelegramTracker(c);a.on("error",function(g){console.log("web socket error:"+g.stack);a.close()}.bind(this));a.on("close",function(){e.__removeTelegramTracker(c)});a.on("message",function(g,p){}.bind(this))}.bind(this));this._wss2=new r({server:d._httpserver,
path:"/siegenia/enocean/windowconfig"});this._wss2.on("error",function(a){console.log("web socket server error:"+a.stack)}.bind(this));this._wss2.on("connection",function(a){var c=require("x.hub.m.enocean.js");a.__watchDog=setTimeout(function(){a.close()},3E5);a.on("error",function(e){console.log("web socket error:"+e.stack);c._siegeniaHandler.stopCalibateWindow();a.close()}.bind(this));a.on("close",function(){clearTimeout(a.__watchDog);c._siegeniaHandler.stopCalibateWindow()});a.on("message",function(e,
g){try{var p=JSON.parse(e);"start"==p.command&&(c._siegeniaHandler.startCalibateWindow(p.windowID,function(q,t,n){q?a.send(JSON.stringify({error:q.message})):a.send(JSON.stringify({windowID:t,message:n}))}),c._siegeniaHandler.configWindow(p.params,p.windowID,function(q){q&&a.send(JSON.stringify({error:q.message,code:q.code}))}))}catch(q){a.send(JSON.stringify({error:q.message}))}}.bind(this))}.bind(this));this._wss3=new r({server:d._httpserver,path:"/zwave2/inclusion"});this._wss3.on("error",function(a){console.log("web socket server zwaveinclusion error:"+
a.stack)}.bind(this));this._wss3.on("connection",function(a){var c=require("x.hub.m.zway.js");a.__watchDog=setTimeout(function(){a.close()},3E5);a.on("error",function(e){console.log("web socket error:"+e.stack);a.close()}.bind(this));a.on("close",function(){clearTimeout(a.__watchDog)});a.on("message",function(e,g){try{var p=JSON.parse(e);"start"==p.command?c.learnDevice(null,function(q,t,n){a.send(JSON.stringify({progress:q,subprogress:t,message:n}))},function(q){q.error?a.send(JSON.stringify({finish:!0,
error:q.error.message,code:q.error.code,device:q.data})):a.send(JSON.stringify({finish:!0,device:q.data}));a.close()}):"updateInterview"==p.command&&(p.address?c.updateInterview(p.address,p.instanceID,p.commandClassID,function(q,t,n){a.send(JSON.stringify({progress:q,subprogress:t,message:n}))},function(q){q.error?a.send(JSON.stringify({finish:!0,error:q.error.message,code:q.error.code,device:q.data})):a.send(JSON.stringify({finish:!0,device:q.data}));a.close()}):a.send(JSON.stringify({finish:!0,
error:"no address parameter",code:"08999"})))}catch(q){a.send(JSON.stringify({error:q.message}))}}.bind(this))}.bind(this));this._wss4=new r({server:d._httpserver,path:"/taskman/tracker"});this._wss4.on("error",function(a){console.log("web socket server error:"+a.stack)}.bind(this));this._wss4.on("connection",function(a){var c=require("url").parse(a.upgradeReq.url);c=require("querystring").parse(c.query);c.taskID||a.close();a.__taskID=c.taskID;a.__watchDog=setTimeout(function(){a.close()},6E4);a.__tmListener=
function(g){a.send(g+"\r\n")};var e=require("x.hub.taskman.js");e.startTaskTrace(a.__taskID,a.__tmListener,function(g){g&&g.error&&(a.send(JSON.stringify({error:g.error.message})),a.close())});a.on("error",function(g){console.log("web socket error:"+g.stack);a.close()}.bind(this));a.on("close",function(){a.__taskID&&a.__tmListener&&e.stopTaskTrace(a.__taskID,a.__tmListener)});a.on("message",function(g,p){try{JSON.parse(g).alive&&(a.__watchDog&&(clearTimeout(a.__watchDog),a.__watchDog=null),a.__watchDog=
setTimeout(function(){a.close()},6E4))}catch(q){a.send(JSON.stringify({error:q.message})),a.close()}}.bind(this))}.bind(this))}_loadCompilerConfig();_loadProgrammEnv();_loadConfigFile();_loadRuntimeConfig();var fm=require("x.hub.fileman.js");
fm.init("A1"==global.HARDWARE_VERSION?"NEO Server":"v5plus",function(){var d=fm.fileManager,l=require("node-localstorage").LocalStorage;if("EA"==global.HARDWARE_VERSION)fs.existsSync("./data")||fs.mkdirSync("./data"),localStorage=new l("./data/localstorage"),fs.existsSync("./localstorage")&&fs.rmdirRecursiveSync("./localstorage");else if("CA"==global.HARDWARE_VERSION){var m=d.getUserRootDataPath();fs.existsSync(m)||fs.mkdirSync(m);localStorage=new l(m+"/localstorage");fs.existsSync("./localstorage")&&
fs.rmdirRecursiveSync("./localstorage")}else if("A1"==global.HARDWARE_VERSION&&!hasLocalStorage)try{localStorage=new l(d.getUserRootDataPath()+path.sep+"localstorage")}catch(f){}require("x.hub.logman.js").init(d,function(){var f=_setupServer();_setupDebugSite(f);if("EA"==global.HARDWARE_VERSION&&"A20"==global.PLATFORM){console.log((new Date).toString()+" ===========> LED Start Sequence");var h=new miot.STMUpdater;h.hostType=f.hostType;h.resetST();setTimeout(function(){f.startSTM(function(b){f.doSTMCommand("XC_FNC=SendSC&type=RGB&data=040305")})},
500);0==v5.Native.checkResetPin()&&(console.log((new Date).toString()+" ===========> reset button pressed, start safe mode"),global.SAFE_MODE=!0)}else"CA"==global.HARDWARE_VERSION?(console.log((new Date).toString()+" ===========> LED Start Sequence"),h=require("x.hub.v6.js"),h.init(f),h._led.startSystemInit()):global.STM&&setTimeout(function(){f.startSTM(function(b){})},500);require("x.hub.resource.js").init(f._app,d);require("x.hub.rule.js").init(f._app,d);require("x.hub.group.js").init(f._app,d);
require("x.hub.action.js").init(f._app,d);require("x.hub.password.js").init(d);require("x.hub.deviceman.js").init(f._app,d,function(){require("x.hub.macroman.js").init(f._app,d);require("x.hub.scriptman.js").init(f._app,f._httpserver);require("x.hub.commandman.js").init(f._app);var b=require("x.hub.taskman.js");global.SAFE_MODE&&(console.log("!!! run task manager in safe mode"),b.lock());b.init();require("x.hub.sysvarman.js").init(f._app,d);"A1"==global.HARDWARE_VERSION&&_setupAutomationManagerMode(f);
f.startWebserver(global.WEB_SERVER_PORT,function(){"EA"==global.HARDWARE_VERSION&&"A20"==global.PLATFORM?f.doSTMCommand("XC_FNC=SendSC&type=RGB&data=0400"):"CA"==global.HARDWARE_VERSION&&require("x.hub.v6.js")._led.stopSystemInit()});f.enableCloudConnect(new v5.CloudConnect);"A20"==global.PLATFORM&&"EA"==global.HARDWARE_VERSION&&v5.Native.watchResetPin(f,function(a){XC.debugf("RESET: "+a);"reboot"==a?f.restart(0):"network"==a?v5.Native.resetNetwork(function(){f.restart(0)}):"passwords"==a?v5.reset(f,
a,function(){f.restart(0)}):"factory"==a&&v5.reset(f,a,function(){v5.Native.resetHM(function(){v5.Native.resetZway(function(){v5.Native.resetZigbee(function(){v5.Native.resetNetwork(function(){f.restart(0)})})})})})})});"A20"==global.PLATFORM&&"EA"==global.HARDWARE_VERSION&&require("x.hub.datastore.js").init(d);require("x.hub.peripheralman.js").init(f._app,f._httpserver);require("x.hub.hubsyncman.js").init(f._app,d);var r=require("x.hub.moduleman.js");global.LOAD_MODULES.forEach(function(b){r.Modules.push(b)});
r.init();r.initModules();h=require("xnm.aio.gateway.js");h._autoSearchInterval&&clearInterval(h._autoSearchInterval)})});process.on("uncaughtException",function(d){console.error(d.stack)});process.on("SIGINT",function(){console.log("Got SIGINT.");-1!=global.LOAD_MODULES.indexOf("knx")?require("x.hub.m.knx.js").clean(function(){console.log("SIGINT callback.");process.exit(1)}):process.exit(1)});
process.on("SIGTERM",function(){console.log("Got SIGTERM.");-1!=global.LOAD_MODULES.indexOf("knx")?require("x.hub.m.knx.js").clean(function(){console.log("SIGINT callback.");process.exit(1)}):process.exit(1)});
