#!/bin/sh
#
# Starts multimacd.
#

LOGLEVEL_RFD=5
CFG_TEMPLATE_DIR=/etc/config_templates
PIDFILE=/var/run/multimacd.pid

source /var/hm_mode 2>/dev/null

# skip this startup in LAN Gateway or HmIP-RFUSB mode
[[ ${HM_MODE} == "HMLGW" || ${HM_MODE} == "HmIP-RFUSB" || ${HM_MODE} == "HmRF-CFG-USB-2" ]] && exit 0

init() {

  # make sure there is no /dev/ttyS0
  if [ -e /dev/ttyS0 ] ; then
    rm -f /dev/ttyS0
  fi

	if [ ! -e /var/etc/multimacd.conf ] ; then
		cp $CFG_TEMPLATE_DIR/multimacd.conf /var/etc/
	fi

	if [ ! -e /etc/config/syslog ] ; then
		cp $CFG_TEMPLATE_DIR/syslog /etc/config
	fi
	if [ -e /etc/config/syslog ] ; then
  		. /etc/config/syslog
	fi

}

waitStartupComplete() {
	STEPS=5
    for i in $(seq 1 $STEPS)
    do
		sleep 2
		echo -n "."
        MMDSTATUSPID=`cat /var/status/multimacd.status 2>&1`
        MMDPID=`pidof multimacd`
        if [ "$MMDSTATUSPID" = "$MMDPID" ] 
		then
            echo "OK"
            break
		fi 
        if [ $i -eq $STEPS ]
		then
            echo "ERROR"
        fi
    done
}

start() {
	echo -n "Starting multimacd: "
  if [[ ${HM_MODE} == "HmIP" ]] && [[ ! -z $(cat /var/rf_address) ]]; then
	  init
	  start-stop-daemon -S -N -10 -q -b -m -p $PIDFILE --exec /bin/multimacd -- -f /var/etc/multimacd.conf -l $LOGLEVEL_RFD
	  waitStartupComplete
  else
    echo "not required"
  fi
}
stop() {
	echo -n "Stopping multimacd: "
  if [[ ${HM_MODE} == "HmIP" ]] && [[ ! -z $(cat /var/rf_address) ]]; then
	  start-stop-daemon -K -q -p $PIDFILE
	  rm -f $PIDFILE
  fi
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

