---
apiVersion: v2
name: openccu
description: HomeMatic/homematicIP CCU central based on OpenCCU
home: https://github.com/OpenCCU/OpenCCU
icon: https://raw.githubusercontent.com/OpenCCU/OpenCCU/master/home-assistant-addon/icon.png
keywords:
  - smarthome
  - iot
  - homematic
  - central
maintainers:
  - name: Jens Maus
    email: mail@jens-maus.de
    url: https://github.com/jens-maus
  - name: Angel Nunez Mencias
    email: helm@angelnu.com
    url: https://github.com/angelnu

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 3.83.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 3.83.6.20250824

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 0.2.2

annotations:
  artifacthub.io/changes: |
    - Release of 3.83.6.20250824 (https://github.com/OpenCCU/OpenCCU/releases/tag/3.83.6.20250824)
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Webpage
      url: https://openccu.de/
    - name: Documentation
      url: https://github.com/OpenCCU/OpenCCU/wiki
