#!/bin/sh
if [ -L /media/usb0 ]; then
  if [ "$(readlink /media/usb0)" = "${UM_MOUNTPOINT}" ]; then
    rm -f /var/status/USBinitialised
    # CCU2 compatibility
    rm -f /var/status/SDinitialised
    # remove linked directory
    rm -f /media/usb0
  fi
fi
