#!/bin/sh

STARTPWD=`pwd`
ROOT_FS=rootfs.ext2
KERNEL_IMAGE=uImage

BOOT_DEV=/dev/mmcblk0p1
ROOT_DEV=/dev/mmcblk0p2
USER_DEV=/dev/mmcblk0p3

#if [ -f $STARTPWD/$KERNEL_IMAGE ]; then
# 	echo "Erasing kernel partition ..."            
# 	flash_erase $KERNEL_MTDCHAR 0 0                      
# 	echo "Writing kernel to NAND ..."         
# 	nandwrite -p $KERNEL_MTDCHAR $KERNEL_IMAGE
#fi

if [ -f $STARTPWD/$ROOT_FS ]; then
  	echo "Writing rootfs to mmcblk0p2 ..."
	umount /rootfs
	dd if=$ROOT_FS of=$ROOT_DEV
fi

