#!/bin/sh
#
# Starts HMServer.
#

LOGLEVEL_HMServer=5
CFG_TEMPLATE_DIR=/etc/config_templates
STARTWAITFILE=/var/status/HMServerStarted

[[ -r /var/hm_mode ]] && . /var/hm_mode

# skip this startup in LAN Gateway mode
[[ "${HM_MODE}" == "HM-LGW" ]] && exit 0

if [[ -n "${HM_HMIP_DEV}" ]]; then
  HM_SERVER_TYPE="HMIPServer"
  PIDFILE=/var/run/HMIPServer.pid
else
  HM_SERVER_TYPE="HMServer"
  PIDFILE=/var/run/HMServer.pid
fi

init() {
  export JAVA_HOME=/opt/java/
  export PATH=${PATH}:${JAVA_HOME}/bin

  if [[ ! -e /etc/config/log4j.xml ]]; then
    cp -a ${CFG_TEMPLATE_DIR}/log4j.xml /etc/config
  fi

  if [[ ! -e /etc/config/hmip_networkkey.conf ]]; then
    if [[ -f ${CFG_TEMPLATE_DIR}/hmip_networkkey.conf ]]; then
      cp -a ${CFG_TEMPLATE_DIR}/hmip_networkkey.conf /etc/config
    fi
  fi

  if [[ -n "${HM_HMIP_DEV}" ]]; then
    if [[ ! -e /var/etc/crRFD.conf ]]; then
      cp -a ${CFG_TEMPLATE_DIR}/crRFD.conf /var/etc/
    fi

    # if no raw-uart is used to connect to the rf module
    # we have to set the device node
    if [[ "${HM_HMIP_DEVNODE}" != "/dev/raw-uart" ]]; then
      sed -i "s|^Adapter\.1\.Port=/dev/.*$|Adapter.1.Port=${HM_HMIP_DEVNODE}|" /var/etc/crRFD.conf
      HM_SERVER_PORT=${HM_HMIP_DEVNODE}
    else
      HM_SERVER_PORT=/dev/ttyS0
    fi

    HM_SERVER=/opt/HMServer/HMIPServer.jar
    HM_SERVER_ARGS="/var/etc/crRFD.conf"
  else
    HM_SERVER=/opt/HMServer/HMServer.jar
  fi
}

waitStartupComplete() {
  STEPS=150
  for i in $(seq 1 ${STEPS}); do
    sleep 2
    echo -n "."
    if [[ -e ${STARTWAITFILE} ]]; then
      echo "OK"
      break
    fi
    if [[ ${i} -eq ${STEPS} ]]; then
      echo "ERROR"
    fi
  done
}

start() {
  echo -n "Starting ${HM_SERVER_TYPE}: "
  init
  start-stop-daemon -b -S -q -m -p ${PIDFILE} --exec java -- -Xmx128m -Dos.arch=arm -Dlog4j.configuration=file:///etc/config/log4j.xml -Dfile.encoding=ISO-8859-1 -Dgnu.io.rxtx.SerialPorts=${HM_SERVER_PORT} -jar ${HM_SERVER} ${HM_SERVER_ARGS}
  echo -n "."
  waitStartupComplete
}

stop() {
  echo -n "Stopping ${HM_SERVER_TYPE}: "
  rm -f ${STARTWAITFILE}
  start-stop-daemon -K -q -p ${PIDFILE}
  rm -f ${PIDFILE}
  echo "OK"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
