# OpenCCU Stale workflow
# yamllint disable rule:truthy
---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "40 5 * * *"
  workflow_dispatch:

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-24.04
    steps:
      # The 90 day stale policy
      # Used for:
      # - Issues & PRs
      # - No PRs marked as no-stale or pinned
      # - No issues marked as no-stale, help-wanted or pinned
      - name: 90 days stale issues & PRs policy
        uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 90
          days-before-close: 7
          operations-per-run: 150
          remove-stale-when-updated: true
          exempt-all-milestones: true
          stale-issue-label: ":ice_cube: stale"
          exempt-issue-labels: ":question: undecided,:pray: help wanted"
          stale-issue-message: >
            There hasn't been any activity on this issue recently. To keep our
            backlog manageable we have to clean old issues, as many of them have
            already been resolved with the latest updates.

            Please make sure to update to the latest OpenCCU version and
            check if that solves the issue. Let us know if that works for you by
            adding a comment 👍

            This issue has now been marked as stale and will be closed if no
            further activity occurs. Thank you for your contributions.

          stale-pr-label: ":ice_cube: stale"
          exempt-pr-labels: ":question: undecided,:pray: help wanted"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. This
            pull request has been automatically marked as stale because of that
            and will be closed if no further activity occurs within 7 days.

            Thank you for your contributions.
